#!/usr/bin/env python3
"""The image must actually INSTALL a driver for the GeForce2 GTS and the SB16.

WHY THIS TEST EXISTS. Shipping a driver in $OEM$ and pointing DevicePath at it
is not the same as installing it, and the gap is invisible from the build side.
Both halves of it were measured on .124 (a freshly PXE-imaged Pentium III
845 MHz) on 2026-08-29, from its own C:\\WINDOWS\\setupapi.log:

 1. winnt.sif carries only the SHORT early driver path - LAN and chipset. The
    rest waits for DevicePath, which cmdlines.txt writes at T-12, AFTER GUI
    setup has installed the devices. That log has exactly six
    'Found ... in C:\\D\\' lines and every one names an L (LAN) or C (chipset)
    directory. Not one G, H, I, M, N, S or T was ever consulted, so the whole
    graphics and sound payload was copied, indexed, and ignored.

 2. Even a VISIBLE unsigned INF loses. XP penalises an untrusted driver node by
    +0x8000 in the rank - '#I087 Driver node not trusted, rank changed from
    0x00002000 to 0x0000a000' - so it can never beat a trusted in-box match
    (XP's own nv4_disp scored 0x2001). DriverSigningPolicy=Ignore suppresses the
    DIALOG, not the RANK.

The result was a GeForce2 GTS on Microsoft's in-box nv4 6.14.10.5673 at 800x600
in 16-bit colour, reporting status OK and problem code 0, with ForceWare 71.89
sitting unused in C:\\D\\G005 - and then the agent's reclaim deleted all 2.4 GB
of it because no device carried a problem code.

The fix is an explicit forced install from $OEM$\\$1\\D\\PREFER.TXT, generated by
stage-oem.sh from scripts/pxe/driver-prefs.txt and applied by the agent before
it reclaims. This test checks the image end of that: the list exists, every INF
it names is really there and really declares the device, and it names the build
we verified rather than the first INF that happened to match.

The Sound Blaster is the opposite finding and is checked too, because "no driver
in our payload" is the RIGHT answer there and must not be mistaken for a gap:
the card is an ISA PnP AWE64 and XP's own wdma_ctl.inf drives it.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

IMAGE = '/mnt/retro-share/Files/OS/XPSP3-FLEET'
DTREE = os.path.join(IMAGE, '$OEM$', '$1', 'D')
PREFER = os.path.join(DTREE, 'PREFER.TXT')
REG = os.path.join(IMAGE, '$OEM$', 'retroagent.reg')

# The two devices in the user's report, as PnP spells them.
GF2_GTS = 'PCI\\VEN_10DE&DEV_0150'          # NVIDIA GeForce2 GTS/Pro (NV15)
AWE64 = ['CTL0045', 'CTL0022']              # SB16-compatible audio + wavetable

fails = []


def check(label, cond):
    print(f'  {"PASS" if cond else "FAIL"}  {label}')
    if not cond:
        fails.append(label)


def read(path):
    with open(path, encoding='latin1', errors='replace') as fh:
        return fh.read()


def parse_prefer(text):
    """Same rules as agent/shared/drvprefs.h:drvpref_split() - TAB only."""
    out = []
    for raw in text.split('\n'):
        line = raw.rstrip('\r')
        if not line or line[0] in ';#':
            continue
        if '\t' not in line:
            out.append((line, None))        # malformed; reported below
            continue
        hwid, inf = line.split('\t', 1)
        out.append((hwid.strip(), inf.strip()))
    return out


def main():
    if not os.path.isdir(DTREE):
        print(f'  SKIP  {DTREE} not present (share not mounted)')
        return 0

    print('== the forced-driver list exists and is well formed ==')
    check('$OEM$\\$1\\D\\PREFER.TXT is staged', os.path.isfile(PREFER))
    if not os.path.isfile(PREFER):
        print('\npxe drivers: 1 FAILED (run scripts/pxe/stage-oem.sh)')
        return 1

    entries = parse_prefer(read(PREFER))
    check('it has at least one entry', len(entries) > 0)
    check('every line is <hardware id>TAB<INF path>',
          all(inf for _h, inf in entries))
    entries = [(h, i) for h, i in entries if i]

    # C:\D on the box is $OEM$\$1\D on the share.
    def on_share(win_path):
        p = win_path.replace('/', '\\')
        if not p.upper().startswith('C:\\D\\'):
            return None
        return os.path.join(DTREE, *p[5:].split('\\'))

    check('every INF path is under C:\\D (that is where the payload lands)',
          all(on_share(i) for _h, i in entries))

    missing = [i for _h, i in entries
               if not (on_share(i) and os.path.isfile(on_share(i)))]
    check(f'all {len(entries)} referenced INFs exist on the share', not missing)
    if missing:
        for m in missing[:5]:
            print(f'        missing: {m}')

    print('== every entry names a device its INF really claims ==')
    # A preference that points at an INF not declaring the id is the failure
    # this whole mechanism exists to prevent: it installs confidently and binds
    # nothing.
    lying = []
    cache = {}
    for hwid, inf in entries:
        p = on_share(inf)
        if not p or not os.path.isfile(p):
            continue
        if p not in cache:
            cache[p] = read(p).upper()
        if hwid.upper() not in cache[p]:
            lying.append((hwid, inf))
    check('no entry points at an INF that does not declare it', not lying)
    for h, i in lying[:5]:
        print(f'        {h} not in {i}')

    print('== the GeForce2 GTS is covered, by the build we verified ==')
    gf2 = [(h, i) for h, i in entries if h.upper() == GF2_GTS]
    check(f'{GF2_GTS} is in the list', len(gf2) == 1)
    if gf2:
        inf = gf2[0][1]
        p = on_share(inf)
        text = cache.get(p) or (read(p).upper() if p and os.path.isfile(p) else '')
        # DriverVer 04/01/2005, 7.1.8.9 == ForceWare 71.89. Verified on .124:
        # a forced install of this INF put 6.14.10.7189 on the device.
        check('it points at ForceWare 71.89 (DriverVer 7.1.8.9)',
              '7.1.8.9' in text)
        # THE TRAP. Three directories in the image ship an INF naming DEV_0150,
        # and the FIRST one a search finds is G003\nv4_go.inf - ForceWare 270.61
        # MOBILE, a 2011 driver for a 2000 card. gs_find_inf_for() would pick it.
        base = os.path.basename(inf).lower()
        check('it is not a mobile/"Go" INF (the first-match trap)',
              '_go' not in base and 'mobile' not in text[:4000].lower())
        check('it names the card, so the INF is the desktop NV15 one',
              'GEFORCE2 GTS' in text)

    print('== PnP could find these too, not only the forced install ==')
    # Belt and braces: the forced install is what makes it happen, but if the
    # directory is missing from DevicePath then the Found New Hardware wizard
    # cannot reach it either, and there is no manual fallback.
    if os.path.isfile(REG):
        reg = read(REG)
        m = re.search(r'"DevicePath"=hex\(2\):([0-9a-f,\r\n\\ ]+)', reg)
        if m:
            raw = [b for b in re.sub(r'[\r\n\\ ]', '', m.group(1)).split(',') if b]
            dev = bytes(int(b, 16) for b in raw).decode('latin1').rstrip('\x00')
            dirs = {d.upper() for d in dev.split(';')}
            # os.path.dirname is POSIX here and does not split on '\\'.
            want = {i.replace('/', '\\').rsplit('\\', 1)[0].upper()
                    for _h, i in entries}
            check('every preference directory is also in DevicePath',
                  want <= dirs)
        else:
            check('DevicePath is present in retroagent.reg', False)

    print('== the Sound Blaster: XP\'s own driver is the right one ==')
    # The card on .124 is an ISA PnP Creative AWE64 - ISAPNP\CTL00E4_DEV0000/
    # 0001/0002, compatible ids *CTL0045 and *CTL0022. Creative never shipped an
    # XP driver for their ISA cards and the DriverPacks sound packs are PCI/HDA
    # era, so there is nothing of ours to install: XP's in-box wdma_ctl.inf
    # (CTLSB16.SYS) is the driver, and it must be ON THE MEDIA.
    src = None
    for name in ('WDMA_CTL.IN_', 'wdma_ctl.in_', 'WDMA_CTL.INF', 'wdma_ctl.inf'):
        cand = os.path.join(IMAGE, 'I386', name)
        if os.path.isfile(cand):
            src = cand
            break
    check("I386 ships XP's in-box Creative WDM INF (wdma_ctl.inf)", src is not None)
    if src and shutil.which('cabextract'):
        tmp = tempfile.mkdtemp(prefix='pxedrv')
        try:
            subprocess.run(['cabextract', '-q', '-d', tmp, src],
                           check=False, capture_output=True)
            got = ''
            for f in os.listdir(tmp):
                got += read(os.path.join(tmp, f)).upper()
            for cid in AWE64:
                check(f'  and it declares {cid} (the AWE64 on .124)', cid in got)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    elif src:
        print('  SKIP  cabextract not installed - cannot read inside WDMA_CTL.IN_')

    # Opt-in, because scanning ~500 directories over SMB takes minutes.
    if os.environ.get('PXE_DRIVERS_FULL_SCAN'):
        print('== full-tree scan (PXE_DRIVERS_FULL_SCAN=1) ==')
        found_gf2, found_awe = [], []
        for d in sorted(os.listdir(DTREE)):
            dp = os.path.join(DTREE, d)
            if not os.path.isdir(dp):
                continue
            for f in os.listdir(dp):
                if not f.lower().endswith('.inf'):
                    continue
                t = read(os.path.join(dp, f)).upper()
                if GF2_GTS in t:
                    found_gf2.append(f'{d}\\{f}')
                if any(c in t for c in AWE64):
                    found_awe.append(f'{d}\\{f}')
        check(f'{GF2_GTS} is claimed by a staged INF ({len(found_gf2)} of them)',
              bool(found_gf2))
        print(f'        {", ".join(found_gf2[:6])}')
        # Recorded, not asserted: a staged Creative ISA driver would be a
        # surprise worth looking at, not a failure.
        print(f'        staged INFs claiming an AWE64 id: '
              f'{len(found_awe)} {found_awe[:4]}')

    print(f'\npxe drivers: {"all checks passed" if not fails else str(len(fails)) + " FAILED"}')
    return 1 if fails else 0


if __name__ == '__main__':
    sys.exit(main())
