#!/usr/bin/env python3
"""Thief II (NewDark 1.26) on vcr-kmd: the per-box DISPLAY SYSTEM block.

WHY THIS EXISTS. On .124 (Voodoo 5 6000, our vcr-kmd driver) the staged Thief
II refused to start - "Your video hardware is not supported or no supported
video mode was found" - with vcr-kmd's 32 bpp Direct3D OFF and ON (V5 plan
step 16). Static analysis of the staged Thief2.exe
(voodoo-cleanroom/vcr-kmd/evidence/newdark_thief2/) found why: NewDark's
Direct3D 9 display (`use_d3d_display`, which the staged cam_ext.cfg enables)
renders 32 bpp only and, at EVERY mode set, puts its 2D layer in one texture
the size of the screen rounded up to a power of two - X8R8G8B8/A8R8G8B8,
1024x512 at 640x480, 2048x1024 at 1280x1024. vcr-kmd's DX7-level HAL offers
16-bit textures of at most 256x256, so that CreateTexture fails, StartMode
returns 0 and the screen loop raises the dialog. No cam_ext.cfg option lowers
it.

The fix is in the LIBRARY, per box, like the nGlide swap: where the vcr-kmd
miniport is the running display driver, the launcher moves cam_ext.cfg aside
and NewDark runs its legacy DirectX 6 display at 16 bpp, whose device
validation asks only for what that HAL reports (in-game on vcr-kmd is still to
be seen on the box). Everywhere else nothing changes.

The block is generated by scripts/fleet/stage-fleetres.py (newdark_display_swap)
and these tests pin its LOGIC by executing it in a tiny model of the few
cmd.exe constructs it uses, over every state a box can be in. A construct the
model does not know fails the test instead of being skipped, so the block
cannot grow a line nobody has reasoned about.
"""
import hashlib
import importlib.util
import os
import re
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
STAGER = os.path.join(REPO, 'scripts', 'fleet', 'stage-fleetres.py')
LIB = os.environ.get('RETRO_LIBRARY', '/mnt/retro-share/Files/Games-Library')
THIEF2 = os.path.join(LIB, 'Thief2')
ANALYSED_MD5 = '1109955d4d0a7855592b33d954abcb76'   # the Thief2.exe the analysis read


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


sf = _load('stage_fleetres_nd', STAGER)


def _block():
    pbs = sf.TITLES['Thief2'].get('post', [])
    nd = [pb for pb in pbs if pb.get('marker') == 'ND_DX6']
    assert len(nd) == 1, ('Thief2 has no ND_DX6 display block: on a vcr-kmd box '
                          'NewDark then opens its Direct3D 9 display and refuses '
                          '"Your video hardware is not supported"')
    return nd[0]


# ---------------------------------------------------------------------------
# a model of exactly the cmd.exe constructs the block uses
# ---------------------------------------------------------------------------
class Box:
    def __init__(self, running, files, have_sc=True):
        self.running = set(running)     # services sc.exe reports RUNNING
        self.files = set(files)         # names in the game directory
        self.have_sc = have_sc
        self.env = {}

    def expand(self, s):
        s = s.replace('%~dp0', '')
        return re.sub(r'%([A-Za-z_][A-Za-z0-9_]*)%',
                      lambda m: self.env.get(m.group(1), ''), s)

    def stmt(self, s):
        s = s.strip()
        m = re.fullmatch(r'if (not )?exist "([^"]+)" (.+)', s)
        if m:
            there = self.expand(m.group(2)) in self.files
            if there != bool(m.group(1)):
                self.stmt(m.group(3))
            return
        m = re.fullmatch(r'move /y "([^"]+)" "([^"]+)" >nul', s)
        if m:
            src, dst = self.expand(m.group(1)), self.expand(m.group(2))
            if src in self.files:        # move /y replaces an existing dst
                self.files.discard(src)
                self.files.add(dst)
            return
        m = re.fullmatch(r'set ([A-Za-z_][A-Za-z0-9_]*)=(\S*)', s)
        if m:
            self.env[m.group(1)] = self.expand(m.group(2))
            return
        m = re.fullmatch(r'if "([^"]*)"=="([^"]*)" (.+)', s)
        if m:                            # the single-line form (no block)
            if self.expand(m.group(1)) == m.group(2):
                self.stmt(m.group(3))
            return
        m = re.fullmatch(r'del /q "([^"]+)" >nul 2>&1', s)
        if m:
            self.files.discard(self.expand(m.group(1)))
            return
        m = re.fullmatch(r'echo [^>]+> "([^"]+)"', s)
        if m:
            self.files.add(self.expand(m.group(1)))
            return
        m = re.fullmatch(r'sc query (\S+) 2>nul \| find /i "RUNNING" >nul && (.+)', s)
        if m:
            if self.have_sc and m.group(1) in self.running:
                self.stmt(m.group(2))
            return
        raise AssertionError('the model does not know this line - reason about '
                             'it and teach the model: %r' % s)

    def run(self, lines):
        stack = []                       # one bool per open ( block: executing?
        for raw in lines:
            s = raw.strip()
            live = all(stack)
            if not s or s.lower().startswith('rem '):
                continue
            m = re.fullmatch(r'if "([^"]*)"=="([^"]*)" \(', s)
            if m:
                stack.append(live and self.expand(m.group(1)) == m.group(2))
                continue
            if s == ') else (':
                outer = all(stack[:-1])
                stack[-1] = outer and not stack[-1]
                continue
            if s == ')':
                stack.pop()
                continue
            if live:
                self.stmt(s)
        assert not stack, 'unbalanced ( ) in the block'
        return self


EXT, ASIDE = 'cam_ext.cfg', 'cam_ext.cfg.d3d9'


def _run(running, files, have_sc=True):
    return Box(running, files, have_sc).run(_block()['lines'])


# ---------------------------------------------------------------------------
# the recipe
# ---------------------------------------------------------------------------
def test_thief2_carries_the_display_block_before_the_game_starts():
    pb = _block()
    assert pb['file'] == 'Play Thief 2.bat'
    assert pb['before'] == 'start "" Thief2.exe', (
        'the block must run BEFORE the game reads cam_ext.cfg')
    assert 'ND_DX6' in '\n'.join(pb['lines'])


def test_vcrkmd_box_gets_the_dx6_display():
    """.124's first launch after a sync: the library's cam_ext.cfg goes aside."""
    box = _run({'vcrmp'}, {EXT, 'cam.cfg'})
    assert EXT not in box.files and ASIDE in box.files
    assert box.env['ND_DX6'] == '1'


def test_vcrkmd_box_is_steady_on_the_next_launch():
    box = _run({'vcrmp'}, {ASIDE})
    assert box.files == {ASIDE}


def test_a_sync_that_restores_cam_ext_is_undone_at_the_next_launch():
    """GAMESYNC never deletes and does restore a missing file, so on the vcr-kmd
    box both can exist; `move /y` must replace the old aside copy."""
    box = _run({'vcrmp'}, {EXT, ASIDE})
    assert box.files == {ASIDE}


def test_every_other_gpu_keeps_direct3d_9_untouched():
    """A GeForce/Radeon/Intel box must not have its file moved or rewritten."""
    for running in (set(), {'nv4', 'ati2mtag', 'ialm'}):
        box = _run(running, {EXT})
        assert box.files == {EXT}, running
        assert box.env['ND_DX6'] == '0'


def test_the_file_comes_back_when_the_driver_changes():
    """Two-way, like glide_swap: after a rollback to the vendor driver (the
    vcrmp key stays, the miniport no longer runs) Direct3D 9 returns."""
    box = _run(set(), {ASIDE})
    assert box.files == {EXT}


def test_a_box_with_both_keeps_the_library_file():
    box = _run(set(), {EXT, ASIDE})
    assert EXT in box.files


def test_a_probe_that_cannot_run_is_the_librarys_own_behaviour():
    """No sc.exe (or any probe failure) must mean Direct3D 9 - the status quo -
    never the DX6 fallback. No box may be made worse by a failed probe."""
    box = _run({'vcrmp'}, {EXT}, have_sc=False)
    assert box.files == {EXT} and box.env['ND_DX6'] == '0'


def test_the_test_is_the_running_service_not_its_key():
    """A rollback leaves Services\\vcrmp behind with the device bound to the
    vendor driver; a key-presence test would keep that box on DX6 forever."""
    text = '\n'.join(_block()['lines'])
    assert re.search(r'^sc query vcrmp .*find /i "RUNNING"', text, re.M)
    assert 'reg query' not in text.lower()
    assert text.index('set ND_DX6=0') < text.index('sc query')


def test_the_block_is_plain_cmd():
    """The repo-wide traps: no doubled percent outside a for loop, no
    parentheses inside a value that cmd.exe expands in a block."""
    for line in _block()['lines']:
        assert not re.search(r'%%[A-Za-z_]', line), line
        if not line.lower().startswith('rem '):
            body = line.strip()
            assert body.count('(') <= 1 and body.count(')') <= 1, line


def test_staging_the_block_is_idempotent_and_refreshable(tmp_path):
    """post_block inserts it once, skips it when current, and a changed recipe
    replaces an older copy in place instead of stacking a second one."""
    t = tmp_path / 'Thief2'
    t.mkdir()
    launcher = ('@echo off\r\ncall "%~dp0FLEETRES.BAT"\r\n'
                'cd /d "%~dp0"\r\nstart "" Thief2.exe\r\nexit\r\n')
    (t / 'Play Thief 2.bat').write_bytes(launcher.encode('latin1'))
    pb = _block()
    r = sf.Runner(str(tmp_path), False, False)
    r.post_block(str(t), 'Thief2', pb)
    once = (t / 'Play Thief 2.bat').read_bytes().decode('latin1')
    assert once.count('set ND_DX6=0') == 1
    assert once.index('set ND_DX6=0') < once.index('start "" Thief2.exe')
    assert '\r\n' in once and '\n' not in once.replace('\r\n', '')
    r.post_block(str(t), 'Thief2', pb)
    assert (t / 'Play Thief 2.bat').read_bytes().decode('latin1') == once
    # an older version of the block (its first line intact) is refreshed
    stale = once.replace('move /y "%~dp0cam_ext.cfg" "%~dp0cam_ext.cfg.d3d9" >nul',
                         'rem an older body')
    (t / 'Play Thief 2.bat').write_bytes(stale.encode('latin1'))
    r.post_block(str(t), 'Thief2', pb)
    assert (t / 'Play Thief 2.bat').read_bytes().decode('latin1') == once


# ---------------------------------------------------------------------------
# the library the block relies on (skips LOUDLY when the share is absent)
# ---------------------------------------------------------------------------
def _lib_file(name):
    """case-insensitive: the tree ships USER.CFG and cam.cfg side by side"""
    if not os.path.isdir(THIEF2):
        pytest.skip('library not mounted at %s - the share-side NewDark checks '
                    'did NOT run; this is not a pass' % LIB)
    for n in os.listdir(THIEF2):
        if n.lower() == name.lower():
            return os.path.join(THIEF2, n)
    return None


def _active(path, var):
    """lines that DEFINE var (Dark config: a var is on by being present)"""
    if not path:
        return []
    with open(path, 'rb') as fh:
        text = fh.read().decode('latin1')
    return [l for l in text.splitlines()
            if re.match(r'\s*%s(\s|$)' % re.escape(var), l, re.I)]


def test_moving_cam_ext_aside_really_leaves_dx6_at_16_bpp():
    """The block works only because the Direct3D 9 switches live in
    cam_ext.cfg ALONE. If one of them moves into a file the game always
    reads, the fallback stops falling back - silently."""
    assert _active(_lib_file('cam_ext.cfg'), 'use_d3d_display'), (
        'cam_ext.cfg no longer enables use_d3d_display - re-check the block')
    for cfg in ('cam.cfg', 'user.cfg', 'dark.cfg', 'darkinst.cfg', 'install.cfg'):
        path = _lib_file(cfg)
        for var in ('use_d3d_display', 'force_32bit', 'force_32bit_textures'):
            assert not _active(path, var), (
                '%s defines %s: moving cam_ext.cfg aside no longer gives a '
                'vcr-kmd box the 16 bpp DX6 display' % (cfg, var))
    depth = _active(_lib_file('cam.cfg'), 'game_screen_depth')
    assert depth and depth[-1].split()[1] == '16', depth


def test_the_staged_exe_is_the_one_that_was_analysed():
    """The addresses and the conclusion come from one build. A new NewDark
    means re-running evidence/newdark_thief2/newdark_dis.py, not trusting it."""
    exe = _lib_file('Thief2.exe')
    assert exe, 'Thief2.exe missing from the staged tree'
    with open(exe, 'rb') as fh:
        md5 = hashlib.md5(fh.read()).hexdigest()
    assert md5 == ANALYSED_MD5, (
        'staged Thief2.exe is %s, the display analysis read %s - re-derive it '
        '(voodoo-cleanroom/vcr-kmd/evidence/newdark_thief2/newdark_dis.py)'
        % (md5, ANALYSED_MD5))


class _StuckBox(Box):
    """A box where the move cannot happen (a read-only cam_ext.cfg.d3d9 left
    by hand blocks `move /y`)."""
    def stmt(self, s):
        if s.strip().startswith('move /y'):
            return
        super().stmt(s)


def test_a_failed_move_is_written_down_not_swallowed():
    b = _StuckBox({"vcrmp"}, {EXT}).run(_block()["lines"])
    assert EXT in b.files and "nd_dx6-error.txt" in b.files


def test_a_move_that_worked_leaves_no_error_file_even_a_stale_one():
    b = _run({"vcrmp"}, {EXT, "nd_dx6-error.txt"})
    assert ASIDE in b.files and EXT not in b.files
    assert "nd_dx6-error.txt" not in b.files


def test_a_d3d_box_never_gets_an_error_file():
    b = _run(set(), {EXT})
    assert "nd_dx6-error.txt" not in b.files and EXT in b.files
