/* test_driver_prefs.c - TRUE-SOURCE: compiles agent/shared/drvprefs.h, the
 * logic behind C:\D\PREFER.TXT and the driver-payload reclaim gate.
 *
 * THE BUG THIS PINS (found 2026-08-29 on .124, a freshly PXE-imaged Pentium III
 * 845 MHz with a GeForce2 GTS). The box came up on Microsoft's in-box nv4
 * 6.14.10.5673 at 800x600 in 16-bit colour while ForceWare 71.89 sat unused in
 * C:\D\G005. Two silent mechanisms put it there:
 *
 *   1. winnt.sif carries only the SHORT early driver path (LAN + chipset); the
 *      rest waits for DevicePath, which cmdlines.txt writes at T-12 - AFTER GUI
 *      setup has installed the devices. That box's setupapi.log has exactly six
 *      "Found ... in C:\D\" lines and every one is an L or a C directory.
 *   2. Even a VISIBLE unsigned INF is penalised +0x8000 in XP's driver rank
 *      ("#I087 Driver node not trusted, rank changed from 0x2000 to 0xa000")
 *      and loses to any trusted in-box match. DriverSigningPolicy=Ignore
 *      suppresses the dialog, not the rank.
 *
 * The device therefore ends at PROBLEM CODE 0 - it reports itself as perfect -
 * and gs_reclaim_drivers() read that as "setup is finished with the drivers"
 * and deleted 2.4 GB of NVIDIA drivers off the machine that needed them. The
 * box was left with neither the right driver nor the payload to fix itself.
 *
 * Fix: agent 1.59.0 forces the listed drivers (gs_apply_driver_prefs) BEFORE
 * reclaiming, and the reclaim refuses while an applicable preference is
 * unsatisfied. Each check below asserts the FIXED answer and, where they
 * differ, the OLD BUGGY one.
 */

#include "munit.h"
#include <stdio.h>
#include <string.h>

#include "../../agent/shared/drvprefs.h"

/* The real hardware ids .124 reported, in the shape gs_present_device_ids()
 * builds: upper-case, one per line, leading and trailing newline. */
static const char IDS_124[] =
    "\n"
    "PCI\\VEN_10DE&DEV_0150&SUBSYS_002E10DE&REV_A4\n"
    "PCI\\VEN_10DE&DEV_0150&SUBSYS_002E10DE\n"
    "PCI\\VEN_10DE&DEV_0150&CC_030000\n"
    "PCI\\VEN_10DE&DEV_0150\n"
    "ISAPNP\\CTL00E4_DEV0000\n"
    "*CTL0045\n"
    "PCI\\VEN_8086&DEV_1229&SUBSYS_000C8086&REV_08\n";

/* A box with a DIFFERENT NVIDIA card - the GeForce4 Ti 4600 in .133. */
static const char IDS_133[] =
    "\n"
    "PCI\\VEN_10DE&DEV_0250&SUBSYS_00000000&REV_A3\n"
    "PCI\\VEN_10DE&DEV_0250\n";

/* The gate that shipped: gs_reclaim_drivers() asked gs_devices_unconfigured()
 * for a count of devices carrying a PROBLEM CODE, and deleted C:\D when that
 * count was zero. Reproduced here so the two answers can be compared on the
 * same inputs - the point of the fix is that they disagree. */
static int old_reclaim_gate(int devices_with_problem_code)
{
    return devices_with_problem_code == 0;      /* non-zero = "delete C:\D" */
}

int main(void)
{
    printf("== PREFER.TXT lines split on TAB, and only on TAB ==\n");
    {
        char  line[] = "PCI\\VEN_10DE&DEV_0150\tC:\\D\\G005\\nv4_disp.inf";
        char *h = NULL, *i = NULL;
        CHECK(drvpref_split(line, &h, &i) == 1, "a well-formed line splits");
        CHECK(h && strcmp(h, "PCI\\VEN_10DE&DEV_0150") == 0,
              "hardware id is everything before the tab");
        CHECK(i && strcmp(i, "C:\\D\\G005\\nv4_disp.inf") == 0,
              "INF path is everything after it");
    }
    {
        /* Amigamerlin's tree really does have spaces in its directory names,
         * so splitting on whitespace would truncate the path and leave a file
         * that does not exist. */
        char  line[] = "PCI\\VEN_121A&DEV_0005\tC:\\D\\V001\\Amigamerlin 3.1\\v.inf";
        char *h = NULL, *i = NULL;
        CHECK(drvpref_split(line, &h, &i) == 1, "a path with spaces still splits");
        CHECK(i && strcmp(i, "C:\\D\\V001\\Amigamerlin 3.1\\v.inf") == 0,
              "the space in the path is kept, not treated as a separator");
    }
    {
        char c1[] = "; generated by stage-oem.sh";
        char c2[] = "# also a comment";
        char c3[] = "PCI\\VEN_10DE&DEV_0150 C:\\D\\G005\\nv4_disp.inf";  /* space */
        char c4[] = "";
        char *h, *i;
        CHECK(!drvpref_split(c1, &h, &i), "';' comments are skipped");
        CHECK(!drvpref_split(c2, &h, &i), "'#' comments are skipped");
        CHECK(!drvpref_split(c3, &h, &i),
              "a space-separated line is REJECTED, not half-parsed");
        CHECK(!drvpref_split(c4, &h, &i), "a blank line is skipped");
    }
    {
        /* stage-oem.sh writes CRLF, because everything else in the image does. */
        char  line[] = "PCI\\VEN_10DE&DEV_0150\tC:\\D\\G005\\nv4_disp.inf\r";
        char *h = NULL, *i = NULL;
        CHECK(drvpref_split(line, &h, &i) == 1, "a CRLF line splits");
        CHECK(i && strcmp(i, "C:\\D\\G005\\nv4_disp.inf") == 0,
              "the CR is stripped - it would otherwise be part of the filename");
    }

    printf("== a preference matches a device id by LINE PREFIX ==\n");
    {
        CHECK(drvpref_present(IDS_124, "PCI\\VEN_10DE&DEV_0150"),
              ".124's GeForce2 GTS matches, suffixes and all");
        CHECK(!drvpref_present(IDS_124, "PCI\\VEN_10DE&DEV_0250"),
              ".124 does not have a GeForce4 Ti");
        CHECK(drvpref_present(IDS_133, "PCI\\VEN_10DE&DEV_0250"),
              ".133's GeForce4 Ti matches on its own box");
        CHECK(!drvpref_present(IDS_133, "PCI\\VEN_10DE&DEV_0150"),
              "and .133 does not have a GeForce2 - one list, right answer per box");
        CHECK(drvpref_present(IDS_124, "ISAPNP\\CTL00E4"),
              "the ISA PnP AWE64 matches on its enumerator-qualified id");
    }
    {
        /* THE OLD-BUGGY VALUE. A bare strstr() would accept a preference that
         * forgot the enumerator prefix, because the string still occurs inside
         * ISAPNP\CTL00E4_DEV0000. That rule matches by accident here and fails
         * on any box whose enumerator differs - and the accident is what gets
         * copied into the next entry. */
        const char *sloppy = "CTL00E4_DEV0000";
        CHECK(strstr(IDS_124, sloppy) != NULL,
              "a bare substring search WOULD match the sloppy id (the old bug)");
        CHECK(!drvpref_present(IDS_124, sloppy),
              "line-anchored matching rejects it, so the rule must be written "
              "with its enumerator");
    }
    {
        CHECK(!drvpref_present(NULL, "PCI\\VEN_10DE&DEV_0150"),
              "no device list -> no match (never force on a guess)");
        CHECK(!drvpref_present(IDS_124, ""),
              "an empty id matches nothing, rather than everything");
    }

    printf("== the reclaim gate: may C:\\D be deleted yet? ==\n");
    {
        /* present, INF there, not yet installed -> the .124 case exactly. */
        CHECK(drvpref_blocks(1, 0, 1) == 1,
              "hardware we have, still on the wrong driver -> KEEP C:\\D");
        /* THE OLD-BUGGY ANSWER, on the same inputs. .124's GeForce2 was
         * status OK / problem code 0 while sitting on the wrong driver, so
         * the old gate deleted the payload for exactly the state above. */
        {
            int old_says_delete = old_reclaim_gate(0);
            int new_says_delete = !drvpref_blocks(1, 0, 1);
            CHECK(old_says_delete == 1,
                  "the old gate DELETED here - the problem-code count was 0");
            CHECK(new_says_delete == 0,
                  "the new gate KEEPS here - the preference is unsatisfied");
            CHECK(old_says_delete != new_says_delete,
                  "the two gates disagree on the .124 state; that disagreement "
                  "IS the fix");
        }

        CHECK(drvpref_blocks(1, 1, 1) == 0,
              "once forced onto our driver, the payload may go");
        CHECK(drvpref_blocks(0, 0, 1) == 0,
              "hardware this box does NOT have must never hold 2.4 GB - that "
              "would refill the 6 GB Gateway the reclaim exists for");
        CHECK(drvpref_blocks(1, 0, 0) == 1,
              "an INF that is not there blocks: better a full disk than a "
              "half-install nobody can retry");
        CHECK(drvpref_blocks(0, 0, 0) == 0,
              "a missing INF for absent hardware is still irrelevant");
    }

    printf("== ordering: apply BEFORE reclaim ==\n");
    {
        /* The invariant, stated as arithmetic: a preference can only be
         * satisfied while the tree still exists, so any sequence that reclaims
         * first leaves it permanently unsatisfiable. */
        int tree_present = 1, satisfied = 0;
        /* right order */
        satisfied = tree_present ? 1 : 0;      /* gs_apply_driver_prefs() */
        if (!drvpref_blocks(1, satisfied, 1))
            tree_present = 0;                  /* gs_reclaim_drivers() */
        CHECK(satisfied == 1 && tree_present == 0,
              "apply then reclaim: driver installed AND the space recovered");

        /* wrong order - what shipped */
        tree_present = 1; satisfied = 0;
        tree_present = 0;                      /* reclaim first */
        satisfied = tree_present ? 1 : 0;      /* nothing left to install from */
        CHECK(satisfied == 0,
              "reclaim then apply: the driver can never be installed again - "
              "this is the state .124 was found in");
    }

    printf("\n%s\n", munit_fails ? "FAILURES"
                                 : "driver prefs: force-install gates the reclaim");
    return munit_fails ? 1 : 0;
}
