/* test_icon_bay.c - the wallpaper's icon bay and the agent's icon arranger must
 * describe the SAME grid.
 *
 * WHAT THIS PROTECTS. The wallpaper draws a visible slot for every desktop icon
 * position; the agent then moves the icons into those slots. Two pieces of code
 * in two languages computing one geometry is a drift hazard, and the previous
 * generation of this feature drifted exactly that way: gen_matrix_wall.py
 * reserved a dark "icon well" in the bottom-LEFT while arrange_icons.exe parked
 * icons in the bottom-RIGHT. The art and the icons sat on top of each other and
 * nobody noticed, because each half was correct on its own.
 *
 * So this mirrors gs_icon_bay() from agent/src/gamesync.c and checks it against
 * the numbers gen_retro_wall.py produces, at every resolution the fleet uses.
 * The expected values below are generated by that script - if you change the
 * layout, regenerate them, and the two stay married.
 */

#include "munit.h"
#include <stdio.h>
#include <string.h>

typedef struct { int x, y, cell_w, cell_h, cols, rows; } gs_bay_t;

/* Verbatim copy of gs_icon_bay() in agent/src/gamesync.c. */
static void gs_icon_bay(int w, int h, gs_bay_t *b)
{
    int margin_x = (int)(w * 0.018);
    int margin_y = (int)(h * 0.030);
    const int header_h = 34;

    b->cell_w = 76;
    b->cell_h = 80;
    if (margin_x < 18) margin_x = 18;
    if (margin_y < 18) margin_y = 18;
    b->cols = (int)((w * 0.34) / b->cell_w);
    if (b->cols < 2) b->cols = 2;
    b->rows = (h - margin_y - header_h - 24) / b->cell_h;
    if (b->rows < 3) b->rows = 3;
    b->x = margin_x;
    b->y = margin_y + header_h;
}

/* Produced by: python3 scripts/retro-wallpaper/gen_retro_wall.py --out ... */
struct expect { int w, h, x, y, cols, rows; };
static const struct expect EXPECT[] = {
    {  800,  600, 18, 52, 3,  6 },
    { 1024,  768, 18, 57, 4,  8 },
    { 1280, 1024, 23, 64, 5, 11 },
    { 1600, 1200, 28, 70, 7, 13 },
    { 1280,  800, 23, 58, 5,  8 },
    { 1440,  900, 25, 61, 6, 10 },
    { 1920, 1080, 34, 66, 8, 12 },
};

int main(void)
{
    unsigned i;
    char msg[160];

    printf("== the agent's bay matches the wallpaper's, at every fleet resolution ==\n");
    for (i = 0; i < sizeof(EXPECT) / sizeof(EXPECT[0]); i++) {
        gs_bay_t b;
        const struct expect *e = &EXPECT[i];
        gs_icon_bay(e->w, e->h, &b);
        sprintf(msg, "%dx%d origin", e->w, e->h);
        CHECK(b.x == e->x && b.y == e->y, msg);
        sprintf(msg, "%dx%d grid", e->w, e->h);
        CHECK(b.cols == e->cols && b.rows == e->rows, msg);
        if (b.x != e->x || b.y != e->y || b.cols != e->cols || b.rows != e->rows)
            printf("      got (%d,%d) %dx%d, want (%d,%d) %dx%d\n",
                   b.x, b.y, b.cols, b.rows, e->x, e->y, e->cols, e->rows);
    }

    printf("== the bay always fits on screen ==\n");
    for (i = 0; i < sizeof(EXPECT) / sizeof(EXPECT[0]); i++) {
        gs_bay_t b;
        const struct expect *e = &EXPECT[i];
        gs_icon_bay(e->w, e->h, &b);
        sprintf(msg, "%dx%d bay right edge is on screen", e->w, e->h);
        CHECK(b.x + b.cols * b.cell_w <= e->w, msg);
        sprintf(msg, "%dx%d bay bottom edge is on screen", e->w, e->h);
        CHECK(b.y + b.rows * b.cell_h <= e->h, msg);
        /* The bay must not eat the whole screen - the art needs room, and an
         * icon column wider than about a third stops reading as a sidebar. */
        sprintf(msg, "%dx%d bay leaves room for the art", e->w, e->h);
        CHECK(b.x + b.cols * b.cell_w < (int)(e->w * 0.45), msg);
    }

    printf("== the smallest screen still holds a usable library ==\n");
    {
        gs_bay_t b;
        gs_icon_bay(800, 600, &b);
        /* 22 games plus My Computer / Recycle Bin will overflow 3x6 at 800x600.
         * That is expected and handled - the arranger keeps packing downward -
         * but the FIRST screenful must at least be respectable. */
        CHECK(b.cols * b.rows >= 18, "800x600 shows at least 18 slots");
    }

    printf("== degenerate inputs do not produce a nonsense grid ==\n");
    {
        gs_bay_t b;
        gs_icon_bay(320, 240, &b);
        CHECK(b.cols >= 2, "a tiny screen still gets 2 columns");
        CHECK(b.rows >= 3, "a tiny screen still gets 3 rows");
        CHECK(b.x >= 18 && b.y >= 18, "margins never collapse to zero");
    }

    printf("\n%s\n", munit_fails ? "FAILURES"
                                 : "icon bay: agent and wallpaper agree");
    return munit_fails ? 1 : 0;
}
