#!/usr/bin/env bash
# Unreal Gold 226 dedicated server on the dev host - Wine in a container.
# --net=host: UE1 answers on UDP 7807 (query 7808, LAN beacon 7775) and the
# fleet reaches it by direct address / broadcast on the flat 192.168.1.0/24
# subnet. UE1 binds INADDR_ANY, so every host interface is covered.
set -euo pipefail
GAME_DIR="${GAME_DIR:-$HOME/unrealgold-server}"
IMAGE="${IMAGE:-retro-wine:bookworm}"
NAME="${NAME:-ugsrv}"
docker rm -f "$NAME" >/dev/null 2>&1 || true
# --user: run as the tree's owner, not the image's root. UCC writes ucc.log and
# saves UnrealServer.ini back into the bind-mounted tree, and root-owned files
# there cannot be regenerated by install.sh afterwards. HOME and the prefix
# live in the container's /tmp so wine can create them as this uid.
exec docker run --rm --init --name "$NAME" --net=host \
    --user "$(id -u):$(id -g)" -e HOME=/tmp \
    -v "$GAME_DIR:/game" \
    -e WINEDEBUG=-all -e WINEPREFIX=/tmp/wp \
    -e UG_MAP="${UG_MAP:-DmDeck16.unr}" \
    -e UG_PORT="${UG_PORT:-7807}" \
    -e UG_MAXPLAYERS="${UG_MAXPLAYERS:-12}" \
    "$IMAGE" \
    /game/_run/entry.sh
