#!/usr/bin/env python3
"""The Windows 9x lane of library titles that ALSO serve the NT fleet.

WHY THIS EXISTS. A staged title deploys to every box, and on Windows 98 SE
(.243 - a Pentium 166 with a Voodoo 2, a Cirrus GD5436 and an SB16; and the
W98BUILD VM shaped like it) the title's NT launchers cannot run: they are
cmd.exe dialect (%~dp0, cd /d, start "", if-blocks) and COMMAND.COM starts
none of them. Those boxes need launchers of their own - a Voodoo launcher that
renders through the 3dfx MiniGL or Glide, a DOS launcher that runs the game's
own DOS build in a DOS box - with requires.json rules that put each launcher
on the right boxes and keep the NT ones off Win9x.

Until now those launchers were hand-written on the share, with nothing in the
repo that could regenerate one, check one, or say what it should contain. This
generator owns them, the same way stage-fleetres.py owns the FLEETRES blocks:

  * each launcher's whole text (COMMAND.COM dialect, checked by
    libmeta.command_com_problems() before anything is written - a launcher that
    fails it stops the run, it is never shipped);
  * the binary payloads a launcher needs (md5-pinned, scripts/fleet/libsource.py),
    the small text files it reads (HLV9X.REG), and files DERIVED from another
    library file (Unreal Gold's System\\Voodoo.tpl, made from its Unreal.ini
    and remade whenever that changes);
  * its launch.txt rows and requires.json rules - MERGED, never templated
    (scripts/fleet/libmeta.py): other generators and people own the rest;
  * the removal of a file it shipped and then replaced - LAST, and only while
    the file holds exactly the bytes it shipped (md5-pinned).

Titles: Quake1 and Descent2 (DOS builds and the Quake MiniGL), and the Win9x
3dfx Voodoo launchers of SiNGold, HalfLife1, Quake2Complete, UnrealGold and
Carmageddon2. The game-local Glide/IPX wrappers those last two shipped LIVE
are renamed inert by stage-fleetres.py ("GAME-LOCAL WRAPPERS SHIP UNDER INERT
NAMES"), which owns their NT launchers.

    python3 scripts/fleet/stage-win9x.py                 # apply
    python3 scripts/fleet/stage-win9x.py --check         # exit 1 if the share differs
    python3 scripts/fleet/stage-win9x.py --dry-run       # say what would change
    python3 scripts/fleet/stage-win9x.py --only Quake1   # one title

Writes go through scripts/fleet/libwrite.py: one file at a time, read back
through /mnt (md5 + a fresh write time) before the next, the first failure
stops the run. Identical bytes are never rewritten. It never creates a title,
never deletes a launcher (GAMESYNC never deletes either - a box keeps an old
launcher until someone removes it, so a superseded one is left for a person to
delete once its replacement is verified on hardware), and writes launch.txt
LAST so no box can sync a row that names a launcher not yet on the share.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import libmeta    # noqa: E402
import libsource  # noqa: E402
import libwrite   # noqa: E402

LIB_DEFAULT = "/mnt/retro-share/Files/Games-Library"


def crlf(text):
    return text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\r\n")


# ==========================================================================
# Quake (1996) - Quake1
# ==========================================================================
# Measured on .243 and in the Win98 build VM (2026-09-24 .. 10-01):
#   * GLQuake 0.97 (engine 1.09) over the 3dfx MiniGL in VOODOO\ runs at
#     640x480x16 (49.4 / 49.8 / 44.9 fps, demo1-3) and 800x600x16 (44.6 fps);
#     512x384 is REFUSED - "Specified video mode not available" - because the
#     Cirrus does not enumerate it. A Voodoo 2 has no 32-bit mode; a Voodoo 1
#     has no 800x600.
#   * DOS QUAKE.EXE 1.08 in a Win98 DOS box stops at "MSCDEX not loaded ...
#     press a key" without -nocdaudio and at "CENTER the joystick and press
#     button 1" with the gameport stick fitted, without -nojoy.
#     vid_describemodes lists modes 0-10 only (VGA 320x200 and Mode X up to
#     360x480): the Cirrus BIOS is VBE 1.2, and Quake's VESA modes need 2.0.
#   * WINQUAKE.EXE stops at "MGL Fatal Error!" there, so a Win9x box gets the
#     DOS build, not WinQuake.
#
# 8.3 NAMES. The Win98 shell stores the 8.3 alias of a shortcut's target in its
# PIF, and a long name's alias (PLAYQU~4.BAT) depends on the order the files
# were created in; the real-DOS menu (DOSGAME.TXT) reads 8.3 names too. The
# display names of the two icons .243 already has are unchanged, so their PIFs
# are rewritten in place rather than swept.

Q1V640 = r"""@echo off
rem Quake - 3dfx Voodoo, 640x480x16: GLQuake over the 3dfx MiniGL in VOODOO.
rem Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.
rem
rem RUNS UNDER BOTH SHELLS: Win98 COMMAND.COM and XP cmd.exe. So no
rem percent-tilde paths, no cd /d and no start with a window title - all
rem NT-only. The desktop shortcut starts in this folder, which is also where
rem Quake looks for ID1.
rem
rem VOODOO holds a copy of GLQUAKE.EXE beside the 3dfx MiniGL, named
rem OPENGL32.DLL - the Quake II 3.20 build, which has no P6 or MMX
rem instructions and so runs on a Pentium without MMX. Windows loads a DLL
rem from the exe's own folder first, so only THIS launcher uses the MiniGL.
rem The shared GLQUAKE.EXE keeps the system OpenGL on every other box.
rem
rem 640x480x16 is the mode EVERY Voodoo scans out: a Voodoo 1 has no 800x600
rem and no Voodoo 1 or 2 has a 32-bit mode. On .243's Voodoo 2 it ran 49.4,
rem 49.8 and 44.9 fps in demo1-3. The Voodoo 2's 800x600 is Q1V800.BAT -
rem measured working there too, so the old note that an 8 MB card cannot
rem hold it was wrong. A Voodoo 1 or 2 renders at its own mode whatever the
rem desktop is, so FLEETRES does not apply here.
rem
rem Agents older than 1.84.0 ignore the glide requirement in requires.json,
rem so this launcher checks for Glide itself rather than failing in the game.
if not exist VOODOO\GLQUAKE.EXE goto notree
rem
rem A VOODOO 4/5 - VSA-100, PCI 121A:0009 - IS NOT A VOODOO 1/2. This
rem MiniGL cannot drive one: on .124, a V5 6000, wglCreateContext fails
rem before the MiniGL ever calls grSstWinOpen, while the Glide 2 path under
rem it works - glide2probe, 2026-09-28. On that card the SYSTEM OpenGL
rem driver is itself Glide-backed, so the honest answer for this shortcut
rem there is Play Quake.bat: the same GLQuake, on the 3dfx card, at the fleet
rem resolution. Where another card drives the desktop, as on .143, that is
rem the other card. Detected on NT only - Win98 has no reg.exe and keeps
rem the MiniGL; the reg lines below are never reached there.
if not exist %windir%\system32\reg.exe goto novsa
rem Enum\PCI's subkeys are the WHOLE id (VEN_121A&DEV_0009&SUBSYS_...&REV_..),
rem so list them and match the prefix - a query of ...\PCI\VEN_121A&DEV_0009
rem finds no such key (the first version of this test, 2026-09-28).
reg query "HKLM\SYSTEM\CurrentControlSet\Enum\PCI" 2>nul | find /i "VEN_121A&DEV_0009" >nul
if errorlevel 1 goto novsa
echo This is a 3dfx Voodoo 4/5. The Voodoo 1/2 MiniGL cannot drive it, so
echo Quake runs through the system OpenGL driver instead.
call "Play Quake.bat"
goto end
:novsa
if exist %windir%\SYSTEM32\GLIDE2X.DLL goto glide
if exist %windir%\SYSTEM\GLIDE2X.DLL goto glide
echo.
echo  No 3dfx Glide driver is installed on this machine.
echo  This shortcut is for a 3dfx Voodoo card - use Play Quake instead.
echo.
pause
goto end
:glide
start /w VOODOO\GLQUAKE.EXE -width 640 -height 480 -bpp 16
rem A fullscreen Glide game can leave the 2D desktop unpainted when it exits,
rem which looks exactly like a hung machine. Repaint it.
if exist VOODOO\DESKFIX9.EXE VOODOO\DESKFIX9.EXE
goto end
:notree
echo VOODOO\GLQUAKE.EXE is missing - the Quake tree is incomplete.
pause
:end
"""

Q1V800 = r"""@echo off
rem Quake - 3dfx Voodoo 800x600x16, GLQuake over the 3dfx MiniGL in VOODOO.
rem Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.
rem A Voodoo 2's largest single-card mode - 44.6 fps on .243 against 46.5 at
rem 640x480, so the Pentium is the limit, not the card. A Voodoo 1 has no
rem 800x600, and 512x384 is refused on .243 because its Cirrus does not
rem enumerate that mode. COMMAND.COM dialect; shown only on Win9x boxes with
rem Glide - requires.json - and it checks for Glide itself for agents older
rem than 1.84.0.
if not exist VOODOO\GLQUAKE.EXE goto notree
if exist %windir%\SYSTEM32\GLIDE2X.DLL goto glide
if exist %windir%\SYSTEM\GLIDE2X.DLL goto glide
echo.
echo  No 3dfx Glide driver is installed on this machine.
echo.
pause
goto end
:glide
start /w VOODOO\GLQUAKE.EXE -width 800 -height 600 -bpp 16
rem Repaint a desktop the Glide game left unpainted.
if exist VOODOO\DESKFIX9.EXE VOODOO\DESKFIX9.EXE
goto end
:notree
echo VOODOO\GLQUAKE.EXE is missing - the Quake tree is incomplete.
pause
:end
"""


def q1dos(mode=None):
    run = "QUAKE.EXE -nojoy -nocdaudio -winmem 16"
    head = [
        "@echo off",
        "rem Quake - the DOS build, QUAKE.EXE 1.08, software rendering, in a Windows 9x",
        "rem DOS box. Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.",
        "rem COMMAND.COM dialect. The desktop shortcut starts in this folder and the",
        "rem DOS box goes full screen when Quake sets its video mode.",
    ]
    if mode is None:
        head += [
            "rem No mode is forced: mode 0, 320x200, or the one saved with D under",
            "rem Options, Video Options - which lists every mode this card offers. On",
            "rem .243 that is modes 0-10, VGA and Mode X up to 360x480: its Cirrus BIOS",
            "rem is VBE 1.2 and Quake's VESA modes need VBE 2.0.",
        ]
    else:
        run += " +vid_mode %d" % mode
        head += [
            "rem Mode %d = 360x480, the sharpest of the built-in VGA and Mode X modes," % mode,
            "rem about 2.7 times the pixels of 320x200. Quake's modes 0-10 are the same",
            "rem on every VGA card, and .243's Cirrus offers Quake no VESA mode at all.",
        ]
    head += [
        "rem -nojoy: with a gameport stick fitted Quake stops at CENTER the joystick.",
        "rem -nocdaudio: with no MSCDEX Quake stops at MSCDEX not loaded, press a key.",
        "rem -winmem 16: in a DOS box Quake takes an 8 MB heap unless it is told.",
        "rem Why DOS and not WinQuake: WINQUAKE.EXE stopped at MGL Fatal Error on",
        "rem .243's Cirrus 5436 with every -nowindirect and -nodirectdraw combination.",
        "if not exist QUAKE.EXE goto notree",
        run,
        "rem CLS: Windows 9x closes a DOS box on exit only when its screen is empty,",
        "rem and Quake prints its end text on the way out - measured on .243.",
        "cls",
        "goto end",
        ":notree",
        "echo QUAKE.EXE is missing - the Quake tree is incomplete.",
        "pause",
        ":end",
    ]
    return "\n".join(head) + "\n"


# The two official mission packs, data only, unzipped from the share's TOSEC
# zips (research C, recipe 3.1): Scourge of Armagon (Hipnotic) and Dissolution
# of Eternity (Rogue). GLQuake 0.97 and QUAKE.EXE 1.08 both carry -hipnotic and
# -rogue; Rogue's zip ships a QUAKE.EXE byte-identical to the library's 1.08.
# Neither pack ships an autoexec.cfg, so ID1's (which execs fleetkey.cfg) runs.
Q1_PACKS = (
    # (switch, folder, short name, Win9x Voodoo bat, Win9x DOS bat)
    ("hipnotic", "HIPNOTIC", "Scourge of Armagon", "Q1HIPV.BAT", "Q1HIPD.BAT"),
    ("rogue", "ROGUE", "Dissolution of Eternity", "Q1ROGV.BAT", "Q1ROGD.BAT"),
)
Q1_PACK_SOURCES = {
    "HIPNOTIC/PAK0.PAK": {
        "zip": "Files/Games/DOS/More Dos Games/Quake Mission Pack 1 Scourge of Armagon "
               "(1997)(Hipnotic Interactive).zip",
        "member": "pak0.pak", "md5": "0ab83681aaf841c4320269e02941a14a"},
    "ROGUE/PAK0.PAK": {
        "zip": "Files/Games/DOS/More Dos Games/Quake Mission Pack 2 Dissolution of Eternity "
               "(1997)(Rogue Entertainment).zip",
        "member": "rogue/pak0.pak", "md5": "c38a4e04219c317cd1b02f386bdfe11f"},
    # Rogue's own icon (32x32, 8 bpp BMP - Win98 draws it). Hipnotic ships none;
    # its shortcuts wear the Quake icon.
    "QROGUE.ICO": {
        "zip": "Files/Games/DOS/More Dos Games/Quake Mission Pack 2 Dissolution of Eternity "
               "(1997)(Rogue Entertainment).zip",
        "member": "icon.ico", "md5": "6fcc4d5491eb6ce40a81d6cdcda74c28"},
}


def q1pack_voodoo(switch, folder, name):
    return "\n".join([
        "@echo off",
        "rem Quake mission pack %s - 3dfx Voodoo 640x480x16, GLQuake over the" % name,
        "rem 3dfx MiniGL in VOODOO with -%s. Generated by retro-agent" % switch,
        "rem scripts/fleet/stage-win9x.py - fix it there. The pack is %s\\PAK0.PAK" % folder,
        "rem beside ID1. COMMAND.COM dialect; shown only on Win9x boxes with Glide -",
        "rem requires.json - and it checks for Glide itself for agents older than 1.84.0.",
        "if not exist VOODOO\\GLQUAKE.EXE goto notree",
        "if not exist %s\\PAK0.PAK goto notree" % folder,
        "if exist %windir%\\SYSTEM32\\GLIDE2X.DLL goto glide",
        "if exist %windir%\\SYSTEM\\GLIDE2X.DLL goto glide",
        "echo.",
        "echo  No 3dfx Glide driver is installed on this machine.",
        "echo.",
        "pause",
        "goto end",
        ":glide",
        "start /w VOODOO\\GLQUAKE.EXE -%s -width 640 -height 480 -bpp 16" % switch,
        "rem Repaint a desktop the Glide game left unpainted.",
        "if exist VOODOO\\DESKFIX9.EXE VOODOO\\DESKFIX9.EXE",
        "goto end",
        ":notree",
        "echo The %s files are missing - the Quake tree is incomplete." % name,
        "pause",
        ":end",
    ]) + "\n"


def q1pack_dos(switch, folder, name):
    return "\n".join([
        "@echo off",
        "rem Quake mission pack %s - the DOS build, QUAKE.EXE 1.08 -%s, in a" % (name, switch),
        "rem Windows 9x DOS box. Generated by retro-agent scripts/fleet/stage-win9x.py.",
        "rem The same switches as Q1DOS.BAT - -nojoy, -nocdaudio, -winmem 16 - for the",
        "rem same measured reasons; the pack is %s\\PAK0.PAK beside ID1." % folder,
        "if not exist QUAKE.EXE goto notree",
        "if not exist %s\\PAK0.PAK goto notree" % folder,
        "QUAKE.EXE -%s -nojoy -nocdaudio -winmem 16" % switch,
        "rem CLS: a Windows 9x DOS box closes on exit only when its screen is empty.",
        "cls",
        "goto end",
        ":notree",
        "echo The %s files are missing - the Quake tree is incomplete." % name,
        "pause",
        ":end",
    ]) + "\n"


def q1pack_bats():
    out = {}
    for switch, folder, name, vbat, dbat in Q1_PACKS:
        out[vbat] = q1pack_voodoo(switch, folder, name)
        out[dbat] = q1pack_dos(switch, folder, name)
    return out


def q1pack_rows():
    rows = []
    for switch, folder, name, vbat, dbat in Q1_PACKS:
        icon9x = "QROGUE.ICO" if switch == "rogue" else "VOODOO\\GLQUAKE.EXE"
        icon_nt = "QROGUE.ICO" if switch == "rogue" else "GLQUAKE.EXE"
        rows += [("Play Quake - %s.bat" % name, "Quake - %s" % name, icon_nt),
                 (vbat, "Quake - %s - 3dfx Voodoo" % name, icon9x),
                 (dbat, "Quake - %s - DOS" % name, icon9x)]
    return rows


def q1pack_rules():
    rules = {}
    for switch, folder, name, vbat, dbat in Q1_PACKS:
        # the NT launcher is stage-fleetres.py's GLQuake template with -<pack>:
        # the same rule as Play Quake.bat
        rules["Play Quake - %s.bat" % name] = {"gpu_feature_level": "fixed",
                                               "min_vram_mb": 4, "min_os": "win2k"}
        rules[vbat] = {"requires_capabilities": ["glide"], "max_os": "win9x"}
        rules[dbat] = {"max_os": "win9x"}
    return rules


QUAKE1 = {
    "copies": dict(Q1_PACK_SOURCES),
    "bats": dict({
        "Q1V640.BAT": Q1V640,
        "Q1V800.BAT": Q1V800,
        "Q1DOS.BAT": q1dos(),
        "Q1DOSM10.BAT": q1dos(10),
    }, **q1pack_bats()),
    "launch": {
        # line 0 stays "Play Quake.bat": stage-fleetres.py pins it
        # (launch_txt_line0) and a disagreement would be a fight.
        "rows": [
            ("Play Quake.bat", "Quake", "GLQUAKE.EXE"),
            ("Play Quake - Software.bat", "Quake - Software Renderer", "WINQUAKE.EXE"),
            ("Q1V640.BAT", "Quake - 3dfx Voodoo", "VOODOO\\GLQUAKE.EXE"),
            ("Q1V800.BAT", "Quake - 3dfx Voodoo 800x600", "VOODOO\\GLQUAKE.EXE"),
            ("Q1DOS.BAT", "Quake - DOS", "GLQUAKE.EXE"),
            ("Q1DOSM10.BAT", "Quake - DOS 360x480", "GLQUAKE.EXE"),
        ] + q1pack_rows(),
        "drop": ["Play Quake - Voodoo.bat", "Play Quake - DOS.bat"],
        "note": [
            "#",
            "# WINDOWS 9X LAUNCHERS ARE 8.3 AND GENERATED (2026-10-01): Q1V640.BAT,",
            "# Q1V800.BAT, Q1DOS.BAT and Q1DOSM10.BAT come from",
            "# scripts/fleet/stage-win9x.py. The Win98 shell stores a target's 8.3",
            "# alias in its PIF, and a long name's alias depends on file order.",
            "# 'Play Quake - Voodoo.bat' and 'Play Quake - DOS.bat' are superseded.",
        ],
    },
    "requires": {
        "version": 5,
        "set_top": {"disk_mb": 200},     # + the two mission packs, 73 MB
        "set": dict({
            "Play Quake.bat": {"gpu_feature_level": "fixed", "min_vram_mb": 4,
                               "min_os": "win2k"},
            "Play Quake - Software.bat": {"min_os": "win2k"},
            "Q1V640.BAT": {"requires_capabilities": ["glide"]},
            "Q1V800.BAT": {"requires_capabilities": ["glide"], "max_os": "win9x"},
            "Q1DOS.BAT": {"max_os": "win9x"},
            "Q1DOSM10.BAT": {"max_os": "win9x"},
        }, **q1pack_rules()),
        "drop": ["Play Quake - Voodoo.bat", "Play Quake - DOS.bat"],
        "notes": (
            "WIN9X LANE REGENERATED 2026-10-01 (scripts/fleet/stage-win9x.py): "
            "Q1V640.BAT is the old Voodoo launcher (640x480x16, every Voodoo; "
            "it redirects a Voodoo 4/5 NT box to Play Quake.bat); Q1V800.BAT is "
            "a Voodoo 2's 800x600x16 and is Win9x-only so a V5 box does not get "
            "a third icon; Q1DOS.BAT and Q1DOSM10.BAT run QUAKE.EXE -nojoy "
            "-nocdaudio -winmem 16 in a DOS box, the second at vid_mode 10 "
            "(360x480). 8.3 names because the Win98 shell stores a target's "
            "8.3 alias in its PIF."),
    },
}

# ==========================================================================
# Descent II (1996) - Descent2: the DOS game in a Windows 9x DOS box
# ==========================================================================
# The Descent 1 pattern ('Play Descent - DOS.bat', measured on .243): every
# other Descent II launcher is refused on a Pentium 166 - DXX-Rebirth needs
# CMOV, the DOSBox lane ~350 MHz of host CPU - and the DOS binary is native to
# it. The payload it runs - the no-CD DESCENT2.EXE, D2's own HMI drivers,
# DESCENT.CFG and DESCENT.SB5 - is staged by stage-fleetres.py's Descent2
# recipe, which owns the DOSBox lane that shares it.

D2DOS = r"""@echo off
rem Descent II - the 1996 DOS game, v1.2 with Vertigo, natively in a Windows 9x
rem DOS box. Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.
rem For a Win9x box - .243, a Pentium 166 with a Sound Blaster 16 - where every
rem other Descent II launcher is refused: DXX-Rebirth needs CMOV and the DOSBox
rem lane about 350 MHz of host CPU. DESCENT2.EXE is the no-CD build from the
rem share's DOS collection - the retail one stops at Sorry, the Descent 2 CD
rem must be present to run. COMMAND.COM dialect, an 8.3 name, and the desktop
rem shortcut starts in this folder.
rem
rem SOUND: DESCENT.CFG is the DOSBox lane's Sound Blaster 16 at IRQ 7, with the
rem HMI driver ids 0xe016 and 0xe018 out of D2's own SETUP.EXE. A real SB16 at
rem IRQ 5 handed IRQ 7 plays no digital sound, so DESCENT.SB5 - the same file at
rem IRQ 5 - is copied over only while DESCENT.CFG still says IRQ 7, exactly as
rem Descent 1's DOS launcher does: what the game saves on exit is kept.
rem -noredbook: no CD audio - there is no disc, and no MSCDEX in a DOS box.
if not exist DESCENT2.EXE goto notree
find "DigiIrq=7" DESCENT.CFG > nul
if not errorlevel 1 copy DESCENT.SB5 DESCENT.CFG > nul
DESCENT2.EXE -noredbook
rem CLS LAST: Windows 9x closes a DOS box on exit only when its screen is
rem empty, and Descent prints on its way out - measured on .243 with Descent 1.
cls
goto end
:notree
echo DESCENT2.EXE is missing - the Descent II tree is incomplete.
pause
:end
"""

DESCENT2 = {
    "bats": {"D2DOS.BAT": D2DOS},
    "launch": {
        "rows": [("D2DOS.BAT", "Descent II - DOS", "DESCENTW.EXE")],
    },
    "requires": {
        # no "version": stage-fleetres.py's Descent2 recipe owns that number,
        # and two generators setting it would fight
        "set": {
            "D2DOS.BAT": {
                "max_os": "win9x",
                "notes": ("The 1996 DOS game, the no-CD DESCENT2.EXE, native in a "
                          "Windows 9x DOS box - the one Descent II a Pentium 1 can "
                          "run. max_os win9x: an NT box has no DOS box that runs it. "
                          "The title floor - 66 MHz, 8 MB, the game's own - applies."),
            },
        },
    },
}

# ==========================================================================
# Win9x 3dfx Voodoo launchers for library titles (research R1 priority 1)
# ==========================================================================
# Shared shape - the proven one: Quake2Win9x's, Hexen II's and UT436's Voodoo
# launchers on .243. COMMAND.COM dialect; check for Glide (agents older than
# 1.84.0 ignore requires.json's glide rule); `start /w` so the batch waits;
# DESKFIX9.EXE afterwards, because a fullscreen Glide game can leave the 2D
# desktop unpainted, which looks exactly like a hung machine.

DESKFIX9 = {"lib": "Quake2Win9x/DESKFIX9.EXE", "md5": "7b71bd5bc0a322072d214778243d9059"}
GLIDE_RULE = {"requires_capabilities": ["glide"], "max_os": "win9x"}
NT_ONLY = {"min_os": "win2k"}


def voodoo_bat(title, check, body, header, missing=None):
    """A Win9x Voodoo launcher: header REM lines, the tree check, the Glide
    check, `body` (the lines that run the game), DESKFIX9, CLS-free end."""
    lines = ["@echo off",
             "rem %s - 3dfx Voodoo launcher for a Windows 9x box." % title,
             "rem Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.",
             "rem COMMAND.COM dialect - no percent-tilde paths, no cd /d, no start with a",
             "rem window title, no blocks. The desktop shortcut starts in this folder."]
    lines += ["rem " + h if h else "rem" for h in header]
    lines += [
        "rem Agents older than 1.84.0 ignore the glide rule in requires.json, so this",
        "rem launcher checks for Glide itself rather than failing in the game.",
        "if not exist %s goto notree" % check,
        "if exist %windir%\\SYSTEM32\\GLIDE2X.DLL goto glide",
        "if exist %windir%\\SYSTEM\\GLIDE2X.DLL goto glide",
        "echo.",
        "echo  No 3dfx Glide driver is installed on this machine.",
        "echo  This shortcut is for a 3dfx Voodoo 1 or 2 card.",
        "echo.",
        "pause",
        "goto end",
        ":glide"]
    lines += body
    lines += [
        "rem A fullscreen Glide game can leave the 2D desktop unpainted when it exits,",
        "rem which looks exactly like a hung machine. Repaint it.",
        "if exist DESKFIX9.EXE DESKFIX9.EXE",
        "rem Windows 9x closes the DOS box on exit only when its screen is empty.",
        "cls",
        "goto end",
        ":notree",
        "echo %s is missing - the %s tree is incomplete." % (check, missing or title),
        "pause",
        ":end"]
    return "\n".join(lines) + "\n"


def q2cfg_lines(path, extra=()):
    """echo lines writing an id Tech 2 fleetres.cfg - no space before >>, so no
    trailing blank on the line. The mod's autoexec.cfg execs this file LAST."""
    sets = [("vid_ref", "gl"), ("gl_driver", "3dfxgl"), ("gl_mode", "3")] + list(extra) \
        + [("vid_fullscreen", "1")]
    out = ["echo // written by the Win9x Voodoo launcher at every start>%s" % path]
    out += ['echo set %s "%s">>%s' % (k, v, path) for k, v in sets]
    return out


# ---- SiN (1998) + Wages of SiN: id Tech 2 over the 3dfx MiniGL ----------------
# R1, MEASURED: SiNGold\3dfxgl.dll is a 3dfx MiniGL whose 52 glide2x imports are
# all exported by the Voodoo 2 kit; sin.exe 1.11, ref_gl.dll and all three
# gamex86.dll have no MMX and no CMOV and resolve against Win98 SE. The game's
# own floor is a Pentium 166 - exactly .243 - so the settings are SiN's own
# low-end preset (base\vm_hw_low.cfg) minus its vid_restart / snd_restart and
# its 512x384 (not a mode a Voodoo-and-Cirrus box offers), with 8-bit textures
# (readme111: 16-bit costs a Voodoo 2 frames).
SIN_LOW = [("con_vidmode", "3"), ("sw_mode", "3"), ("con_texmode", "1"),
           ("gl_picmip", "1"), ("gl_shadows", "0"), ("cl_glows", "0"),
           ("cl_lights", "0"), ("cl_particles", "0"), ("cl_tessellation", "0"),
           ("cl_detailmodel", "0"), ("gl_polyblend", "0"), ("gl_flashblend", "0")]
SIN_HEADER = [
    "",
    "3DFXGL.DLL beside sin.exe is the 3dfx MiniGL - 52 glide2x imports, every",
    "one exported by the Voodoo 2 kit's GLIDE2X.DLL. The early +set values reach",
    "the FIRST renderer load: SiN's default is vid_ref soft, in this tree a copy",
    "of ref_gl, with gl_driver opengl32 - Microsoft's software GL. The mod's",
    "autoexec.cfg then sets opengl32 and mode 6 and execs fleetres.cfg LAST, so",
    "this launcher rewrites that file at every start: the MiniGL, 640x480 - gl_mode",
    "3, the mode every Voodoo scans out - and SiN's own low-end preset with 8-bit",
    "textures, for a Pentium 166, the game's published floor. 11 kHz sound too.",
    "GAMERES also writes fleetres.cfg at a sync - this launcher wins at launch.",
    ""]


def sin_bat(game, moddir, gameset):
    run = ("start /w sin.exe %s+set vid_ref gl +set gl_driver 3dfxgl +set gl_mode 3 "
           "+set vid_fullscreen 1 +set s_khz 11" % gameset)
    return voodoo_bat(game, "sin.exe", q2cfg_lines(moddir + "\\fleetres.cfg", SIN_LOW) + [run],
                      SIN_HEADER, missing="SiN")


SINGOLD = {
    "copies": {"DESKFIX9.EXE": DESKFIX9},
    "bats": {
        "Play SiN - Voodoo.bat": sin_bat("SiN", "base", ""),
        "Play Wages of SiN - Voodoo.bat": sin_bat("SiN - Wages of SiN", "2015",
                                                  "+set game 2015 "),
    },
    "launch": {"rows": [
        ("Play SiN - Voodoo.bat", "SiN - 3dfx Voodoo", "sin.exe"),
        ("Play Wages of SiN - Voodoo.bat", "SiN - Wages of SiN - 3dfx Voodoo", "2015\\wos.ico"),
    ]},
    "requires": {
        "version": 3,
        "set": {"Play SiN - Voodoo.bat": GLIDE_RULE,
                "Play Wages of SiN - Voodoo.bat": GLIDE_RULE},
        "patch": {n: NT_ONLY for n in ("Play SiN Gold.bat", "Play Wages of SiN.bat",
                                       "Play SiN - software renderer.bat")},
        "notes": (
            "WIN9X VOODOO LANE 2026-10-01 (scripts/fleet/stage-win9x.py, research R1): "
            "Play SiN - Voodoo.bat and Play Wages of SiN - Voodoo.bat run sin.exe over "
            "the 3dfx MiniGL beside it (glide capability, max_os win9x): base\\ or "
            "2015\\fleetres.cfg is rewritten at every start with the MiniGL, gl_mode 3 "
            "and SiN's own low-end preset, and the same renderer is set early on the "
            "command line so the first renderer load is the Voodoo. The three cmd.exe "
            "launchers are min_os win2k. The CPU floor stays 200 MHz (marginal for a "
            "P166, the game's own published minimum) - .243 runs it by override."),
    },
}


# ---- Half-Life (WON 1.1.0.8) + TFC + DMC over the 3Dfx Mini Driver -------------
# R1, MEASURED: gldrv\drvmap.txt names "gldrv/3dfxgl.dll 3Dfx Mini Driver" but
# the file was NOT in the tree; CounterStrike16\gldrv\3dfxgl.dll is that MiniGL
# (52 glide2x imports, all in the Voodoo 2 kit). hl.exe hands -gldrv's value
# to hw.dll VERBATIM and hw.dll LoadLibrary()s it, so the name must resolve from
# the game folder: the readme's documented value is "3dfxgl.dll" - also what
# hl.exe writes itself when it finds glide2x - so a copy sits in the root as
# well as in gldrv\ (the in-game driver list). hw.dll, the GL engine, has no
# MMX and no CMOV. Opposing Force and Blue Shift are broken in this tree
# (KNOWN-BROKEN-bshift-and-gearbox.txt) and get no Voodoo launcher.
HL_MINIGL = {"lib": "CounterStrike16/gldrv/3dfxgl.dll", "md5": "d3d7c67f2004431488d03b801804c601"}
HL_REG = r"""REGEDIT4

; Half-Life on a 3dfx Voodoo 1 or 2 under Windows 9x - merged by the Voodoo
; launchers before the game starts. Generated by retro-agent
; scripts/fleet/stage-win9x.py - fix it there.
;
; A Voodoo renders 16 bits per pixel only, and install.reg pins 1024x768x32
; for the NT boxes - a mode no Voodoo 1 or 2 scans out, and more than the 1 MB
; Cirrus beside .243's Voodoo 2 can set for the 2D side. hl.exe has -24bpp and
; -32bpp switches and no 16-bit one, so the depth goes in the registry, which
; is where the WON engine keeps it - and the mode with it, 640x480, so the
; registry agrees with the launcher's -w 640 -h 480 whichever one wins.

[HKEY_CURRENT_USER\Software\Valve\Half-Life\Settings]
"ScreenWidth"=dword:00000280
"ScreenHeight"=dword:000001e0
"ScreenBPP"=dword:00000010
"EngineModeW"=dword:00000280
"EngineModeH"=dword:000001e0
"EngineModeBPP"=dword:00000010
"""
HL_HEADER = [
    "",
    "GoldSrc over the 3Dfx Mini Driver, 3DFXGL.DLL - 52 glide2x imports, all in",
    "the Voodoo 2 kit. -gldrv 3dfxgl.dll is the value Valve's readme names and",
    "the one hl.exe writes itself when it finds glide2x. hl.exe hands it to the",
    "engine, which loads it by name from this folder. install.reg keeps",
    "EngineGLDriver at Default for the NT boxes - -gldrv does not rewrite it.",
    "HLV9X.REG first sets the engine's mode to 640x480 at 16 bits: no Voodoo 1",
    "or 2 has a 32-bit mode, and 640x480 is the mode every Voodoo scans out.",
    "-toconsole gets past the WON launcher dialog to the console - one ESC.",
    ""]


def hl_bat(game, gamearg):
    run = ("start /w hl.exe -nosierra -full -gl -gldrv 3dfxgl.dll -w 640 -h 480 "
           "-toconsole%s" % gamearg)
    return voodoo_bat(game, "hl.exe",
                      ["if exist HLV9X.REG start /w regedit /s HLV9X.REG", run],
                      HL_HEADER, missing="Half-Life")


HALFLIFE1 = {
    "copies": {"DESKFIX9.EXE": DESKFIX9, "3dfxgl.dll": HL_MINIGL,
               "gldrv/3dfxgl.dll": HL_MINIGL},
    "files": {"HLV9X.REG": HL_REG},
    "bats": {
        "Play Half-Life - Voodoo.bat": hl_bat("Half-Life", ""),
        "Play Team Fortress Classic - Voodoo.bat": hl_bat("Team Fortress Classic", " -game tfc"),
        "Play Deathmatch Classic - Voodoo.bat": hl_bat("Deathmatch Classic", " -game dmc"),
    },
    "launch": {"rows": [
        ("Play Half-Life - Voodoo.bat", "Half-Life - 3dfx Voodoo", "valve.ico"),
        ("Play Team Fortress Classic - Voodoo.bat", "Team Fortress Classic - 3dfx Voodoo",
         "TeamFortressClassic.ico"),
        ("Play Deathmatch Classic - Voodoo.bat", "Deathmatch Classic - 3dfx Voodoo",
         "dmc\\dmc.ico"),
    ]},
    "requires": {
        "version": 4,
        "set": {"Play Half-Life - Voodoo.bat": GLIDE_RULE,
                "Play Team Fortress Classic - Voodoo.bat": GLIDE_RULE,
                "Play Deathmatch Classic - Voodoo.bat": GLIDE_RULE},
        "patch": {n: NT_ONLY for n in ("Half-Life.bat", "Opposing Force.bat", "Blue Shift.bat",
                                       "Team Fortress Classic.bat", "Deathmatch Classic.bat")},
        "notes": (
            "WIN9X VOODOO LANE 2026-10-01 (scripts/fleet/stage-win9x.py, research R1): "
            "Half-Life, Team Fortress Classic and Deathmatch Classic each get a "
            "COMMAND.COM Voodoo launcher (glide capability, max_os win9x) running "
            "hl.exe -gl -gldrv 3dfxgl.dll at 640x480 after HLV9X.REG sets 16 bpp; the "
            "3Dfx Mini Driver drvmap.txt always named is now staged (gldrv\\3dfxgl.dll, "
            "and 3dfxgl.dll in the root, the name -gldrv loads). The five cmd.exe "
            "launchers are min_os win2k."),
    },
}


# ---- Quake II mission packs on Quake2Complete --------------------------------
# The base game on Win9x is Quake2Win9x; the packs live in Quake2Complete, whose
# own launchers are cmd.exe. These are Quake2Win9x's proven Voodoo launcher with
# +set game: <pack>\fleetres.cfg (exec'd LAST by <pack>\autoexec.cfg) selects
# ref_gl over 3dfxgl.dll - the same MiniGL, byte for byte - at gl_mode 3.
# quake2.exe here is the 3.20 exe with its mode table patched (entry 9 =
# 1920x1080); entry 3 is still 640x480, and the code is the stock exe's.
def q2pack_bat(pack, moddir):
    return voodoo_bat(
        "Quake II - %s" % pack, "quake2.exe",
        q2cfg_lines(moddir + "\\fleetres.cfg") + ["start /w quake2.exe +set game %s" % moddir],
        ["",
         "The mission pack is the mod directory %s, selected with +set game. The" % moddir,
         "renderer goes in %s\\fleetres.cfg, which %s\\autoexec.cfg execs LAST - the" % (moddir, moddir),
         "mechanism of Quake2Win9x's Voodoo launcher, proven on .243: ref_gl over",
         "3dfxgl.dll, the 3dfx MiniGL beside quake2.exe, at 640x480 - gl_mode 3,",
         "the mode every Voodoo scans out. GAMERES also writes that file at a sync",
         "- this launcher wins at launch.",
         ""], missing="Quake II")


QUAKE2COMPLETE = {
    "copies": {"DESKFIX9.EXE": DESKFIX9},
    "bats": {
        "Play Quake II - The Reckoning - Voodoo.bat": q2pack_bat("The Reckoning", "xatrix"),
        "Play Quake II - Ground Zero - Voodoo.bat": q2pack_bat("Ground Zero", "rogue"),
    },
    "launch": {"rows": [
        ("Play Quake II - The Reckoning - Voodoo.bat", "Quake II - The Reckoning - 3dfx Voodoo",
         "xatrix\\q2.ico"),
        ("Play Quake II - Ground Zero - Voodoo.bat", "Quake II - Ground Zero - 3dfx Voodoo",
         "Q2.ico"),
    ]},
    "requires": {
        "version": 3,
        # the title-level min_os win2k would refuse the whole tree on Win9x;
        # every cmd.exe launcher carries it itself now
        "drop_top": ["min_os"],
        "set": {"Play Quake II - The Reckoning - Voodoo.bat": GLIDE_RULE,
                "Play Quake II - Ground Zero - Voodoo.bat": GLIDE_RULE},
        "patch": {n: NT_ONLY for n in ("Quake II.bat", "Quake II - The Reckoning.bat",
                                       "Quake II - Ground Zero.bat",
                                       "Quake II - ThreeWave CTF.bat")},
        "notes": (
            "WIN9X VOODOO LANE 2026-10-01 (scripts/fleet/stage-win9x.py, research R1): "
            "the title-level min_os win2k moved onto the four cmd.exe launchers, so a "
            "Win9x box with Glide gets the mission packs through two COMMAND.COM "
            "Voodoo launchers - Quake2Win9x's proven mechanism with +set game xatrix / "
            "rogue. The base game on Win9x stays Quake2Win9x."),
    },
}


# ---- Unreal Gold (226): UE1 GlideDrv ------------------------------------------
# R1, MEASURED: System\GlideDrv.dll's 54 glide2x imports are all in the Voodoo
# 2 kit; Unreal.exe, Core, Engine, Window, WinDrv, GlideDrv, Render and Galaxy
# resolve on Win98 SE. The game-local nGlide glide2x.dll ships INERT now
# (stage-fleetres.py, "GAME-LOCAL WRAPPERS SHIP UNDER INERT NAMES") - it
# imports d3d9.dll and could never load on Win98 anyway - so the real system
# Glide loads with no file moved. UT436's Voodoo launcher is the model: its own
# ini, -INI= with the dash (UE1 takes a bare word as a map or a server) - with
# one change: the library ships the ini as a TEMPLATE, System\Voodoo.tpl, and
# the launcher copies it to Voodoo.ini at every start. UE1 writes its system
# ini back on exit, and a game that fails to start a render device saves the
# fallback - SoftDrv - into it. A library-shipped Voodoo.ini would be edited on
# the box (GAMESYNC then recopies it, and the icons are rebuilt), and a fallback
# would stick for every later launch; a fresh copy each time has neither.
UNREAL_VOODOO = [
    ("Engine.Engine", "GameRenderDevice", "GlideDrv.GlideRenderDevice"),
    # a Voodoo 1/2 cannot render windowed: when Unreal's splash takes the focus
    # the viewport falls back to WindowedRenderDevice - SoftDrv strands the game
    # on the software rasterizer (scripts/voodoo2/fix_glide_games.py, .171)
    ("Engine.Engine", "WindowedRenderDevice", "GlideDrv.GlideRenderDevice"),
    ("Engine.Engine", "RenderDevice", "GlideDrv.GlideRenderDevice"),
    ("WinDrv.WindowsClient", "FullscreenViewportX", "640"),
    ("WinDrv.WindowsClient", "FullscreenViewportY", "480"),
    ("WinDrv.WindowsClient", "FullscreenColorBits", "16"),
    ("WinDrv.WindowsClient", "StartupFullscreen", "True"),
    ("GlideDrv.GlideRenderDevice", "HighDetailActors", "False"),
    ("GlideDrv.GlideRenderDevice", "DetailTextures", "False"),
    # Epic's own readme for a non-MMX P166: 11025 Hz
    ("Galaxy.GalaxyAudioSubsystem", "OutputRate", "11025Hz"),
]


def ini_set(text, edits):
    """`text` (an .ini) with each (section, key, value) set - replaced in place,
    or added at the end of its section when missing. Every other byte is kept;
    the line ending is the file's own."""
    nl = "\r\n" if "\r\n" in text else "\n"
    lines = text.replace("\r\n", "\n").split("\n")
    want = {}
    for sec, key, val in edits:
        want.setdefault(sec.lower(), {})[key.lower()] = (key, val)
    done = set()
    out, sec = [], None

    def flush(section):
        add = [(k, v) for kl, (k, v) in want.get(section, {}).items()
               if (section, kl) not in done]
        at = len(out)
        while at > 0 and not out[at - 1].strip():
            at -= 1
        out[at:at] = ["%s=%s" % (k, v) for k, v in add]
        done.update((section, k.lower()) for k, _ in add)

    for line in lines:
        st = line.strip()
        if st.startswith("[") and st.endswith("]"):
            if sec is not None:
                flush(sec)
            sec = st[1:-1].lower()
        elif sec in want and "=" in line and not st.startswith(";"):
            k = line.split("=", 1)[0].strip()
            if k.lower() in want[sec]:
                line = "%s=%s" % (k, want[sec][k.lower()][1])
                done.add((sec, k.lower()))
        out.append(line)
    if sec is not None:
        flush(sec)
    missing = [s for s in want if not any(d[0] == s for d in done)]
    if missing:
        raise SystemExit("ini_set: sections not in the ini: %s" % missing)
    return nl.join(out)


UNREALGOLD = {
    "copies": {"DESKFIX9.EXE": DESKFIX9},
    "derive": {"System/Voodoo.tpl": ("System/Unreal.ini",
                                     lambda t: ini_set(t, UNREAL_VOODOO))},
    # staged as Voodoo.ini for a few hours on 2026-10-01 before it became a
    # template; removed only while it holds exactly those bytes
    "remove": {"System/Voodoo.ini": "26b61ecc0a3fa74c486765acbc4dc402"},
    "bats": {
        "Play Unreal Gold - Voodoo.bat": voodoo_bat(
            "Unreal Gold", "System\\Unreal.exe", [
                "rem A game-local glide2x.dll left by an older library sync - nGlide -",
                "rem would shadow the real Glide. The library ships it under an inert",
                "rem name now, so one here is not a library file: remove it.",
                "if exist System\\GLIDE2X.DLL del System\\GLIDE2X.DLL",
                "cd System",
                "rem UE1 leaves Running.ini behind after a crash or a kill, and finding",
                "rem it raises the Recovery Mode dialog instead of the game.",
                "if exist Running.ini del Running.ini",
                "rem A fresh copy of the template at every start - see the header.",
                "copy /y Voodoo.tpl Voodoo.ini > nul",
                "start /w Unreal.exe -INI=Voodoo.ini",
                "cd .."],
            ["",
             "Unreal renders through GlideDrv on the Voodoo, not through a 2D chip.",
             "System\\Voodoo.tpl is Unreal.ini with GlideDrv as the game AND the",
             "windowed device - a Voodoo cannot render windowed, and SoftDrv there",
             "strands the game on the software rasterizer when the splash takes the",
             "focus - 640x480x16, lighter detail and 11 kHz sound: Epic's own advice",
             "for a non-MMX Pentium 166. It is copied to Voodoo.ini at every start:",
             "UE1 writes its ini back on exit, and after a failed start it saves the",
             "fallback device, SoftDrv, which would then stick. Settings changed in",
             "the game's menus last one session; keys and the player live in User.ini",
             "and are kept. -INI= leaves Unreal.ini to every other box; the DASH",
             "matters, UE1 takes a bare word as a map or a server.",
             ""], missing="Unreal Gold")},
    "launch": {"rows": [
        ("Play Unreal Gold - Voodoo.bat", "Unreal Gold - 3dfx Voodoo", "System\\Unreal.ico"),
    ]},
    "requires": {
        "version": 4,
        "set": {"Play Unreal Gold - Voodoo.bat": GLIDE_RULE},
        "patch": {n: NT_ONLY for n in ("Play Unreal Gold.bat", "Host Unreal Gold LAN.bat")},
        "notes": (
            "WIN9X VOODOO LANE 2026-10-01 (scripts/fleet/stage-win9x.py, research R1): "
            "Play Unreal Gold - Voodoo.bat runs Unreal.exe -INI=Voodoo.ini (GlideDrv, "
            "640x480x16, lighter detail, 11 kHz) for a Voodoo 1/2 box (glide, max_os "
            "win9x). The game-local nGlide glide2x.dll ships as glide2x.dll.nglide, so "
            "the real system Glide loads with no file moved on the box; the NT "
            "launcher's render-device block still restores it where there is no 3dfx "
            "card. The two cmd.exe launchers are min_os win2k. A non-MMX P166 is "
            "'slow rendering, large frame rate variations' by Epic's own readme - the "
            "period experience, as UT436 on .243."),
    },
}


# ---- Carmageddon II: the native 3Dfx build -------------------------------------
# R1, MEASURED: hardware_3dfx.bdd / 3dfx_win.bdd import 48 glide2x functions, all
# in the Voodoo 2 kit; CARMA2_HW.EXE has no live SafeDisc and no MMX; it and the
# game-local winmm.dll OGG proxy resolve on Win98 SE. Its game-local wrappers -
# nGlide (glide2x/glide3x/glide.dll) and IPXWrapper's Winsock stubs - ship
# INERT now (stage-fleetres.py); on Win98 nGlide cannot load (d3d9.dll) and the
# stubs abort the game on its first network call (ipxwrapper.dll imports
# kernel32!GetSystemWindowsDirectoryA). CARMA2_HW.EXE imports WSOCK32 itself,
# so a stub left by an older sync would be loaded - and is deleted.
CARMA2_BAT = voodoo_bat(
    "Carmageddon 2", "CARMA2_HW.EXE", [
        "rem Game-local wrappers left by an older library sync are not library",
        "rem files any more - the library ships them under inert names - and on",
        "rem Windows 9x they break the game: nGlide shadows the real Glide and",
        "rem cannot load, and IPXWrapper's Winsock stubs abort the game. Remove them.",
        "if exist GLIDE2X.DLL del GLIDE2X.DLL",
        "if exist GLIDE3X.DLL del GLIDE3X.DLL",
        "if exist GLIDE.DLL del GLIDE.DLL",
        "if exist WSOCK32.DLL del WSOCK32.DLL",
        "if exist MSWSOCK.DLL del MSWSOCK.DLL",
        "if exist DPWSOCKX.DLL del DPWSOCKX.DLL",
        "start /w CARMA2_HW.EXE"],
    ["",
     "CARMA2_HW.EXE is the native 3Dfx build - its BRender drivers talk to",
     "glide2x.dll - and install.reg already selects the Glide renderer. It runs",
     "directly, skipping the renderer chooser carma2.exe opens. With no game-local",
     "wrapper in the way the real Voodoo Glide loads. A Pentium 166 is the game's",
     "own published minimum.",
     ""], missing="Carmageddon 2")

CARMAGEDDON2 = {
    "copies": {"DESKFIX9.EXE": DESKFIX9},
    "bats": {"Play Carmageddon 2 - Voodoo.bat": CARMA2_BAT},
    "launch": {"rows": [
        ("Play Carmageddon 2 - Voodoo.bat", "Carmageddon 2 - 3dfx Voodoo", "carma2.exe"),
    ]},
    "requires": {
        "version": 3,
        # The title ships Carma2_SW.exe, so no floor at the title level: on a
        # Voodoo 1/2 box the ACTIVE adapter is the 2D chip (.243: level none)
        # and a title-level 'fixed' is a hard NO before anything else is read.
        "drop_top": ["gpu_feature_level", "min_vram_mb"],
        "set": {"Play Carmageddon 2 - Voodoo.bat": GLIDE_RULE},
        "patch": {"Play Carmageddon 2.bat": {"gpu_feature_level": "fixed",
                                             "min_vram_mb": 4, "min_os": "win2k"}},
        "notes": (
            "WIN9X VOODOO LANE 2026-10-01 (scripts/fleet/stage-win9x.py, research R1): "
            "the GPU floor moved from the title onto Play Carmageddon 2.bat - the title "
            "ships Carma2_SW.exe, and on a Voodoo 1/2 box the active adapter is the 2D "
            "chip, so a title-level 'fixed' refused the whole tree there. Play "
            "Carmageddon 2 - Voodoo.bat (glide, max_os win9x) runs CARMA2_HW.EXE on the "
            "real Glide: the game-local nGlide set and IPXWrapper stubs ship under "
            "inert names (.nglide, .ipxw) and the NT launcher puts them in place where "
            "they are wanted. LAN between Win9x and the IPXWrapper boxes is untested."),
    },
}

# ==========================================================================
# Wing Commander: Prophecy + Secret Ops (1997/98) - WCProphecy, NEW, Win9x-only
# ==========================================================================
# Research C recipe 3.2: GOG's 2.0.0.11 build, extracted on the host with
# innoextract (a Unicode Inno setup does not run on Win9x), PROPHECY\ and
# SECROPS\ (renamed: no space), GOG's nGlide set (glide*.dll, 3DfxSpl*.dll,
# nglide_*) and goggame.dll left out so the real Voodoo 2 Glide is used.
# The 2013 exes import only 1997-era KERNEL32/USER32/GDI32/DSOUND/DINPUT/WSOCK32
# (subsystem 4.0). Video Card Number 2 = gl_00002.dll = Glide 2. GOG runs disc-
# free from the WCPDISC*.IFF files beside prophecy.exe.

WCP_REG = r"""REGEDIT4

[HKEY_LOCAL_MACHINE\SOFTWARE\Origin Systems\Wing Commander Prophecy]
"Installed To:"=".\\"
"Installed From:"=".\\"
"Prophecy Installed"=hex:01
"Install Size:"=dword:00000002
"Video Card Description:"="3dfx Glide (2.60)"
"Video Card Number"=dword:00000002
"Video Card Major Version:"=dword:00000002
"Video Card Minor Version:"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Origin Systems\Wing Commander Secret Ops]
"Installed To:"=".\\"
"Installed From:"=".\\"
"Secret Ops Installed"=hex:01
"Install Size:"=dword:00000002
"Video Card Description:"="3dfx Glide (2.60)"
"Video Card Number"=dword:00000002
"Video Card Major Version:"=dword:00000002
"Video Card Minor Version:"=dword:00000000
"""

WCP_HEADER = [
    "Wing Commander Prophecy / Secret Ops - GOG 2.0.0.11, disc-free via WCPDISC*.IFF.",
    "Glide 2 renderer gl_00002.dll, selected by install.reg - Video Card Number 2.",
    "The game runs from its own folder, so the batch changes into it and back."]

WCPROPHECY = {
    "copies": {"DESKFIX9.EXE": DESKFIX9},
    "files": {"install.reg": WCP_REG},
    "bats": {
        "WCP.BAT": voodoo_bat("Wing Commander Prophecy", "PROPHECY\\PROPHECY.EXE",
                              ["cd PROPHECY", "start /w PROPHECY.EXE", "cd .."], WCP_HEADER),
        "WCSO.BAT": voodoo_bat("Wing Commander Secret Ops", "SECROPS\\SECRETOPS.EXE",
                               ["cd SECROPS", "start /w SECRETOPS.EXE", "cd .."], WCP_HEADER),
    },
    "launch": {"rows": [
        ("WCP.BAT", "Wing Commander Prophecy - 3dfx Voodoo", "WCPROPH.ICO"),
        ("WCSO.BAT", "Wing Commander Secret Ops - 3dfx Voodoo", "WCPROPH.ICO"),
    ]},
    "requires": {
        "version": 1,
        "set_top": {"min_cpu_mhz": 133, "min_ram_mb": 32, "disk_mb": 1800, "max_os": "win9x"},
        "set": {"WCP.BAT": GLIDE_RULE, "WCSO.BAT": GLIDE_RULE},
        "notes": ("README: P133 + 32 MB + a 4 MB 3Dfx card (Glide 2.43) accelerated, P166 "
                  "software. GOG build, disc-free via the local wcpdisc*.iff; GOG's nGlide "
                  "left out so the real Voodoo Glide renders (scripts/fleet/stage-win9x.py)."),
    },
}

# ==========================================================================

TITLES = {
    "Quake1": QUAKE1,
    "Descent2": DESCENT2,
    "SiNGold": SINGOLD,
    "HalfLife1": HALFLIFE1,
    "Quake2Complete": QUAKE2COMPLETE,
    "UnrealGold": UNREALGOLD,
    "Carmageddon2": CARMAGEDDON2,
    "WCProphecy": WCPROPHECY,
}

# Payload first, launchers next, rules after them, launch.txt LAST.
ORDER = ("copies", "files", "bats", "requires", "launch")


class Runner:
    def __init__(self, lib, check=False, dry=False, writer=None, via_smb=False,
                 log=print, titles=None):
        self.lib, self.check, self.dry = lib, check, dry
        self.log = log
        self.titles = titles if titles is not None else TITLES
        self.writer = writer or libwrite.writer_for(lib, via_smb=via_smb)
        self.changed, self.current, self.problems = [], 0, []

    # ---- reading the share ------------------------------------------------
    def _path(self, tdir, rel):
        """The existing file for `rel` (any case), else where to create it."""
        hit = libsource.find_ci_path(tdir, rel)
        if hit:
            return hit
        parent = os.path.dirname(rel.replace("\\", "/"))
        pdir = libsource.find_ci_path(tdir, parent) if parent else tdir
        if parent and pdir is None:
            pdir = os.path.join(tdir, *parent.split("/"))
        return os.path.join(pdir, os.path.basename(rel.replace("\\", "/")))

    @staticmethod
    def _read(path):
        try:
            with open(path, "rb") as fh:
                return fh.read()
        except FileNotFoundError:
            return None

    # ---- what the title should hold ----------------------------------------
    def desired(self, title, spec, tdir):
        """[(kind, rel, bytes)] in write order. Raises on a launcher that fails
        the COMMAND.COM check or a launch.txt that would lose a shortcut."""
        out = []
        for rel, src in sorted(spec.get("copies", {}).items()):
            out.append(("copies", rel, libsource.fetch(src)))
        for rel, text in sorted(spec.get("files", {}).items()):
            out.append(("files", rel, crlf(text).encode("latin-1")))
        # a file computed from another library file (Unreal Gold's Voodoo.ini
        # from its Unreal.ini): regenerated whenever its source changes
        for rel, (src_rel, fn) in sorted(spec.get("derive", {}).items()):
            src = libsource.find_ci_path(tdir, src_rel)
            if src is None:
                raise SystemExit("%s: %s is missing - cannot derive %s"
                                 % (title, src_rel, rel))
            with open(src, "rb") as fh:
                text = fh.read().decode("latin-1")
            out.append(("files", rel, fn(text).encode("latin-1")))
        for rel, text in sorted(spec.get("bats", {}).items()):
            data = crlf(text).encode("ascii")
            probs = libmeta.command_com_problems(data)
            if probs:
                raise SystemExit("%s/%s fails the COMMAND.COM check - refusing to "
                                 "ship it: %s" % (title, rel, "; ".join(probs)))
            out.append(("bats", rel, data))
        req = spec.get("requires")
        if req:
            cur = self._read(self._path(tdir, "requires.json"))
            text = libmeta.merge_requires(
                (cur or b"").decode("utf-8"), version=req.get("version"),
                set_shortcuts=req.get("set"), patch_shortcuts=req.get("patch"),
                drop_shortcuts=req.get("drop", ()), set_top=req.get("set_top"),
                drop_top=req.get("drop_top", ()), notes_add=req.get("notes"))
            out.append(("requires", "requires.json", text.encode("utf-8")))
        lt = spec.get("launch")
        if lt:
            cur = self._read(self._path(tdir, "launch.txt"))
            text = libmeta.set_launch_rows((cur or b"").decode("latin-1"),
                                           lt.get("rows", ()), lt.get("drop", ()),
                                           lt.get("note"))
            probs = libmeta.launch_problems(text)
            if probs:
                raise SystemExit("%s/launch.txt would lose a shortcut: %s"
                                 % (title, "; ".join(probs)))
            out.append(("launch", "launch.txt", text.encode("latin-1")))
        rank = {k: i for i, k in enumerate(ORDER)}
        out.sort(key=lambda t: rank[t[0]])
        return out

    def run(self):
        for title in sorted(self.titles):
            spec = self.titles[title]
            tdir = libsource.find_ci_path(self.lib, title)
            if tdir is None:
                # never create a title: retro-autodeploy answers a new title
                # directory with a fleet-wide GAMESYNC RESET + START
                self.problems.append("%s: not in the library" % title)
                continue
            for kind, rel, data in self.desired(title, spec, tdir):
                path = self._path(tdir, rel)
                if self._read(path) == data:
                    self.current += 1
                    continue
                what = "%s/%s" % (title, rel)
                if self.check:
                    self.problems.append("%s: not current" % what)
                    continue
                if not self.dry:
                    self.writer.write_bytes(path, data)
                self.changed.append(what)
            # LAST, after everything that replaces the file is in place. Only
            # the exact bytes this generator once shipped are ever removed.
            for rel, md5 in sorted(spec.get("remove", {}).items()):
                path = libsource.find_ci_path(tdir, rel)
                if path is None:
                    self.current += 1
                    continue
                what = "%s/%s" % (title, rel)
                have = libsource.md5(self._read(path))
                if have != md5:
                    self.problems.append("%s: not the file this generator shipped "
                                         "(md5 %s) - left alone" % (what, have))
                    continue
                if self.check:
                    self.problems.append("%s: should be removed" % what)
                    continue
                if not self.dry:
                    self.writer.remove(path)
                self.changed.append(what + " [removed]")
        return self


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lib", default=LIB_DEFAULT)
    ap.add_argument("--only", action="append", default=[], metavar="TITLE")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the share is not what this generator makes; writes nothing")
    ap.add_argument("--dry-run", action="store_true")
    libwrite.add_arguments(ap)
    a = ap.parse_args(argv)
    if not os.path.isdir(a.lib):
        print("library not mounted at %s" % a.lib, file=sys.stderr)
        return 2
    titles = TITLES
    if a.only:
        unknown = sorted(set(a.only) - set(TITLES))
        if unknown:
            print("--only names titles this generator does not own: %s" % unknown,
                  file=sys.stderr)
            return 2
        titles = {t: TITLES[t] for t in a.only}
    try:
        r = Runner(a.lib, a.check, a.dry_run, via_smb=a.via_smb, titles=titles)
    except libwrite.LibWriteError as e:
        print(str(e), file=sys.stderr)
        return 2
    try:
        with r.writer:
            r.run()
    except (libwrite.LibWriteError, libsource.SourceError) as e:
        for c in r.changed:
            print("staged %s" % c)
        print(libwrite.failure_banner(e, r.writer), file=sys.stderr)
        return 3
    for c in r.changed:
        print("%s %s" % ("would stage" if a.dry_run else "staged", c))
    for p in r.problems:
        print("FAIL %s" % p, file=sys.stderr)
    print("\n%d staged, %d already current, %d problem(s)"
          % (len(r.changed), r.current, len(r.problems)))
    return 1 if r.problems else 0


if __name__ == "__main__":
    sys.exit(main())
