#!/usr/bin/env python3
"""The Windows 9x lane of library titles that ALSO serve the NT fleet.

WHY THIS EXISTS. A staged title deploys to every box, and on Windows 98 SE
(.243 - a Pentium 166 with a Voodoo 2, a Cirrus GD5436 and an SB16; and the
W98BUILD VM shaped like it) the title's NT launchers cannot run: they are
cmd.exe dialect (%~dp0, cd /d, start "", if-blocks) and COMMAND.COM starts
none of them. Those boxes need launchers of their own - a Voodoo launcher that
renders through the 3dfx MiniGL or Glide, a DOS launcher that runs the game's
own DOS build in a DOS box - with requires.json rules that put each launcher
on the right boxes and keep the NT ones off Win9x.

Until now those launchers were hand-written on the share, with nothing in the
repo that could regenerate one, check one, or say what it should contain. This
generator owns them, the same way stage-fleetres.py owns the FLEETRES blocks:

  * each launcher's whole text (COMMAND.COM dialect, checked by
    libmeta.command_com_problems() before anything is written - a launcher that
    fails it stops the run, it is never shipped);
  * the binary payloads a launcher needs (md5-pinned, scripts/fleet/libsource.py);
  * its launch.txt rows and requires.json rules - MERGED, never templated
    (scripts/fleet/libmeta.py): other generators and people own the rest.

    python3 scripts/fleet/stage-win9x.py                 # apply
    python3 scripts/fleet/stage-win9x.py --check         # exit 1 if the share differs
    python3 scripts/fleet/stage-win9x.py --dry-run       # say what would change
    python3 scripts/fleet/stage-win9x.py --only Quake1   # one title

Writes go through scripts/fleet/libwrite.py: one file at a time, read back
through /mnt (md5 + a fresh write time) before the next, the first failure
stops the run. Identical bytes are never rewritten. It never creates a title,
never deletes a launcher (GAMESYNC never deletes either - a box keeps an old
launcher until someone removes it, so a superseded one is left for a person to
delete once its replacement is verified on hardware), and writes launch.txt
LAST so no box can sync a row that names a launcher not yet on the share.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import libmeta    # noqa: E402
import libsource  # noqa: E402
import libwrite   # noqa: E402

LIB_DEFAULT = "/mnt/retro-share/Files/Games-Library"


def crlf(text):
    return text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\r\n")


# ==========================================================================
# Quake (1996) - Quake1
# ==========================================================================
# Measured on .243 and in the Win98 build VM (2026-09-24 .. 10-01):
#   * GLQuake 0.97 (engine 1.09) over the 3dfx MiniGL in VOODOO\ runs at
#     640x480x16 (49.4 / 49.8 / 44.9 fps, demo1-3) and 800x600x16 (44.6 fps);
#     512x384 is REFUSED - "Specified video mode not available" - because the
#     Cirrus does not enumerate it. A Voodoo 2 has no 32-bit mode; a Voodoo 1
#     has no 800x600.
#   * DOS QUAKE.EXE 1.08 in a Win98 DOS box stops at "MSCDEX not loaded ...
#     press a key" without -nocdaudio and at "CENTER the joystick and press
#     button 1" with the gameport stick fitted, without -nojoy.
#     vid_describemodes lists modes 0-10 only (VGA 320x200 and Mode X up to
#     360x480): the Cirrus BIOS is VBE 1.2, and Quake's VESA modes need 2.0.
#   * WINQUAKE.EXE stops at "MGL Fatal Error!" there, so a Win9x box gets the
#     DOS build, not WinQuake.
#
# 8.3 NAMES. The Win98 shell stores the 8.3 alias of a shortcut's target in its
# PIF, and a long name's alias (PLAYQU~4.BAT) depends on the order the files
# were created in; the real-DOS menu (DOSGAME.TXT) reads 8.3 names too. The
# display names of the two icons .243 already has are unchanged, so their PIFs
# are rewritten in place rather than swept.

Q1V640 = r"""@echo off
rem Quake - 3dfx Voodoo, 640x480x16: GLQuake over the 3dfx MiniGL in VOODOO.
rem Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.
rem
rem RUNS UNDER BOTH SHELLS: Win98 COMMAND.COM and XP cmd.exe. So no
rem percent-tilde paths, no cd /d and no start with a window title - all
rem NT-only. The desktop shortcut starts in this folder, which is also where
rem Quake looks for ID1.
rem
rem VOODOO holds a copy of GLQUAKE.EXE beside the 3dfx MiniGL, named
rem OPENGL32.DLL - the Quake II 3.20 build, which has no P6 or MMX
rem instructions and so runs on a Pentium without MMX. Windows loads a DLL
rem from the exe's own folder first, so only THIS launcher uses the MiniGL.
rem The shared GLQUAKE.EXE keeps the system OpenGL on every other box.
rem
rem 640x480x16 is the mode EVERY Voodoo scans out: a Voodoo 1 has no 800x600
rem and no Voodoo 1 or 2 has a 32-bit mode. On .243's Voodoo 2 it ran 49.4,
rem 49.8 and 44.9 fps in demo1-3. The Voodoo 2's 800x600 is Q1V800.BAT -
rem measured working there too, so the old note that an 8 MB card cannot
rem hold it was wrong. A Voodoo 1 or 2 renders at its own mode whatever the
rem desktop is, so FLEETRES does not apply here.
rem
rem Agents older than 1.84.0 ignore the glide requirement in requires.json,
rem so this launcher checks for Glide itself rather than failing in the game.
if not exist VOODOO\GLQUAKE.EXE goto notree
rem
rem A VOODOO 4/5 - VSA-100, PCI 121A:0009 - IS NOT A VOODOO 1/2. This
rem MiniGL cannot drive one: on .124, a V5 6000, wglCreateContext fails
rem before the MiniGL ever calls grSstWinOpen, while the Glide 2 path under
rem it works - glide2probe, 2026-09-28. On that card the SYSTEM OpenGL
rem driver is itself Glide-backed, so the honest answer for this shortcut
rem there is Play Quake.bat: the same GLQuake, on the 3dfx card, at the fleet
rem resolution. Where another card drives the desktop, as on .143, that is
rem the other card. Detected on NT only - Win98 has no reg.exe and keeps
rem the MiniGL; the reg lines below are never reached there.
if not exist %windir%\system32\reg.exe goto novsa
rem Enum\PCI's subkeys are the WHOLE id (VEN_121A&DEV_0009&SUBSYS_...&REV_..),
rem so list them and match the prefix - a query of ...\PCI\VEN_121A&DEV_0009
rem finds no such key (the first version of this test, 2026-09-28).
reg query "HKLM\SYSTEM\CurrentControlSet\Enum\PCI" 2>nul | find /i "VEN_121A&DEV_0009" >nul
if errorlevel 1 goto novsa
echo This is a 3dfx Voodoo 4/5. The Voodoo 1/2 MiniGL cannot drive it, so
echo Quake runs through the system OpenGL driver instead.
call "Play Quake.bat"
goto end
:novsa
if exist %windir%\SYSTEM32\GLIDE2X.DLL goto glide
if exist %windir%\SYSTEM\GLIDE2X.DLL goto glide
echo.
echo  No 3dfx Glide driver is installed on this machine.
echo  This shortcut is for a 3dfx Voodoo card - use Play Quake instead.
echo.
pause
goto end
:glide
start /w VOODOO\GLQUAKE.EXE -width 640 -height 480 -bpp 16
rem A fullscreen Glide game can leave the 2D desktop unpainted when it exits,
rem which looks exactly like a hung machine. Repaint it.
if exist VOODOO\DESKFIX9.EXE VOODOO\DESKFIX9.EXE
goto end
:notree
echo VOODOO\GLQUAKE.EXE is missing - the Quake tree is incomplete.
pause
:end
"""

Q1V800 = r"""@echo off
rem Quake - 3dfx Voodoo 800x600x16, GLQuake over the 3dfx MiniGL in VOODOO.
rem Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.
rem A Voodoo 2's largest single-card mode - 44.6 fps on .243 against 46.5 at
rem 640x480, so the Pentium is the limit, not the card. A Voodoo 1 has no
rem 800x600, and 512x384 is refused on .243 because its Cirrus does not
rem enumerate that mode. COMMAND.COM dialect; shown only on Win9x boxes with
rem Glide - requires.json - and it checks for Glide itself for agents older
rem than 1.84.0.
if not exist VOODOO\GLQUAKE.EXE goto notree
if exist %windir%\SYSTEM32\GLIDE2X.DLL goto glide
if exist %windir%\SYSTEM\GLIDE2X.DLL goto glide
echo.
echo  No 3dfx Glide driver is installed on this machine.
echo.
pause
goto end
:glide
start /w VOODOO\GLQUAKE.EXE -width 800 -height 600 -bpp 16
rem Repaint a desktop the Glide game left unpainted.
if exist VOODOO\DESKFIX9.EXE VOODOO\DESKFIX9.EXE
goto end
:notree
echo VOODOO\GLQUAKE.EXE is missing - the Quake tree is incomplete.
pause
:end
"""


def q1dos(mode=None):
    run = "QUAKE.EXE -nojoy -nocdaudio -winmem 16"
    head = [
        "@echo off",
        "rem Quake - the DOS build, QUAKE.EXE 1.08, software rendering, in a Windows 9x",
        "rem DOS box. Generated by retro-agent scripts/fleet/stage-win9x.py - fix it there.",
        "rem COMMAND.COM dialect. The desktop shortcut starts in this folder and the",
        "rem DOS box goes full screen when Quake sets its video mode.",
    ]
    if mode is None:
        head += [
            "rem No mode is forced: mode 0, 320x200, or the one saved with D under",
            "rem Options, Video Options - which lists every mode this card offers. On",
            "rem .243 that is modes 0-10, VGA and Mode X up to 360x480: its Cirrus BIOS",
            "rem is VBE 1.2 and Quake's VESA modes need VBE 2.0.",
        ]
    else:
        run += " +vid_mode %d" % mode
        head += [
            "rem Mode %d = 360x480, the sharpest of the built-in VGA and Mode X modes," % mode,
            "rem about 2.7 times the pixels of 320x200. Quake's modes 0-10 are the same",
            "rem on every VGA card, and .243's Cirrus offers Quake no VESA mode at all.",
        ]
    head += [
        "rem -nojoy: with a gameport stick fitted Quake stops at CENTER the joystick.",
        "rem -nocdaudio: with no MSCDEX Quake stops at MSCDEX not loaded, press a key.",
        "rem -winmem 16: in a DOS box Quake takes an 8 MB heap unless it is told.",
        "rem Why DOS and not WinQuake: WINQUAKE.EXE stopped at MGL Fatal Error on",
        "rem .243's Cirrus 5436 with every -nowindirect and -nodirectdraw combination.",
        "if not exist QUAKE.EXE goto notree",
        run,
        "rem CLS: Windows 9x closes a DOS box on exit only when its screen is empty,",
        "rem and Quake prints its end text on the way out - measured on .243.",
        "cls",
        "goto end",
        ":notree",
        "echo QUAKE.EXE is missing - the Quake tree is incomplete.",
        "pause",
        ":end",
    ]
    return "\n".join(head) + "\n"


QUAKE1 = {
    "bats": {
        "Q1V640.BAT": Q1V640,
        "Q1V800.BAT": Q1V800,
        "Q1DOS.BAT": q1dos(),
        "Q1DOSM10.BAT": q1dos(10),
    },
    "launch": {
        # line 0 stays "Play Quake.bat": stage-fleetres.py pins it
        # (launch_txt_line0) and a disagreement would be a fight.
        "rows": [
            ("Play Quake.bat", "Quake", "GLQUAKE.EXE"),
            ("Play Quake - Software.bat", "Quake - Software Renderer", "WINQUAKE.EXE"),
            ("Q1V640.BAT", "Quake - 3dfx Voodoo", "VOODOO\\GLQUAKE.EXE"),
            ("Q1V800.BAT", "Quake - 3dfx Voodoo 800x600", "VOODOO\\GLQUAKE.EXE"),
            ("Q1DOS.BAT", "Quake - DOS", "GLQUAKE.EXE"),
            ("Q1DOSM10.BAT", "Quake - DOS 360x480", "GLQUAKE.EXE"),
        ],
        "drop": ["Play Quake - Voodoo.bat", "Play Quake - DOS.bat"],
        "note": [
            "#",
            "# WINDOWS 9X LAUNCHERS ARE 8.3 AND GENERATED (2026-10-01): Q1V640.BAT,",
            "# Q1V800.BAT, Q1DOS.BAT and Q1DOSM10.BAT come from",
            "# scripts/fleet/stage-win9x.py. The Win98 shell stores a target's 8.3",
            "# alias in its PIF, and a long name's alias depends on file order.",
            "# 'Play Quake - Voodoo.bat' and 'Play Quake - DOS.bat' are superseded.",
        ],
    },
    "requires": {
        "version": 4,
        "set": {
            "Play Quake.bat": {"gpu_feature_level": "fixed", "min_vram_mb": 4,
                               "min_os": "win2k"},
            "Play Quake - Software.bat": {"min_os": "win2k"},
            "Q1V640.BAT": {"requires_capabilities": ["glide"]},
            "Q1V800.BAT": {"requires_capabilities": ["glide"], "max_os": "win9x"},
            "Q1DOS.BAT": {"max_os": "win9x"},
            "Q1DOSM10.BAT": {"max_os": "win9x"},
        },
        "drop": ["Play Quake - Voodoo.bat", "Play Quake - DOS.bat"],
        "notes": (
            "WIN9X LANE REGENERATED 2026-10-01 (scripts/fleet/stage-win9x.py): "
            "Q1V640.BAT is the old Voodoo launcher (640x480x16, every Voodoo; "
            "it redirects a Voodoo 4/5 NT box to Play Quake.bat); Q1V800.BAT is "
            "a Voodoo 2's 800x600x16 and is Win9x-only so a V5 box does not get "
            "a third icon; Q1DOS.BAT and Q1DOSM10.BAT run QUAKE.EXE -nojoy "
            "-nocdaudio -winmem 16 in a DOS box, the second at vid_mode 10 "
            "(360x480). 8.3 names because the Win98 shell stores a target's "
            "8.3 alias in its PIF."),
    },
}

# ==========================================================================

TITLES = {
    "Quake1": QUAKE1,
}

# Payload first, launchers next, rules after them, launch.txt LAST.
ORDER = ("copies", "files", "bats", "requires", "launch")


class Runner:
    def __init__(self, lib, check=False, dry=False, writer=None, via_smb=False,
                 log=print, titles=None):
        self.lib, self.check, self.dry = lib, check, dry
        self.log = log
        self.titles = titles if titles is not None else TITLES
        self.writer = writer or libwrite.writer_for(lib, via_smb=via_smb)
        self.changed, self.current, self.problems = [], 0, []

    # ---- reading the share ------------------------------------------------
    def _path(self, tdir, rel):
        """The existing file for `rel` (any case), else where to create it."""
        hit = libsource.find_ci_path(tdir, rel)
        if hit:
            return hit
        parent = os.path.dirname(rel.replace("\\", "/"))
        pdir = libsource.find_ci_path(tdir, parent) if parent else tdir
        if parent and pdir is None:
            pdir = os.path.join(tdir, *parent.split("/"))
        return os.path.join(pdir, os.path.basename(rel.replace("\\", "/")))

    @staticmethod
    def _read(path):
        try:
            with open(path, "rb") as fh:
                return fh.read()
        except FileNotFoundError:
            return None

    # ---- what the title should hold ----------------------------------------
    def desired(self, title, spec, tdir):
        """[(kind, rel, bytes)] in write order. Raises on a launcher that fails
        the COMMAND.COM check or a launch.txt that would lose a shortcut."""
        out = []
        for rel, src in sorted(spec.get("copies", {}).items()):
            out.append(("copies", rel, libsource.fetch(src)))
        for rel, text in sorted(spec.get("files", {}).items()):
            out.append(("files", rel, crlf(text).encode("latin-1")))
        for rel, text in sorted(spec.get("bats", {}).items()):
            data = crlf(text).encode("ascii")
            probs = libmeta.command_com_problems(data)
            if probs:
                raise SystemExit("%s/%s fails the COMMAND.COM check - refusing to "
                                 "ship it: %s" % (title, rel, "; ".join(probs)))
            out.append(("bats", rel, data))
        req = spec.get("requires")
        if req:
            cur = self._read(self._path(tdir, "requires.json"))
            text = libmeta.merge_requires(
                (cur or b"").decode("utf-8"), version=req.get("version"),
                set_shortcuts=req.get("set"), patch_shortcuts=req.get("patch"),
                drop_shortcuts=req.get("drop", ()), set_top=req.get("set_top"),
                drop_top=req.get("drop_top", ()), notes_add=req.get("notes"))
            out.append(("requires", "requires.json", text.encode("utf-8")))
        lt = spec.get("launch")
        if lt:
            cur = self._read(self._path(tdir, "launch.txt"))
            text = libmeta.set_launch_rows((cur or b"").decode("latin-1"),
                                           lt.get("rows", ()), lt.get("drop", ()),
                                           lt.get("note"))
            probs = libmeta.launch_problems(text)
            if probs:
                raise SystemExit("%s/launch.txt would lose a shortcut: %s"
                                 % (title, "; ".join(probs)))
            out.append(("launch", "launch.txt", text.encode("latin-1")))
        rank = {k: i for i, k in enumerate(ORDER)}
        out.sort(key=lambda t: rank[t[0]])
        return out

    def run(self):
        for title in sorted(self.titles):
            spec = self.titles[title]
            tdir = libsource.find_ci_path(self.lib, title)
            if tdir is None:
                # never create a title: retro-autodeploy answers a new title
                # directory with a fleet-wide GAMESYNC RESET + START
                self.problems.append("%s: not in the library" % title)
                continue
            for kind, rel, data in self.desired(title, spec, tdir):
                path = self._path(tdir, rel)
                if self._read(path) == data:
                    self.current += 1
                    continue
                what = "%s/%s" % (title, rel)
                if self.check:
                    self.problems.append("%s: not current" % what)
                    continue
                if not self.dry:
                    self.writer.write_bytes(path, data)
                self.changed.append(what)
        return self


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lib", default=LIB_DEFAULT)
    ap.add_argument("--only", action="append", default=[], metavar="TITLE")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the share is not what this generator makes; writes nothing")
    ap.add_argument("--dry-run", action="store_true")
    libwrite.add_arguments(ap)
    a = ap.parse_args(argv)
    if not os.path.isdir(a.lib):
        print("library not mounted at %s" % a.lib, file=sys.stderr)
        return 2
    titles = TITLES
    if a.only:
        unknown = sorted(set(a.only) - set(TITLES))
        if unknown:
            print("--only names titles this generator does not own: %s" % unknown,
                  file=sys.stderr)
            return 2
        titles = {t: TITLES[t] for t in a.only}
    try:
        r = Runner(a.lib, a.check, a.dry_run, via_smb=a.via_smb, titles=titles)
    except libwrite.LibWriteError as e:
        print(str(e), file=sys.stderr)
        return 2
    try:
        with r.writer:
            r.run()
    except (libwrite.LibWriteError, libsource.SourceError) as e:
        for c in r.changed:
            print("staged %s" % c)
        print(libwrite.failure_banner(e, r.writer), file=sys.stderr)
        return 3
    for c in r.changed:
        print("%s %s" % ("would stage" if a.dry_run else "staged", c))
    for p in r.problems:
        print("FAIL %s" % p, file=sys.stderr)
    print("\n%d staged, %d already current, %d problem(s)"
          % (len(r.changed), r.current, len(r.problems)))
    return 1 if r.problems else 0


if __name__ == "__main__":
    sys.exit(main())
