#!/usr/bin/env python3
"""Stage the per-box resolution helper (FLEETRES) into the staged game library.

WHY THIS EXISTS. One staged tree deploys to eight machines with eight different
monitors — four 1920x1080 LCDs and four CRTs, two of which are 4:3 tubes being
driven at 5:4. A resolution written into a staged config is therefore wrong
somewhere **by construction**, and every title in the library was pinned at
1024x768 (Tiberian Sun at 640x480).

The fix has to stay INSIDE the staged tree, or it dies at the next re-image and
the next GAMESYNC overwrites it — that already happened once, to a hand-edited
baseq3\\autoexec.cfg on .123. So the fix is runtime: every title's launcher runs
FLEETRES.EXE, staged beside it, which reads THIS box's panel and writes the
game's own config (or command line) before the game starts.

    python3 scripts/fleet/stage-fleetres.py            # apply
    python3 scripts/fleet/stage-fleetres.py --dry-run  # show what would change
    python3 scripts/fleet/stage-fleetres.py --check    # exit 1 if not applied

It is idempotent: a launcher that already carries the block is left alone. Every
transformation asserts that it actually matched — a silent no-op here would
present as "the resolution fix does not work on that title", days later, on a
box, which is exactly the failure mode this repo keeps paying for.
"""

import argparse
import hashlib
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
PAYLOAD = os.path.join(os.path.dirname(HERE), "..", "provisioning", "fleetres")
PAYLOAD = os.path.normpath(PAYLOAD)
LIB_DEFAULT = "/mnt/retro-share/Files/Games-Library"

# What "already staged" means: the launcher actually CALLS the block. It was
# the bare filename "FLEETRES.BAT", and that is a false positive waiting to
# happen - a launcher whose COMMENTS merely mention FLEETRES.BAT (explaining
# where its resolution comes from, which is exactly what a good comment does)
# was reported "already current" and silently never patched. Far Cry hit this
# on the first run. Both CALL and call_cap() start with this prefix.
MARK = 'call "%~dp0FLEETRES.BAT"'   # the call, not the mention

# --------------------------------------------------------------------------
# The block, staged once per title as FLEETRES.BAT and CALLed by every launcher.
# One file per title rather than a paste into 35 launchers: when this is wrong
# it is wrong in one place.
# --------------------------------------------------------------------------
FLEETRES_BAT = """\
@echo off
rem ==========================================================================
rem  FLEET RESOLUTION BLOCK - identical in every staged title.
rem  Generated by retro-agent scripts/fleet/stage-fleetres.py. Do not hand-edit
rem  a copy: fix the generator and re-stage, or the next title you touch will
rem  disagree with this one.
rem
rem  ONE staged tree deploys to EIGHT monitors, so a resolution written into a
rem  staged config is wrong somewhere BY CONSTRUCTION. FLEETRES.EXE reads THIS
rem  box's panel - the EDID native mode plus the driver's own mode list - and
rem  answers with the FR_* variables below.
rem
rem  It deliberately does NOT trust two things that look authoritative:
rem    * wmic Win32_VideoController.CurrentHorizontalResolution, which reported
rem      640x480 on .123 while the box was really at 1024x768;
rem    * the LIVE desktop mode, because a game that exits without restoring
rem      leaves the desktop at 640x480 (.123 and .240 were both sitting there
rem      mid-survey) and a launcher trusting it would pin every later game to
rem      640x480 for good. The PERSISTED mode is what it reads.
rem
rem  Usage:  call "%~dp0FLEETRES.BAT"            (whole panel)
rem          call "%~dp0FLEETRES.BAT" -cap 1024 768   (engine ceiling)
rem
rem  FR_W    / FR_H    resolution for an engine that can do widescreen
rem  FR_W43  / FR_H43  resolution for an engine that is 4:3-only
rem  FR_Q2MODE         id Tech 2 gl_mode index matching FR_W43/FR_H43
rem  FR_Q3MODE         id Tech 3 r_mode index - a DIFFERENT TABLE: id Tech 2's
rem                    mode 8 is 1280x960 (4:3), id Tech 3's is 1280x1024 (5:4),
rem                    so handing FR_Q2MODE to a Quake III-family engine asks a
rem                    16:9 panel for a squashed picture
rem  FR_FOV            hor+ FOV preserving the 4:3 vertical FOV (90 at 4:3)
rem  FR_DOSFULLRES     DOSBox [sdl] fullresolution: desktop on an LCD,
rem                    original on a CRT
rem  FR_GLIDE          1 when this box has REAL 3dfx silicon (VEN_121A in the
rem                    PCI enum - a Voodoo 2 is Class=MEDIA and never shows up
rem                    as a display adapter, so nothing else can see it). The
rem                    launcher moves the game-local nGlide glide2x.dll aside
rem                    when this is 1, because game-local shadows system32 and
rem                    the wrapper then blocks the card it is standing in for.
rem  FR_UE1DEV         the UE1 render device to write into the game's .ini
rem ==========================================================================
set FR_W=
set FR_H=
set FR_W43=
set FR_H43=
set FR_FOV=
set FR_Q2MODE=
set FR_DOSFULLRES=
set FR_PANEL=
set FR_Q3MODE=
set FR_GLIDE=
set FR_UE1DEV=
if not defined TEMP set TEMP=%SystemRoot%\\Temp
if exist "%~dp0FLEETRES.EXE" "%~dp0FLEETRES.EXE" -cmd %1 %2 %3 > "%TEMP%\\fleetres.cmd"
if exist "%TEMP%\\fleetres.cmd" call "%TEMP%\\fleetres.cmd"
rem Fallbacks, for a box where FLEETRES.EXE is missing or the panel is unreadable.
rem 1024x768 is the fleet's lowest common denominator, not a preference.
if not defined FR_W set FR_W=1024
if not defined FR_H set FR_H=768
if not defined FR_W43 set FR_W43=1024
if not defined FR_H43 set FR_H43=768
if not defined FR_FOV set FR_FOV=90
if not defined FR_Q2MODE set FR_Q2MODE=6
if not defined FR_Q3MODE set FR_Q3MODE=6
if not defined FR_DOSFULLRES set FR_DOSFULLRES=original
rem FR_GLIDE defaults to 0 - "no 3dfx silicon" - deliberately. The wrong way
rem round would move the nGlide wrapper aside on a box that has nothing else,
rem costing six machines a working renderer to help two.
if not defined FR_GLIDE set FR_GLIDE=0
if not defined FR_UE1DEV set FR_UE1DEV=D3DDrv.D3DRenderDevice
"""


def idtech3_cfg(mod, wide=True):
    """The cfg the staged autoexec.cfg execs, written fresh at every launch.

    r_mode / r_customwidth / r_customheight / r_fullscreen are CVAR_LATCH: they
    bite only at renderer init. The staged autoexec.cfg used to `seta r_mode 6`
    there, which beat the command line on .123. That seta is now gone from the
    library and `exec fleetres.cfg` is the LAST line of autoexec.cfg instead, so
    whatever the box's own config wrote earlier is overridden in the same pass.
    """
    w, h = ("%FR_W%", "%FR_H%") if wide else ("%FR_W43%", "%FR_H43%")
    p = '"%%~dp0%s\\fleetres.cfg"' % mod
    lines = [
        '> %s echo // written by the launcher at every start - do not edit' % p,
        '>>%s echo seta r_mode "-1"' % p,
        '>>%s echo seta r_customwidth "%s"' % (p, w),
        '>>%s echo seta r_customheight "%s"' % (p, h),
        '>>%s echo seta r_customaspect "1"' % p,
        '>>%s echo seta r_customPixelAspect "1"' % p,
        '>>%s echo seta r_fullscreen "1"' % p,
    ]
    if wide:
        # id Tech 3 is vert-: at 16:9 with the default FOV you see LESS
        # vertically, not more horizontally. FR_FOV restores the 4:3 vertical
        # field of view (106 at 16:9, 90 at 4:3).
        lines.append('>>%s echo seta cg_fov "%%FR_FOV%%"' % p)
    return lines


def idtech3_modecfg(mod):
    """For an id Tech 3 fork with NO r_mode -1 BRANCH.

    `r_mode -1` + r_customwidth/r_customheight is the standard idiom and it is
    NOT universal: measured on .145 with an identical fleetres.cfg,
    quake3.exe/jasp.exe/jamp.exe all came up at 1920x1080 and **sof2mp.exe came
    up at 640x480**. It does not error - it renders small - which is exactly
    the silent class of defect this repo keeps paying for.

    So this fork gets a plain mode INDEX, and it must be FR_Q3MODE and not
    FR_Q2MODE: the two engines' tables differ at index 8, which is 1280x960
    (4:3) in id Tech 2 and 1280x1024 (5:4) in id Tech 3. Asking a 16:9 panel
    for 1280x1024 is the squashed picture this whole mechanism removes."""
    p = '"%%~dp0%s\\fleetres.cfg"' % mod
    return [
        '> %s echo // written by the launcher at every start - do not edit' % p,
        '>>%s echo // r_mode -1 DOES NOT EXIST IN THIS ENGINE - a plain index,' % p,
        '>>%s echo // and FR_Q3MODE not FR_Q2MODE: idTech3 mode 8 is 1280x1024.' % p,
        '>>%s echo seta r_mode "%%FR_Q3MODE%%"' % p,
        '>>%s echo seta r_fullscreen "1"' % p,
        '>>%s echo seta cg_fov "%%FR_FOV%%"' % p,
    ]


def idtech3_modeargs():
    return ('+set r_mode %FR_Q3MODE% +set r_fullscreen 1 +set cg_fov %FR_FOV%')


def idtech3_args(wide=True, fov=True):
    w, h = ("%FR_W%", "%FR_H%") if wide else ("%FR_W43%", "%FR_H43%")
    a = ("+set r_mode -1 +set r_customwidth {w} +set r_customheight {h} "
         "+set r_customaspect 1 +set r_customPixelAspect 1 "
         "+set r_fullscreen 1").format(w=w, h=h)
    if fov:
        a += " +set cg_fov %FR_FOV%"
    return a


def q2_cfg(mod):
    """id Tech 2 has a FIXED mode table indexed by gl_mode and no custom mode:
    0=320x240 ... 6=1024x768 ... 9=1600x1200, no 16:9 entry anywhere. So the
    honest best on a 16:9 panel is a correctly proportioned 4:3 mode, which is
    what FR_Q2MODE indexes."""
    p = '"%%~dp0%s\\fleetres.cfg"' % mod
    return [
        '> %s echo // written by the launcher at every start - do not edit' % p,
        '>>%s echo set gl_mode "%%FR_Q2MODE%%"' % p,
        '>>%s echo set vid_fullscreen "1"' % p,
    ]


def ue_ini(ini, section="WinDrv.WindowsClient"):
    """Unreal Engine 1/2 keeps the fullscreen mode in its .ini, and the engine
    rewrites that file on exit, so it has to be written before every launch."""
    e = '"%~dp0FLEETRES.EXE"'
    i = '"%%~dp0%s"' % ini
    return [
        'if exist "%~dp0FLEETRES.EXE" (',
        '  %s -ini %s %s FullscreenViewportX %%FR_W%%' % (e, i, section),
        '  %s -ini %s %s FullscreenViewportY %%FR_H%%' % (e, i, section),
        '  %s -ini %s %s StartupFullscreen True' % (e, i, section),
        ')',
    ]


def dosbox_conf(conf):
    """fullresolution=original changes the WHOLE DESKTOP to the DOS mode - on a
    16:9 LCD that is a stretched 640x480 upscale, and it is left behind after a
    crash (measured on .145 with DISPLAYCFG). =desktop keeps the desktop mode
    and lets DOSBox pillarbox correctly with aspect=true. On a CRT `original` is
    still right, which is why this is per-box and not a staged constant."""
    return ['if exist "%%~dp0FLEETRES.EXE" "%%~dp0FLEETRES.EXE" -ini '
            '"%%~dp0%s" sdl fullresolution %%FR_DOSFULLRES%%' % conf]


def kv_cfg(conf, pairs):
    """DXX-Rebirth writes DESCENT.CFG as bare `ResolutionX=1024` with NO
    [section] header, so WritePrivateProfileString cannot address it and
    -setline cannot match it (the whole "ResolutionX=1024" is one whitespace
    token). -kv splits at the '=' instead."""
    e = '"%~dp0FLEETRES.EXE"'
    out = ['if exist "%~dp0FLEETRES.EXE" (']
    for k, v in pairs:
        out.append('  %s -kv "%%~dp0%s" %s %s' % (e, conf, k, v))
    out.append(')')
    return out


def reg_cfg(root, subkey, values):
    r"""Some engines keep the mode ONLY in the registry - Max Payne through
    MFC's SetRegistryKey("Remedy Entertainment"), Red Faction under
    HKLM\SOFTWARE\Volition. Nothing that ships in the tree can set those, so
    a box inherits whatever stale hive it happens to have. FLEETRES -reg is
    used rather than reg.exe because reg.exe does not exist on Win9x."""
    e = '"%~dp0FLEETRES.EXE"'
    out = ['if exist "%~dp0FLEETRES.EXE" (']
    for name, typ, data in values:
        out.append('  %s -reg %s "%s" "%s" %s %s' % (e, root, subkey, name, typ, data))
    out.append(')')
    return out


def setline_cfg(conf, entries):
    e = '"%~dp0FLEETRES.EXE"'
    out = ['if exist "%~dp0FLEETRES.EXE" (']
    for key, line in entries:
        out.append('  %s -setline "%%~dp0%s" %s %s' % (e, conf, key, line))
    out.append(')')
    return out


# --------------------------------------------------------------------------
# The per-box RENDER DEVICE block. Structurally the same problem as the
# resolution: one staged tree, eight boxes, and a game-local nGlide
# glide2x.dll that is RIGHT on the six boxes with no Glide silicon and WRONG
# on the two that have it, because game-local wins at load time and shadows
# the real system32 glide2x.dll. On .171 that cost a whole session: UnrealGold
# was reported as crashing, had never crashed, and had spent the time on the
# software rasterizer at 100% CPU because the wrapper's grSstOpen failed (2,3).
#
# The wrapper is NOT deleted - it is the only Glide path the other six boxes
# have. It is moved aside per box, at launch, and moved back when the box has
# no 3dfx card. Both directions matter: a tree that only ever renames one way
# would strand the wrapper aside after the card came out.
# --------------------------------------------------------------------------
def glide_swap(rel):
    """rel = the game-local wrapper's path relative to the title root."""
    w = '%~dp0' + rel
    return [
        'rem ---- per-box RENDER DEVICE (see stage-fleetres.py) --------------',
        'if "%FR_GLIDE%"=="1" (',
        '  if exist "%s" move /y "%s" "%s.nglide" >nul' % (w, w, w),
        ') else (',
        '  if not exist "%s" if exist "%s.nglide" move /y "%s.nglide" "%s" >nul'
        % (w, w, w, w),
        ')',
    ]


# --------------------------------------------------------------------------
# Turok 2 keeps its mode as one BOOLEAN PER MODE in Data\config.ned, chosen
# from a fixed list: 320x240, 512x384, 640x480, 800x600, 1024x768, 1280x1024.
# There is no width/height pair and no 1080p entry, so the honest best is the
# largest 4:3 mode on that list the box can drive. 1280x1024 is deliberately
# NOT on the ladder: it is 5:4, and putting a 5:4 mode on a 4:3 or 16:9 panel
# squashes the picture - which is the same fault this whole mechanism exists
# to fix on .133 and .171.
#
# The `^` in the key is literal INSIDE double quotes; unquoted, cmd.exe eats it
# as its own escape character and the key silently becomes "320x240".
# --------------------------------------------------------------------------
T2_MODES = ["320^x^240", "512^x^384", "640^x^480", "800^x^600",
            "1024^x^768", "1280^x^1024"]
T2_LADDER = [(640, "640^x^480"), (800, "800^x^600"), (1024, "1024^x^768")]


def turok2_mode():
    e = '"%~dp0FLEETRES.EXE"'
    f = '"%~dp0Data\\config.ned"'
    k = 'Acclaim\\Turok\\VideoD3D\\'
    out = ['set T2SEL=640^x^480']
    for w, m in T2_LADDER[1:]:
        out.append('if %%FR_W43%% GEQ %d set T2SEL=%s' % (w, m))
    out.append('if exist "%~dp0FLEETRES.EXE" (')
    for m in T2_MODES:
        out.append('  %s -setline %s "%s%s" "%s%s" 0' % (e, f, k, m, k, m))
    out.append('  %s -setline %s "%s%%T2SEL%%" "%s%%T2SEL%%" 1' % (e, f, k, k))
    out.append('  %s -setline %s "%sWindowed" "%sWindowed" 0' % (e, f, k, k))
    out.append(')')
    return out


CALL = 'call "%~dp0FLEETRES.BAT"'
def call_cap(w, h):
    return 'call "%~dp0FLEETRES.BAT" -cap ' + str(w) + ' ' + str(h)


# --------------------------------------------------------------------------
# Per-title recipes.
#
#   before : a line that must exist in the .bat; the block is inserted above it
#   pre    : lines of the block
#   sub    : (regex, replacement) applied once to the launch line, and it MUST
#            match - an unmatched substitution aborts the whole run
# --------------------------------------------------------------------------
def rec(before, pre, sub=None):
    return {"before": before, "pre": pre, "sub": sub}


def q3(mod, exe, extra=""):
    args = idtech3_args()
    old = re.escape('start "" %s%s' % (exe, extra))
    return rec('cd /d "%~dp0"',
               [CALL] + idtech3_cfg(mod),
               (old, 'start "" %s%s %s' % (exe, extra, args)))


TITLES = {
    "Quake3-TeamArena": {
        "launchers": {
            "Play Quake III Arena.bat": q3("baseq3", "ioquake3.x86.exe"),
            "Play Team Arena.bat": q3("missionpack", "ioquake3.x86.exe",
                                      " +set fs_game missionpack"),
            "Play Quake III Arena - retail 1.32c.bat": q3("baseq3", "quake3.exe"),
        },
        "cfg_strip": ["baseq3/autoexec.cfg", "missionpack/autoexec.cfg"],
    },
    "SoldierOfFortune2": {
        # THE ONLY idTech3 TITLE HERE WITH NO r_mode -1 BRANCH. See
        # idtech3_modecfg(). Both binaries are the same engine, so both get the
        # index - the single-player launcher was still on -1 and was therefore
        # silently 640x480 too.
        "launchers": {
            "Play Soldier of Fortune II - Multiplayer.bat": rec(
                'cd /d "%~dp0"', [CALL] + idtech3_modecfg("base"),
                (re.escape('start "" "%~dp0sof2mp.exe"'),
                 'start "" "%%~dp0sof2mp.exe" %s' % idtech3_modeargs())),
            # NB the substitution target is `set "GAMEARGS="`, not the GAME=
            # line above it: this launcher CLEARS GAMEARGS after setting GAME,
            # so appending there is silently wiped one line later. Found by
            # reading the generated file rather than trusting the patch.
            "Play Soldier of Fortune II.bat": rec(
                'cd /d "%~dp0"', [CALL] + idtech3_modecfg("base"),
                (re.escape('set "GAMEARGS="'),
                 'set "GAMEARGS=%s"' % idtech3_modeargs())),
        },
        "fix": {
            # The MP launcher was moved off -1 by the library-qa sweep, but onto
            # FR_Q2MODE - the wrong table. The SP one was never moved at all.
            "Play Soldier of Fortune II - Multiplayer.bat": [
                ('r_mode "%FR_Q2MODE%"', 'r_mode "%FR_Q3MODE%"'),
                ('+set r_mode %FR_Q2MODE%', '+set r_mode %FR_Q3MODE%'),
            ],
            "Play Soldier of Fortune II.bat": [
                ('seta r_mode "-1"', 'seta r_mode "%FR_Q3MODE%"'),
                ('+set r_mode -1 +set r_customwidth %FR_W% '
                 '+set r_customheight %FR_H% +set r_customaspect 1 '
                 '+set r_customPixelAspect 1 +set r_fullscreen 1',
                 '+set r_mode %FR_Q3MODE% +set r_fullscreen 1'),
            ],
        },
        "cfg_strip": ["base/autoexec.cfg"],
    },
    "JediAcademy": {
        "new": {
            "Play Jedi Academy.bat": ("jasp.exe", "base"),
            "Play Jedi Academy - Multiplayer.bat": ("jamp.exe", "base"),
        },
        "launch_txt": [
            ("Play Jedi Academy.bat", "Jedi Academy", "jasp.exe"),
            ("Play Jedi Academy - Multiplayer.bat",
             "Jedi Academy - Multiplayer", "jamp.exe"),
        ],
        "cfg_strip": ["base/autoexec.cfg"],
    },
    "UnrealTournament": {
        "launchers": {
            "Play Unreal Tournament.bat": rec(
                'cd /d "%~dp0System"',
                [CALL] + ue_ini("System\\UnrealTournament.ini")),
        },
    },
    "UnrealTournament436": {
        "launchers": {
            "Play Unreal Tournament 436.bat": rec(
                'cd /d "%~dp0System"',
                [CALL] + ue_ini("System\\UnrealTournament.ini")),
            "Join fleet UT99 server - 436.bat": rec(
                'cd /d "%~dp0System"',
                [CALL] + ue_ini("System\\UnrealTournament.ini")),
        },
    },
    "UT2004": {
        "launchers": {
            "Play UT2004.bat": rec('cd /d "%~dp0System"',
                                   [CALL] + ue_ini("System\\UT2004.ini")),
            "Join fleet UT2004 server.bat": rec(
                'cd /d "%~dp0System"', [CALL] + ue_ini("System\\UT2004.ini")),
        },
    },
    "UnrealGold": {
        "launchers": {
            "Play Unreal Gold.bat": rec('cd /d "%~dp0System"',
                                        [CALL] + ue_ini("System\\Unreal.ini")),
        },
        # The render device is per-box for exactly the reason the resolution
        # is. The staged Unreal.ini asks for SoftDrv in a window and D3DDrv
        # fullscreen; FR_UE1DEV picks the right one for THIS box and the swap
        # stops the game-local nGlide wrapper shadowing real Glide silicon.
        "post": [{
            "file": "Play Unreal Gold.bat",
            "marker": "FR_GLIDE",
            "before": 'cd /d "%~dp0System"',
            "lines": glide_swap("System\\glide2x.dll") + [
                'if exist "%~dp0FLEETRES.EXE" (',
                '  "%~dp0FLEETRES.EXE" -ini "%~dp0System\\Unreal.ini" '
                'Engine.Engine GameRenderDevice %FR_UE1DEV%',
                '  "%~dp0FLEETRES.EXE" -ini "%~dp0System\\Unreal.ini" '
                'Engine.Engine WindowedRenderDevice %FR_UE1DEV%',
                '  "%~dp0FLEETRES.EXE" -ini "%~dp0System\\Unreal.ini" '
                'Engine.Engine RenderDevice %FR_UE1DEV%',
                ')',
            ],
        }],
    },
    "Carmageddon2": {
        # Carries the IDENTICAL 1,310,720-byte nGlide wrapper as UnrealGold and
        # was never tested on a box with Glide silicon. install.reg already
        # selects the Glide renderer (Driver=2), so on .143/.171 the game asks
        # for Glide and gets the wrapper instead of the card.
        "launchers": {
            "Play Carmageddon 2.bat": rec('cd /d "%~dp0"', [CALL]),
        },
        "post": [{
            "file": "Play Carmageddon 2.bat",
            "marker": "FR_GLIDE",
            "before": 'start "" CARMA2_HW.EXE',
            "lines": glide_swap("glide2x.dll"),
        }],
    },
    "HalfLife1": {
        # GoldSrc, same engine as the already-proven Counter-Strike launcher.
        # It is vert- at 16:9, so FR_FOV is not applicable here (WON HL has no
        # fov cvar worth setting from the command line) - the mode is.
        "launchers": {
            n: rec('cd /d "%~dp0"', [CALL],
                   (re.escape('-full -gl -w 1024 -h 768'),
                    '-full -gl -w %FR_W% -h %FR_H%'))
            for n in ("Half-Life.bat", "Opposing Force.bat", "Blue Shift.bat",
                      "Team Fortress Classic.bat", "Deathmatch Classic.bat")
        },
    },
    "HexenII": {
        # glh2.exe is a GLQuake derivative and was assumed to share GLQuake's
        # fixed 4:3 mode table. IT DOES NOT: measured on .145, glh2.exe comes up
        # fullscreen at a real 1920x1080 (window class HexenII, 0,0-1920x1080)
        # and renders the menu, while GLQUAKE.EXE on the SAME BOX refuses the
        # same mode with "Specified video mode not available". Two engines that
        # look like one family, two different answers - which is why each is
        # measured rather than inferred from the other.
        "launchers": {
            n: rec('cd /d "%~dp0"', [CALL],
                   (re.escape('-width 640 -height 480'),
                    '-width %FR_W% -height %FR_H%'))
            for n in ("Play Hexen II.bat", "Host Hexen II - LAN.bat",
                      "Join Hexen II - LAN.bat")
        },
        "fix": {
            n: [("-width %FR_W43% -height %FR_H43%", "-width %FR_W% -height %FR_H%")]
            for n in ("Play Hexen II.bat", "Host Hexen II - LAN.bat",
                      "Join Hexen II - LAN.bat")
        },
    },
    "HiddenAndDangerous": {
        # There is no fullscreen or resolution switch on this engine: HDE.exe
        # reads HKLM\Software\Lonely Cat Games\...\Config (root index 1 of its
        # {HKCU,HKLM,HKCR} table) and install.reg pins 800x600 there, which is a
        # staged constant and therefore wrong on seven of the eight boxes.
        "launchers": {
            n: rec('cd /d "%~dp0"',
                   [CALL] + reg_cfg(
                       "HKLM",
                       "Software\\Lonely Cat Games\\Hidden and Dangerous "
                       "Deluxe\\Config",
                       [("Display width", "dword", "%FR_W%"),
                        ("Display height", "dword", "%FR_H%"),
                        ("Display bitdepth", "dword", "32"),
                        ("Fullscreen", "dword", "1")]))
            for n in ("Play Hidden and Dangerous Deluxe.bat",
                      "Host Hidden and Dangerous - LAN.bat",
                      "Join Hidden and Dangerous - LAN.bat")
        },
    },
    "Turok2": {
        "launchers": {
            n: rec('cd /d "%~dp0"', [CALL] + turok2_mode())
            for n in ("Play Turok 2.bat", "Play Turok 2 - Multiplayer.bat",
                      "Join Turok 2 - LAN.bat")
        },
    },
    "RedAlert2": {
        # Two games, two .ini files, one tree. The aqrit ddraw wrapper this tree
        # ships is what lets the Westwood engine take a mode its own menu never
        # offers - the same shape as Tiberian Sun and CnCNet.
        "launchers": {
            "Launch Red Alert 2.bat": rec(
                'start /wait Ra2.exe -speedcontrol',
                [CALL,
                 'if exist "%~dp0FLEETRES.EXE" (',
                 '  "%~dp0FLEETRES.EXE" -ini "%~dp0RA2.INI" Video '
                 'ScreenWidth %FR_W%',
                 '  "%~dp0FLEETRES.EXE" -ini "%~dp0RA2.INI" Video '
                 'ScreenHeight %FR_H%',
                 ')']),
            "Launch Yuri's Revenge.bat": rec(
                'start /wait RA2MD.exe -speedcontrol',
                [CALL,
                 'if exist "%~dp0FLEETRES.EXE" (',
                 '  "%~dp0FLEETRES.EXE" -ini "%~dp0RA2MD.INI" Video '
                 'ScreenWidth %FR_W%',
                 '  "%~dp0FLEETRES.EXE" -ini "%~dp0RA2MD.INI" Video '
                 'ScreenHeight %FR_H%',
                 ')']),
        },
    },
    "BF1942": {
        # Refractor keeps the mode in Video.con as
        #   game.setGameDisplayMode <w> <h> <bpp> <refresh-index>
        # and reads the PROFILE copy, so both the Default and Custom profiles
        # are written - a box that has ever opened the video menu uses Custom.
        "launchers": {
            "Play Battlefield 1942.bat": rec(
                'cd /d "%~dp0"',
                [CALL]
                + setline_cfg("Mods\\bf1942\\Settings\\Profiles\\Default\\Video.con",
                              [("game.setGameDisplayMode",
                                "game.setGameDisplayMode %FR_W% %FR_H% 32 0")])
                + setline_cfg("Mods\\bf1942\\Settings\\Profiles\\Custom\\Video.con",
                              [("game.setGameDisplayMode",
                                "game.setGameDisplayMode %FR_W% %FR_H% 32 0")])),
            "Join Battlefield 1942 - LAN.bat": rec(
                'cd /d "%~dp0"',
                [CALL]
                + setline_cfg("Mods\\bf1942\\Settings\\Profiles\\Default\\Video.con",
                              [("game.setGameDisplayMode",
                                "game.setGameDisplayMode %FR_W% %FR_H% 32 0")])
                + setline_cfg("Mods\\bf1942\\Settings\\Profiles\\Custom\\Video.con",
                              [("game.setGameDisplayMode",
                                "game.setGameDisplayMode %FR_W% %FR_H% 32 0")])),
        },
    },
    "Descent2": {
        # DXX-Rebirth is genuinely widescreen. Its DESCENT.CFG is bare
        # key=value with no [section], which is why -kv exists.
        "launchers": {
            "Play Descent 2.bat": rec(
                'cd /d "%~dp0"',
                [CALL] + kv_cfg("DESCENT.CFG",
                                [("ResolutionX", "%FR_W%"),
                                 ("ResolutionY", "%FR_H%")])),
        },
    },
    "RedFaction": {
        # The mode is ONLY in HKLM\SOFTWARE\Volition\Red Faction - value
        # names read out of rf.exe. Nothing in the tree can set it.
        "launchers": {
            "Play Red Faction.bat": rec(
                'cd /d "%~dp0"',
                [CALL] + reg_cfg("HKLM", "SOFTWARE\\Volition\\Red Faction",
                                 [("Resolution Width", "dword", "%FR_W%"),
                                  ("Resolution Height", "dword", "%FR_H%"),
                                  ("Resolution Bit Depth", "dword", "32")])),
        },
    },
    "MaxPayne": {
        # install.reg pins 800x600 into HKCU because that is the only place the
        # engine reads. That is a staged constant and therefore wrong on seven
        # of the eight boxes; the launcher writes the box's own mode instead.
        "launchers": {
            "Play Max Payne.bat": rec(
                'cd /d "%~dp0"',
                [CALL] + reg_cfg(
                    "HKCU",
                    "Software\\Remedy Entertainment\\Max Payne\\Video Settings",
                    [("Display Width", "dword", "%FR_W%"),
                     ("Display Height", "dword", "%FR_H%")])),
        },
    },
    "Shogo": {
        # LithTech 1.0 keeps the mode in autoexec.cfg as  "screenwidth" "640".
        # The quotes are required by the format and cmd.exe eats real ones, so
        # FLEETRES turns a backtick into a double quote.
        "launchers": {
            "Play Shogo - direct engine.bat": rec(
                'cd /d "%~dp0"',
                [CALL] + setline_cfg("autoexec.cfg",
                                     [("screenwidth", "`screenwidth` `%FR_W%`"),
                                      ("screenheight", "`screenheight` `%FR_H%`")])),
        },
    },
    "DeusEx": {
        "launchers": {
            "Play Deus Ex.bat": rec('cd /d "%~dp0System"',
                                    [CALL] + ue_ini("SYSTEM\\DeusEx.ini")),
            "Host Deus Ex Multiplayer.bat": rec(
                'cd /d "%~dp0"', [CALL] + ue_ini("SYSTEM\\DeusEx.ini")),
        },
    },
    "CounterStrike16": {
        "launchers": {
            "Play Counter-Strike.bat": rec(
                'cd /d "%~dp0"', [CALL],
                (re.escape('start "" hl.exe -game cstrike -full'),
                 'start "" hl.exe -game cstrike -full -w %FR_W% -h %FR_H%')),
        },
    },
    "Thief2": {
        # NewDark is genuinely widescreen-aware (D3DX9_43.dll, NVScript.osm,
        # new_mantle in cam.cfg), so this one gets the full panel.
        "launchers": {
            "Play Thief 2.bat": rec(
                'cd /d "%~dp0"',
                [CALL,
                 'if exist "%~dp0FLEETRES.EXE" "%~dp0FLEETRES.EXE" -setline '
                 '"%~dp0cam.cfg" game_screen_size game_screen_size '
                 '%FR_W% %FR_H%']),
        },
    },
    "Descent3": {
        "launchers": {
            "Play Descent 3.bat": rec(
                'cd /d "%~dp0"', [CALL],
                (re.escape('start "" "%~dp0main.exe" -launched'),
                 'start "" "%~dp0main.exe" -launched -Width %FR_W% '
                 '-Height %FR_H%')),
        },
    },
    "Quake2Complete": {
        "launchers": {
            "Quake II.bat": rec(
                'cd /d "%~dp0"', [CALL] + q2_cfg("baseq2"),
                (re.escape('start "" quake2.exe') + r'(?!\s*\+set game)',
                 'start "" quake2.exe +set gl_mode %FR_Q2MODE%')),
            "Quake II - The Reckoning.bat": rec(
                'cd /d "%~dp0"', [CALL] + q2_cfg("xatrix"),
                (re.escape('start "" quake2.exe +set game xatrix'),
                 'start "" quake2.exe +set game xatrix +set gl_mode %FR_Q2MODE%')),
            "Quake II - Ground Zero.bat": rec(
                'cd /d "%~dp0"', [CALL] + q2_cfg("rogue"),
                (re.escape('start "" quake2.exe +set game rogue'),
                 'start "" quake2.exe +set game rogue +set gl_mode %FR_Q2MODE%')),
            "Quake II - ThreeWave CTF.bat": rec(
                'cd /d "%~dp0"', [CALL] + q2_cfg("ctf"),
                (re.escape('start "" quake2.exe +set game ctf'),
                 'start "" quake2.exe +set game ctf +set gl_mode %FR_Q2MODE%')),
        },
        "cfg_exec": ["baseq2/autoexec.cfg", "xatrix/autoexec.cfg",
                     "rogue/autoexec.cfg", "ctf/autoexec.cfg"],
    },
    "SiNGold": {
        "new": {"Play SiN Gold.bat": ("sin.exe", "base")},
        "launch_txt_line0": ("Play SiN Gold.bat", "SiN", "sin.exe"),
        # The mission pack is a SEPARATE mod directory with its own autoexec.cfg
        # and its own `set gl_mode "6"`, so covering base/ alone left half the
        # title pinned. ctf/ is only reached by the dedicated-server launcher,
        # but its autoexec is the same constant and costs nothing to fix.
        "cfg_exec": ["base/autoexec.cfg", "2015/autoexec.cfg", "ctf/autoexec.cfg"],
        "launchers": {
            "Play Wages of SiN.bat": rec(
                'cd /d "%~dp0"', [CALL] + q2_cfg("2015"),
                (re.escape('start "" sin.exe +set game 2015'),
                 'start "" sin.exe +set game 2015 +set gl_mode %FR_Q2MODE%')),
            # The SOFTWARE renderer indexes the same table with sw_mode. It
            # exists for a box with no usable 3D, and 1024x768 in software was
            # still a staged constant - wrong on .171, which is capped at
            # 800x600 by its Voodoo 2 and would be asked for more.
            "Play SiN - software renderer.bat": rec(
                'cd /d "%~dp0"', [CALL],
                (re.escape('+set sw_mode 6'), '+set sw_mode %FR_Q2MODE%')),
        },
    },
    "SoldierOfFortune": {
        "new": {"Play Soldier of Fortune.bat": ("SoF.exe", "base")},
        "launch_txt_line0": ("Play Soldier of Fortune.bat",
                             "Soldier of Fortune", "SoF.exe"),
        "cfg_exec": ["base/autoexec.cfg"],
    },
    "Quake1": {
        "new": {"Play Quake.bat": ("GLQUAKE.EXE", None)},
        "launch_txt_line0": ("Play Quake.bat", "Quake", "GLQUAKE.EXE"),
    },
    "TiberianSun": {
        # THE CAP IS GONE, AND THE REASON MATTERS. It was set at 1024x768 on the
        # argument that a Westwood 2D engine draws sprites 1:1 and they become
        # unreadable at 1920x1080. That is a taste judgement, and underneath it
        # was a factual assumption - that the engine could not go higher -
        # which is wrong: TS renders a real 1920x1080 (measured on .123, full
        # sidebar and a large map viewport). Its own Display Options list only
        # offers 640x400/640x480/800x600, but the CnCNet patch reads
        # [Video] ScreenWidth/ScreenHeight out of SUN.INI directly and bypasses
        # that list entirely. So A GAME'S OWN MODE MENU IS NOT EVIDENCE OF ITS
        # CEILING - which is exactly the inference that produced this cap.
        "fix": {
            "Play Tiberian Sun.bat": [
                ('call "%~dp0FLEETRES.BAT" -cap 1024 768',
                 'call "%~dp0FLEETRES.BAT"'),
                ("Video ScreenWidth %FR_W43%", "Video ScreenWidth %FR_W%"),
                ("Video ScreenHeight %FR_H43%", "Video ScreenHeight %FR_H%"),
            ],
        },
        "launchers": {
            "Play Tiberian Sun.bat": rec(
                'cd /d "%~dp0"',
                [CALL,
                 'if exist "%~dp0FLEETRES.EXE" (',
                 '  "%~dp0FLEETRES.EXE" -ini "%~dp0SUN.INI" Video '
                 'ScreenWidth %FR_W%',
                 '  "%~dp0FLEETRES.EXE" -ini "%~dp0SUN.INI" Video '
                 'ScreenHeight %FR_H%',
                 '  "%~dp0FLEETRES.EXE" -ini "%~dp0SUN.INI" Video '
                 'AllowHiResModes yes',
                 ')']),
        },
    },
    "Descent1": {
        "launchers": {
            "Play Descent.bat": rec('cd /d "%~dp0DOSBOX"',
                                    [CALL] + dosbox_conf("dosboxD1.conf")),
            "Host Descent - LAN.bat": rec('cd /d "%~dp0DOSBOX"',
                                          [CALL] + dosbox_conf("dosboxD1.conf")),
            "Join Descent - LAN.bat": rec('cd /d "%~dp0DOSBOX"',
                                          [CALL] + dosbox_conf("dosboxD1.conf")),
            "Descent Sound Setup.bat": rec('cd /d "%~dp0DOSBOX"',
                                           [CALL] + dosbox_conf("dosboxD1.conf")),
        },
    },
    "Carmageddon1": {
        "launchers": {
            "Play Carmageddon.bat": rec(
                'cd /d "%~dp0DOSBOX"', [CALL] + dosbox_conf("dosboxCarma.conf")),
            "Host Carmageddon - LAN.bat": rec(
                'cd /d "%~dp0DOSBOX"', [CALL] + dosbox_conf("dosboxCarma.conf")),
            "Join Carmageddon - LAN.bat": rec(
                'cd /d "%~dp0DOSBOX"', [CALL] + dosbox_conf("dosboxCarma.conf")),
            "Carmageddon Sound Setup.bat": rec(
                'cd /d "%~dp0DOSBOX"', [CALL] + dosbox_conf("dosboxCarma.conf")),
        },
    },
    "RedneckRampage": {
        "launchers": {
            n: rec('cd /d "%~dp0DOSBOX"', [CALL] + dosbox_conf("dosboxRR.conf"))
            for n in ("Play Redneck Rampage.bat",
                      "Play Redneck Rampage - Game.bat",
                      "Play Route 66.bat",
                      "Play Rides Again.bat",
                      "Host Redneck Rampage - LAN.bat",
                      "Join Redneck Rampage - LAN.bat",
                      "Redneck Rampage Setup.bat")
        },
    },
    # CryEngine 1. The engine reads System.cfg from the CURRENT directory and
    # REWRITES it on exit, so the launcher resets it from System-fleet.cfg
    # first and FLEETRES writes the mode into the fresh copy. Far Cry 1.4 is
    # natively 16:9, so it gets the whole panel (FR_W/FR_H), not the 4:3 subset.
    # The anchor is the start line, not the `cd /d`: the block MUST land after
    # the copy, or it would write the resolution into a file overwritten a line
    # later - the same shape of bug that wiped SoF2's GAMEARGS.
    "FarCry": {
        "launchers": {
            "Play Far Cry.bat": rec(
                'start "" "Bin32\\FarCry.exe" %*',
                [CALL,
                 'if exist "%~dp0FLEETRES.EXE" "%~dp0FLEETRES.EXE" -setline '
                 '"%~dp0System.cfg" r_Width r_Width = %FR_W%',
                 'if exist "%~dp0FLEETRES.EXE" "%~dp0FLEETRES.EXE" -setline '
                 '"%~dp0System.cfg" r_Height r_Height = %FR_H%']),
        },
    },
}

# --------------------------------------------------------------------------
# Whole-file templates for the launchers that do not exist yet
# --------------------------------------------------------------------------
NEW_IDTECH3 = """\
@echo off
rem {title} - fleet launcher.
rem
rem This .bat exists because launch.txt used to point straight at the exe, and
rem a desktop shortcut cannot carry arguments (gamesync.c never calls
rem SetArguments) - so there was nowhere to run FLEETRES and the game was pinned
rem to whatever resolution the staged config named, on every monitor.
cd /d "%~dp0"

{block}

start "" {exe} {args}

rem Close this console. A .bat that ends at "start" leaves its window open for
rem the life of the game; a dozen launches leaves a dozen of them stacked on the
rem desktop, and a screenshot then cannot tell "fullscreen game GDI cannot see"
rem from "the game never started".
exit
"""

NEW_Q2 = """\
@echo off
rem {title} - fleet launcher.
rem
rem This .bat exists because launch.txt used to point straight at the exe, and a
rem desktop shortcut cannot carry arguments - so there was nowhere to run
rem FLEETRES and the game was pinned to gl_mode 6 (1024x768) on every monitor.
rem
rem id Tech 2 has a FIXED mode table and no custom mode: 0=320x240 ... 6=1024x768
rem ... 9=1600x1200, with no 16:9 entry at all. A correctly proportioned 4:3 mode
rem is the honest best on a widescreen panel; stretching it is worse.
cd /d "%~dp0"

{block}

start "" {exe} +set gl_mode %FR_Q2MODE%

exit
"""

NEW_GLQUAKE = """\
@echo off
rem Quake - fleet launcher (GLQuake).
rem
rem This .bat exists because launch.txt used to point straight at GLQUAKE.EXE,
rem and a desktop shortcut cannot carry arguments - so there was nowhere to set
rem a resolution and every box got GLQuake's own 640x480 default.
rem
rem CAPPED AT 1280x960, AND THAT CEILING IS MEASURED, NOT ASSUMED. On .145
rem (GeForce 8400GS, 1920x1080 panel) GLQUAKE.EXE answers
rem     Quake Error: "Specified video mode not available"
rem at BOTH 1920x1080 and 1600x1200, and comes up fullscreen at 1280x960. Its
rem mode list is a fixed 4:3 table compiled into the binary, so there is no
rem 16:9 entry to ask for and no custom mode. 1280x960 pillarboxed on a 1080p
rem panel is the honest best this engine can do.
cd /d "%~dp0"

{block}

start "" GLQUAKE.EXE -width %FR_W43% -height %FR_H43% -bpp 32

exit
"""


def read(path):
    with open(path, "rb") as fh:
        return fh.read().decode("latin1")


def write(path, text):
    with open(path, "wb") as fh:
        fh.write(text.encode("latin1"))


def crlf(text):
    return text.replace("\r\n", "\n").replace("\n", "\r\n")


class Runner:
    def __init__(self, lib, dry, check):
        self.lib, self.dry, self.check = lib, dry, check
        self.changed, self.errors, self.skipped = [], [], 0

    def note(self, what):
        self.changed.append(what)

    def fail(self, what):
        self.errors.append(what)

    def put(self, path, text, what):
        """Write only if the content differs — and say so."""
        if os.path.isfile(path) and read(path) == text:
            self.skipped += 1
            return False
        if self.check:
            self.fail("%s: not staged" % what)
            return False
        if not self.dry:
            write(path, text)
        self.note(what)
        return True

    # ---- the per-title steps -------------------------------------------
    def payload(self, tdir, title):
        src = os.path.join(PAYLOAD, "FLEETRES.EXE")
        dst = os.path.join(tdir, "FLEETRES.EXE")
        want = open(src, "rb").read()
        if not os.path.isfile(dst) or open(dst, "rb").read() != want:
            if self.check:
                self.fail("%s: FLEETRES.EXE not staged" % title)
            else:
                if not self.dry:
                    shutil.copyfile(src, dst)
                self.note("%s/FLEETRES.EXE" % title)
        else:
            self.skipped += 1
        self.put(os.path.join(tdir, "FLEETRES.BAT"), crlf(FLEETRES_BAT),
                 "%s/FLEETRES.BAT" % title)

    def patch_launcher(self, tdir, title, name, r):
        path = os.path.join(tdir, name)
        if not os.path.isfile(path):
            self.fail("%s/%s: launcher missing from the library" % (title, name))
            return
        body = read(path)
        if MARK in body:
            self.skipped += 1
            return
        if self.check:
            self.fail("%s/%s: no FLEETRES block" % (title, name))
            return

        nl = "\r\n" if "\r\n" in body else "\n"
        flat = body.replace("\r\n", "\n")

        anchor = r["before"]
        if anchor not in flat:
            self.fail("%s/%s: anchor %r not found — the launcher changed "
                      "under us, so this recipe is stale" % (title, name, anchor))
            return
        block = "\n".join(r["pre"])
        flat = flat.replace(anchor, block + "\n\n" + anchor, 1)

        if r["sub"]:
            pat, repl = r["sub"]
            new, n = re.subn(pat, lambda m: repl, flat, count=1)
            if n != 1:
                self.fail("%s/%s: launch-line pattern matched %d times, not 1 "
                          "— refusing to ship a launcher that silently did not "
                          "get its resolution arguments" % (title, name, n))
                return
            flat = new

        out = flat.replace("\n", nl) if nl == "\r\n" else flat
        if not self.dry:
            write(path, out)
        self.note("%s/%s" % (title, name))

    def repair(self, tdir, title, name, pairs):
        """Change a launcher this tool has ALREADY staged.

        patch_launcher keys idempotency off the presence of `FLEETRES.BAT`, so
        once a launcher carries the block it is never touched again — which is
        right for re-runs and wrong the day a recipe changes. Every repair here
        is a literal old->new pair that must be in exactly one of two states:
        present (apply it) or already applied (skip). NEITHER is an error, not
        a silent no-op, because "the recipe no longer matches the library" is
        precisely the condition that ships a launcher which did not get its
        arguments."""
        path = os.path.join(tdir, name)
        if not os.path.isfile(path):
            self.fail("%s/%s: launcher missing from the library" % (title, name))
            return
        body = read(path)
        out = body
        did = []
        for old, new in pairs:
            if old in out:
                if self.check:
                    self.fail("%s/%s: still has %r" % (title, name, old))
                    return
                out = out.replace(old, new)
                did.append(old)
            elif new not in out:
                self.fail("%s/%s: neither %r nor its replacement is present — "
                          "this recipe is stale, and applying it blind would "
                          "ship a launcher that silently did not change"
                          % (title, name, old))
                return
        if not did:
            self.skipped += 1
            return
        if not self.dry:
            write(path, out)
        self.note("%s/%s [repair]" % (title, name))

    def post_block(self, tdir, title, pb):
        """A second, independently-marked block in a launcher that may ALREADY
        carry the FLEETRES block. patch_launcher keys idempotency off
        `FLEETRES.BAT`, so it skips a launcher it has already done - which would
        silently drop anything added later. This one keys off its own marker."""
        path = os.path.join(tdir, pb["file"])
        if not os.path.isfile(path):
            self.fail("%s/%s: launcher missing from the library"
                      % (title, pb["file"]))
            return
        body = read(path)
        if pb["marker"] in body:
            self.skipped += 1
            return
        if self.check:
            self.fail("%s/%s: no %s block" % (title, pb["file"], pb["marker"]))
            return
        nl = "\r\n" if "\r\n" in body else "\n"
        flat = body.replace("\r\n", "\n")
        if pb["before"] not in flat:
            self.fail("%s/%s: anchor %r not found - the launcher changed under "
                      "us, so this recipe is stale"
                      % (title, pb["file"], pb["before"]))
            return
        flat = flat.replace(pb["before"],
                            "\n".join(pb["lines"]) + "\n\n" + pb["before"], 1)
        out = flat.replace("\n", nl) if nl == "\r\n" else flat
        if not self.dry:
            write(path, out)
        self.note("%s/%s [%s]" % (title, pb["file"], pb["marker"]))

    def new_launcher(self, tdir, title, name, spec):
        exe, mod = spec
        path = os.path.join(tdir, name)
        disp = name[len("Play "):-len(".bat")] if name.startswith("Play ") else name
        if exe.upper() == "GLQUAKE.EXE":
            block = "\n".join([call_cap(1280, 960)])
            text = NEW_GLQUAKE.format(block=block)
        elif title in ("SiNGold", "SoldierOfFortune"):
            block = "\n".join([CALL] + q2_cfg(mod))
            text = NEW_Q2.format(title=disp, exe=exe, block=block)
        else:
            block = "\n".join([CALL] + idtech3_cfg(mod))
            text = NEW_IDTECH3.format(title=disp, exe=exe, block=block,
                                      args=idtech3_args())
        self.put(path, crlf(text), "%s/%s" % (title, name))

    def strip_latched(self, tdir, title, rel):
        """Delete the CVAR_LATCH resolution seta lines from a staged
        autoexec.cfg and exec fleetres.cfg instead.

        These two lines are the whole reason the command line did not take on
        .123: they run after Com_StartupVariable and before R_Init, so the
        renderer comes up on THEIR value. Removing them and supplying the mode
        from the launcher is the actual fix — but only once the launcher does
        supply it, which is why both halves are in this one script."""
        path = os.path.join(tdir, rel.replace("/", os.sep))
        if not os.path.isfile(path):
            self.fail("%s/%s: missing" % (title, rel))
            return
        body = read(path)
        out, dropped = [], 0
        for line in body.replace("\r\n", "\n").split("\n"):
            if re.match(r'\s*seta\s+r_(mode|fullscreen)\s', line):
                dropped += 1
                continue
            # the trailing comment lines that belonged to the r_mode line
            if dropped and re.match(r'\s{8,}//', line):
                continue
            out.append(line)
        text = "\n".join(out)
        text = self._append_exec(text)
        if dropped == 0 and "exec fleetres.cfg" in body:
            self.skipped += 1
            return
        if dropped == 0:
            self.fail("%s/%s: no 'seta r_mode'/'seta r_fullscreen' to remove "
                      "— check the file, do not assume it is already done"
                      % (title, rel))
            return
        self.put(path, crlf(text), "%s/%s" % (title, rel))

    def add_exec(self, tdir, title, rel):
        path = os.path.join(tdir, rel.replace("/", os.sep))
        if not os.path.isfile(path):
            self.fail("%s/%s: missing" % (title, rel))
            return
        body = read(path).replace("\r\n", "\n")
        if "exec fleetres.cfg" in body:
            self.skipped += 1
            return
        self.put(path, crlf(self._append_exec(body)), "%s/%s" % (title, rel))

    @staticmethod
    def _append_exec(text):
        if "exec fleetres.cfg" in text:
            return text
        tail = (
            "\n"
            "// ---- per-box resolution ---------------------------------------\n"
            "// fleetres.cfg is written by this title's Play ....bat at every\n"
            "// launch, from the panel FLEETRES.EXE measures on THIS machine.\n"
            "// It is exec'd LAST so it beats anything set above, and it is not\n"
            "// shipped in the library - one staged tree serves eight different\n"
            "// monitors, so a resolution constant here is wrong somewhere by\n"
            "// construction. If the file is absent the engine prints a harmless\n"
            "// 'couldn't exec' and keeps its own defaults.\n"
            "exec fleetres.cfg\n")
        return text.rstrip("\n") + "\n" + tail

    def launch_txt(self, tdir, title, rows=None, line0=None):
        path = os.path.join(tdir, "launch.txt")
        body = read(path)
        nl = "\r\n" if "\r\n" in body else "\n"
        lines = body.replace("\r\n", "\n").split("\n")
        if rows is not None:
            data = ["\t".join(r) for r in rows]
            rest = [l for l in lines if l.strip().startswith("#") or not l.strip()]
            new = nl.join(data + rest)
        else:
            done = False
            for i, l in enumerate(lines):
                if l.strip() and not l.strip().startswith("#"):
                    lines[i] = "\t".join(line0)
                    done = True
                    break
            if not done:
                self.fail("%s/launch.txt: no data line to rewrite" % title)
                return
            new = nl.join(lines)
        self.put(path, new, "%s/launch.txt" % title)

    def run(self):
        for title in sorted(TITLES):
            spec = TITLES[title]
            tdir = os.path.join(self.lib, title)
            if not os.path.isdir(tdir):
                self.fail("%s: not in the library" % title)
                continue
            self.payload(tdir, title)
            for name, r in sorted(spec.get("launchers", {}).items()):
                self.patch_launcher(tdir, title, name, r)
            for name, s in sorted(spec.get("new", {}).items()):
                self.new_launcher(tdir, title, name, s)
            for rel in spec.get("cfg_strip", []):
                self.strip_latched(tdir, title, rel)
            for rel in spec.get("cfg_exec", []):
                self.add_exec(tdir, title, rel)
            for pb in spec.get("post", []):
                self.post_block(tdir, title, pb)
            for name, pairs in sorted(spec.get("fix", {}).items()):
                self.repair(tdir, title, name, pairs)
            if "launch_txt" in spec:
                self.launch_txt(tdir, title, rows=spec["launch_txt"])
            if "launch_txt_line0" in spec:
                self.launch_txt(tdir, title, line0=spec["launch_txt_line0"])
        return self


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lib", default=LIB_DEFAULT)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--check", action="store_true",
                    help="report what is NOT staged and exit 1; changes nothing")
    a = ap.parse_args()

    if not os.path.isdir(a.lib):
        print("library not mounted at %s" % a.lib, file=sys.stderr)
        return 2

    r = Runner(a.lib, a.dry_run, a.check).run()
    for c in r.changed:
        print("%s %s" % ("would stage" if a.dry_run else "staged", c))
    for e in r.errors:
        print("FAIL %s" % e, file=sys.stderr)
    print("\n%d staged, %d already current, %d failures"
          % (len(r.changed), r.skipped, len(r.errors)))
    return 1 if r.errors else 0


if __name__ == "__main__":
    sys.exit(main())
