//=============================================================================
// GBSchema -- GENERATED by ../gen_gbschema.py from scripts/gamebots/schema.py.
//
// Do not edit by hand. Regenerate with:
//     python3 gen_gbschema.py > GameBots/Classes/GBSchema.uc
//
// Every value is a static function (`class'GBSchema'.static.Name()`), NOT a
// `const` -- see this generator's module docstring for why a bare cross-class
// const proved unreliable on this compiler and a function call did not.
//
// The schema hash goes out in every request; the policy server refuses a
// mismatch and names the fix. An adapter built against a stale copy of this
// file is otherwise undetectable -- the floats still unpack, they just mean
// something else.
//=============================================================================
class GBSchema extends Object;

static final function int SCHEMA_VERSION() { return 1; }
static final function int SCHEMA_HASH() { return 1183573531; }  // 0x468be61b, < 2^31 so it fits a signed int
static final function int OBS_DIM() { return 144; }
static final function int MAX_ENTITIES() { return 8; }
static final function int NUM_RAYS_H() { return 16; }
static final function int INTENT_DIM() { return 16; }

// wire sizes (bytes) -- see schema.py HEADER_STRUCT / OBS_ENTRY_STRUCT / ACTION_STRUCT
static final function int HEADER_SIZE() { return 16; }
static final function int OBS_ENTRY_SIZE() { return 580; }
static final function int ACTION_SIZE() { return 24; }

// magic, as bytes (UnrealScript has no byte-string literal)
static final function int REQ_MAGIC_0() { return 71; }  // 'G'
static final function int REQ_MAGIC_1() { return 66; }  // 'B'
static final function int REQ_MAGIC_2() { return 81; }  // 'Q'
static final function int REQ_MAGIC_3() { return 49; }  // '1'
static final function int RESP_MAGIC_0() { return 71; }  // 'G'
static final function int RESP_MAGIC_1() { return 66; }  // 'B'
static final function int RESP_MAGIC_2() { return 65; }  // 'A'
static final function int RESP_MAGIC_3() { return 49; }  // '1'

// --- buttons ---
static final function int BTN_ATTACK() { return 1; }
static final function int BTN_ATTACK2() { return 2; }
static final function int BTN_JUMP() { return 4; }
static final function int BTN_CROUCH() { return 8; }
static final function int BTN_RELOAD() { return 16; }
static final function int BTN_USE() { return 32; }
static final function int BTN_WALK() { return 64; }
static final function int BTN_ZOOM() { return 128; }

// --- request flags ---
static final function int FLAG_NONE() { return 0; }
static final function int FLAG_TRAINING() { return 1; }
static final function int FLAG_PAUSED() { return 2; }

// --- action bounds (enforce on the server, never trust the policy) ---
static final function float MAX_PITCH_DELTA_DEG() { return 25.0; }
static final function float MAX_YAW_DELTA_DEG() { return 40.0; }

// --- entity slots: base = OBS_E0_PRESENT() + i * ENT_SLOT_STRIDE() ---
static final function int ENT_SLOT_STRIDE() { return 10; }
static final function int ENT_PRESENT() { return 0; }
static final function int ENT_TEAMMATE() { return 1; }
static final function int ENT_DIR() { return 2; }
static final function int ENT_DIST() { return 5; }
static final function int ENT_RELVEL() { return 6; }
static final function int ENT_HEALTH() { return 8; }
static final function int ENT_VISIBLE() { return 9; }

// --- observation field offsets ---
// self
static final function int OBS_HEALTH_FRAC() { return 0; }  // x1: health / max health, 0..1
static final function int OBS_ARMOR_FRAC() { return 1; }  // x1: armour / max armour, 0..1
static final function int OBS_AMMO_FRAC() { return 2; }  // x1: ammo in clip / clip size, 0..1
static final function int OBS_AMMO_RESERVE_FRAC() { return 3; }  // x1: reserve ammo, 0..1
static final function int OBS_WEAPON_ID_NORM() { return 4; }  // x1: weapon index / max weapon index
static final function int OBS_VEL_LOCAL() { return 5; }  // x3: velocity in the bot's own frame (fwd,right,up), / max speed
static final function int OBS_SPEED_FRAC() { return 8; }  // x1: |velocity| / max ground speed
static final function int OBS_PITCH_NORM() { return 9; }  // x1: view pitch / 90deg, -1..1
static final function int OBS_ON_GROUND() { return 10; }  // x1: 1 if standing on something
static final function int OBS_CROUCHING() { return 11; }  // x1: 1 if ducked
static final function int OBS_IN_WATER() { return 12; }  // x1: 1 if submerged
static final function int OBS_RELOADING() { return 13; }  // x1: 1 if mid-reload
static final function int OBS_ALIVE() { return 14; }  // x1: 1 if alive (0 during respawn wait)
// geom
static final function int OBS_RAY_H() { return 15; }  // x16: 16 horizontal raycast distances / far plane, starting straight ahead and going clockwise
static final function int OBS_RAY_UP() { return 31; }  // x1: distance to ceiling / far plane
static final function int OBS_RAY_DOWN() { return 32; }  // x1: distance to floor / far plane (step/ledge sensing)
// ent
static final function int OBS_E0_PRESENT() { return 33; }  // x1: 1 if this slot holds an entity
static final function int OBS_E0_IS_TEAMMATE() { return 34; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E0_DIR() { return 35; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E0_DIST_NORM() { return 38; }  // x1: distance / far plane
static final function int OBS_E0_REL_VEL() { return 39; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E0_HEALTH_FRAC() { return 41; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E0_VISIBLE() { return 42; }  // x1: 1 if we currently have line of sight
static final function int OBS_E1_PRESENT() { return 43; }  // x1: 1 if this slot holds an entity
static final function int OBS_E1_IS_TEAMMATE() { return 44; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E1_DIR() { return 45; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E1_DIST_NORM() { return 48; }  // x1: distance / far plane
static final function int OBS_E1_REL_VEL() { return 49; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E1_HEALTH_FRAC() { return 51; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E1_VISIBLE() { return 52; }  // x1: 1 if we currently have line of sight
static final function int OBS_E2_PRESENT() { return 53; }  // x1: 1 if this slot holds an entity
static final function int OBS_E2_IS_TEAMMATE() { return 54; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E2_DIR() { return 55; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E2_DIST_NORM() { return 58; }  // x1: distance / far plane
static final function int OBS_E2_REL_VEL() { return 59; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E2_HEALTH_FRAC() { return 61; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E2_VISIBLE() { return 62; }  // x1: 1 if we currently have line of sight
static final function int OBS_E3_PRESENT() { return 63; }  // x1: 1 if this slot holds an entity
static final function int OBS_E3_IS_TEAMMATE() { return 64; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E3_DIR() { return 65; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E3_DIST_NORM() { return 68; }  // x1: distance / far plane
static final function int OBS_E3_REL_VEL() { return 69; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E3_HEALTH_FRAC() { return 71; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E3_VISIBLE() { return 72; }  // x1: 1 if we currently have line of sight
static final function int OBS_E4_PRESENT() { return 73; }  // x1: 1 if this slot holds an entity
static final function int OBS_E4_IS_TEAMMATE() { return 74; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E4_DIR() { return 75; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E4_DIST_NORM() { return 78; }  // x1: distance / far plane
static final function int OBS_E4_REL_VEL() { return 79; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E4_HEALTH_FRAC() { return 81; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E4_VISIBLE() { return 82; }  // x1: 1 if we currently have line of sight
static final function int OBS_E5_PRESENT() { return 83; }  // x1: 1 if this slot holds an entity
static final function int OBS_E5_IS_TEAMMATE() { return 84; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E5_DIR() { return 85; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E5_DIST_NORM() { return 88; }  // x1: distance / far plane
static final function int OBS_E5_REL_VEL() { return 89; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E5_HEALTH_FRAC() { return 91; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E5_VISIBLE() { return 92; }  // x1: 1 if we currently have line of sight
static final function int OBS_E6_PRESENT() { return 93; }  // x1: 1 if this slot holds an entity
static final function int OBS_E6_IS_TEAMMATE() { return 94; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E6_DIR() { return 95; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E6_DIST_NORM() { return 98; }  // x1: distance / far plane
static final function int OBS_E6_REL_VEL() { return 99; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E6_HEALTH_FRAC() { return 101; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E6_VISIBLE() { return 102; }  // x1: 1 if we currently have line of sight
static final function int OBS_E7_PRESENT() { return 103; }  // x1: 1 if this slot holds an entity
static final function int OBS_E7_IS_TEAMMATE() { return 104; }  // x1: 1 teammate, 0 enemy/neutral
static final function int OBS_E7_DIR() { return 105; }  // x3: unit vector to it in the bot's frame
static final function int OBS_E7_DIST_NORM() { return 108; }  // x1: distance / far plane
static final function int OBS_E7_REL_VEL() { return 109; }  // x2: its velocity relative to us (fwd,right) / max speed
static final function int OBS_E7_HEALTH_FRAC() { return 111; }  // x1: its health 0..1 (0 if unknown)
static final function int OBS_E7_VISIBLE() { return 112; }  // x1: 1 if we currently have line of sight
// event
static final function int OBS_TOOK_DAMAGE() { return 113; }  // x1: damage taken last tick / max health
static final function int OBS_DAMAGE_DIR() { return 114; }  // x2: unit direction the damage came from (fwd,right)
static final function int OBS_KILLED_SOMEONE() { return 116; }  // x1: 1 if we got a kill last tick
static final function int OBS_DIED() { return 117; }  // x1: 1 if we died last tick
// game
static final function int OBS_ROUND_TIME_FRAC() { return 118; }  // x1: elapsed / round length, 0..1
static final function int OBS_SCORE_DIFF_NORM() { return 119; }  // x1: (our score - theirs) / fraglimit, clamped -1..1
static final function int OBS_TEAMMATES_ALIVE_FRAC() { return 120; }  // x1: alive teammates / team size
static final function int OBS_ENEMIES_ALIVE_FRAC() { return 121; }  // x1: alive enemies / team size
static final function int OBS_OBJECTIVE() { return 122; }  // x2: mode-specific (bomb planted, flag carried, ...)
// intent
static final function int OBS_INTENT() { return 124; }  // x16: intent vector from the LLM planner (all zeros = no plan)

defaultproperties
{
}
