#!/usr/bin/env python3
"""gen_catalog.py — build GAMES.CAT for DOSGAME.EXE from the share survey.

Reads the survey JSON produced by survey_share.py and emits the pipe-separated
catalog the DOS utility loads:

    title|zipname|kind|mainexe|size|tile

- kind: R (ready-to-run), I (installer at zip root), C (cd-image) — survey key
- mainexe: best guess = shallowest non-installer exe from the survey record
- tile: <stem8>.PRV (present or not; the DOS side shows it only if the file
  exists in C:\\DOSGAME\\TILES)

Only plain zips are cataloged (rar/7z/iso need host-side prep first — they get
kind C/X rows so the DOS UI can say "ask the fleet to prep this one").

Usage: gen_catalog.py <survey.json> <out GAMES.CAT> [--limit N]
"""
import json, os, re, sys

SKIP = {"install.exe","setup.exe","setsound.exe","dos4gw.exe","univbe.exe",
        "readme.exe","catalog.exe","order.exe","helpme.exe","config.exe"}

def stem8(name):
    s = os.path.splitext(os.path.basename(name))[0]
    s = re.sub(r"[^A-Za-z0-9_]", "_", s)[:8].upper()
    return s or "GAME"

def title_of(name):
    t = os.path.splitext(name)[0]
    t = re.sub(r"\((19|20)\d\d\)", "", t)          # (1993)
    t = re.sub(r"\([^)]*\)", "", t)                # (Apogee...)
    t = t.replace("_", " ").strip()
    return re.sub(r"\s+", " ", t)[:40]

def dos83(name):
    """Truncate to a real 8.3 name, not to 12 characters.

    `name.upper()[:12]` looks right (8 + '.' + 3 = 12) but chops the EXTENSION
    off anything with a stem longer than eight: "SUPERGAME1.EXE" became
    "SUPERGAME1.E". The shipped catalog carries 7 such rows, and DOS cannot
    launch any of them.
    """
    base = name.split("/")[-1].split("\\")[-1].upper()
    stem, dot, ext = base.partition(".")
    return stem[:8] + ("." + ext[:3] if dot else "")


def main_exe(rec):
    # .COM matters: survey_share.py collects COM files and even uses them to
    # classify an archive as ready-to-run, but never exported them, so
    # main_exe() returned "" and gen dropped the row. The result was 0 COM-
    # launched games in a 3,000-title DOS catalog — every one of them
    # invisible from the DOS box.
    for lst in (rec.get("exes_shallow") or [],
                rec.get("coms_shallow") or [],
                rec.get("bats_shallow") or []):
        for p in lst:
            base = p.split("/")[-1]
            if base.lower() not in SKIP:
                return dos83(base)
    return ""

def kind_of(rec):
    k = rec.get("kind", "")
    if k == "ready-to-run": return "R"
    if k in ("installer", "cd-image+installer"): return "I"
    if k.startswith("cd-"): return "C"
    return "X"

def main():
    survey, out = sys.argv[1], sys.argv[2]
    limit = 0
    if "--limit" in sys.argv:
        limit = int(sys.argv[sys.argv.index("--limit") + 1])
    recs = json.load(open(survey))
    rows, seen = [], set()
    for r in recs:
        if not r["name"].lower().endswith(".zip"): continue
        k = kind_of(r)
        if k == "X": continue
        exe = main_exe(r)
        if k == "R" and not exe: continue
        t = title_of(r["name"])
        key = t.lower()
        if key in seen: continue
        seen.add(key)
        rows.append((t, r["name"], k, exe or "INSTALL.EXE", r.get("size", 0),
                     stem8(r["name"]) + ".PRV"))
    rows.sort(key=lambda x: x[0].lower())
    if limit: rows = rows[:limit]
    with open(out, "w", newline="") as f:
        f.write("# GAMES.CAT generated by gen_catalog.py — title|zip|kind|exe|size|tile\n")
        for t, z, k, e, s, p in rows:
            f.write("%s|%s|%s|%s|%d|%s\n" % (t, z, k, e, s, p))
    print("wrote %d entries to %s" % (len(rows), out))

if __name__ == "__main__":
    main()
