#!/usr/bin/env python3
"""Pre-package DOS titles for a bulk fill of a box's game drive (.243's D:).

DOSGAME's own install path (HTGET + UNZIP in real DOS) runs one title at a
time at ~30 s per small title - fine for a person picking a game, far too slow
to fill a disk overnight. This packs chosen titles on the HOST into
ready-to-unzip archives the box can expand in one batch run:

  * each title becomes <STEM>.ZIP, STEM = serve_dosgames.zip_stem(original
    zip name) - the same 8.3 directory DOSGAME itself would create, so a title
    filled this way and one installed from the menu land in the same place;
  * a lone top-level directory is stripped (the game sits at <gamedir>\\STEM);
  * every member name must already be 8.3 (DOS UNZIP cannot create long
    names); a title that is not is REFUSED and reported, not mangled;
  * a DOSGAME.TXT names the launcher and the title (dosgame.c reads the first
    data line: "<8.3 launcher><TAB><title>");
  * Glide titles also get the Voodoo 2's DOS GLIDE2X.OVL (Glide 2.56) beside
    the exe - their own trees ship Voodoo 1 overlays or none - and a small
    launcher batch that sets FX_GLIDE_NO_SPLASH.

Output: <out>/<STEM>.ZIP, <out>/MANIFEST.TXT (STEM|title|launcher|files|bytes|source)
and <out>/FILL.BAT, the box-side batch (DJGPP UNZIP in a Win98 DOS box):

    python3 scripts/dosgames/prep_fill.py --out /tmp/fill --titles titles.json

titles.json: [{"zip": "<path to the share zip>", "title": "...",
               "launcher": "GTA3DFX.BAT", "glide": true,
               "batches": {"GTA3DFX.BAT": "...", ...}}, ...]
"""
import argparse
import io
import json
import os
import re
import sys
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from serve_dosgames import zip_stem  # noqa: E402  (same function DOSGAME uses)

V2_OVL = "/mnt/retro-share/Files/Drivers/3DFX/Win9x/voodoo2-30202-fleet/GLIDE2X.OVL"
NAME83 = re.compile(r"^[A-Z0-9_\-!#$%&'@^`{}~]{1,8}(\.[A-Z0-9_\-!#$%&'@^`{}~]{1,3})?$")


def is_83_path(p):
    return all(NAME83.match(part) for part in p.upper().split("/") if part)


def pack(entry, out_dir, ovl):
    src = entry["zip"]
    stem = zip_stem(os.path.basename(src))
    zin = zipfile.ZipFile(src)
    files = [i for i in zin.infolist() if not i.is_dir()]
    tops = {i.filename.split("/")[0] for i in files}
    strip = ""
    if len(tops) == 1 and all("/" in i.filename for i in files):
        strip = next(iter(tops)) + "/"
    bad = [i.filename for i in files if not is_83_path(i.filename[len(strip):])]
    dropped = []
    if bad and entry.get("drop_non83"):
        # explicit, per title: only for files the DOS game does not need
        # (Windows launchers, docs, an empty savegames folder) - each is listed
        dropped = bad
        files = [i for i in files if i.filename not in set(bad)]
        bad = []
    if bad:
        return {"stem": stem, "title": entry["title"], "refused": "non-8.3 names: %s" % bad[:5]}
    buf = io.BytesIO()
    zout = zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED)
    nbytes = 0
    for i in files:
        name = i.filename[len(strip):].upper()
        data = zin.read(i)
        zout.writestr(name, data)
        nbytes += len(data)
    extra = dict(entry.get("batches", {}))
    if entry.get("glide"):
        for d in entry.get("ovl_dirs", [""]):
            zout.writestr((d + "/" if d else "") + "GLIDE2X.OVL", ovl)
    for name, text in extra.items():
        zout.writestr(name.upper(), text.replace("\n", "\r\n").encode("ascii"))
    launcher = entry["launcher"].upper()
    title = re.sub(r"[()]", "-", entry["title"])        # no parentheses in anything a batch expands
    zout.writestr("DOSGAME.TXT", ("%s\t%s\r\n" % (launcher, title)).encode("ascii", "replace"))
    zout.close()
    open(os.path.join(out_dir, stem + ".ZIP"), "wb").write(buf.getvalue())
    return {"stem": stem, "title": title, "launcher": launcher, "files": len(files) + len(extra) + 1,
            "bytes": nbytes, "zip_bytes": len(buf.getvalue()), "source": src, "dropped": dropped}


def fill_bat(rows, share_dir, gamedir):
    """Box-side: expand every title with the DJGPP UNZIP DOSGAME already ships.
    Skips a title whose FILL.OK exists, so a re-run resumes. 8.3 paths only."""
    lines = ["@echo off", "rem generated by prep_fill.py - expands the pre-packed DOS titles",
             "if not exist %s\\NUL md %s" % (gamedir, gamedir)]
    for r in rows:
        if "refused" in r:
            continue
        s = r["stem"]
        lines += [
            "if exist %s\\%s\\FILL.OK goto done_%s" % (gamedir, s, s),
            "C:\\DOSGAME\\UNZIP.EXE -qq -o %s\\%s.ZIP -d %s\\%s" % (share_dir, s, gamedir, s),
            "if errorlevel 1 echo FAIL %s>> %s\\FILL.LOG" % (s, gamedir),
            "if errorlevel 1 goto done_%s" % s,
            "echo %d %d> %s\\%s\\FILL.OK" % (r["files"], r["bytes"], gamedir, s),
            "echo OK %s>> %s\\FILL.LOG" % (s, gamedir),
            ":done_%s" % s,
        ]
    lines.append("echo END>> %s\\FILL.LOG" % gamedir)
    return "\r\n".join(lines) + "\r\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--titles", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--share-dir", default="W:\\FILES\\GAMES\\DOSFILL")
    ap.add_argument("--gamedir", default="D:\\GAMES")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    ovl = open(V2_OVL, "rb").read()
    rows = [pack(e, a.out, ovl) for e in json.load(open(a.titles))]
    stems = [r["stem"] for r in rows]
    assert len(stems) == len(set(stems)), "duplicate STEM"
    with open(os.path.join(a.out, "MANIFEST.TXT"), "w") as f:
        for r in rows:
            if "refused" in r:
                print("REFUSED %s (%s): %s" % (r["stem"], r["title"], r["refused"]))
                continue
            f.write("%s|%s|%s|%d|%d|%s\n" % (r["stem"], r["title"], r["launcher"], r["files"], r["bytes"], r["source"]))
            print("%s  %-40s %6.1f MB -> %5.1f MB zip%s" % (r["stem"], r["title"][:40], r["bytes"] / 1e6, r["zip_bytes"] / 1e6,
                  ("   dropped non-8.3: %s" % r["dropped"]) if r.get("dropped") else ""))
    open(os.path.join(a.out, "FILL.BAT"), "w", newline="").write(fill_bat(rows, a.share_dir, a.gamedir))


if __name__ == "__main__":
    main()
