#!/usr/bin/env python3
"""Stage DOS games as Windows 9x library titles - a desktop icon that runs the
game natively in Windows 98's own DOS box.

WHY (2026-09-29): .243 (Win98 SE, Pentium 166, Voodoo 2, SB16 + gameport
stick) now keeps its games on a 72 GB E: that only Windows can see - real-mode
DOS no longer reaches that disk - and the user asked for "all of the DOS flight
simulator type games", each with "icons with correct iconography on the
desktop". A GAMESYNC title does exactly that: the agent copies the tree to the
box's GamesDir and makes a shortcut (a PIF, for a DOS target) with the icon
named in launch.txt.

Each title gets:
  * the game's installed tree (the TOSEC zip, a lone top folder stripped; every
    name must already be 8.3 - DOS cannot open anything else - or be listed in
    drop_non83, files the game does not need);
  * `Play <name>.bat` - COMMAND.COM dialect: the shortcut starts in the title's
    folder, the batch cd's where the game wants to run and starts it; the DOS
    box goes full screen when the game sets a graphics mode. BLASTER comes
    from the box's AUTOEXEC.BAT;
  * ICON.ICO - the game's own art, BMP entries (a PNG-only .ico is a blank
    page on Windows 9x/XP);
  * launch.txt and requires.json with max_os win9x: an NT box gets nothing
    (no DOSBox is staged - these want a real 486/Pentium, not an emulated one).

Spec: a JSON list of {"lib": "Flight-Falcon3", "title": "Falcon 3.0",
"year": 1991, "zip": "<share path>" | "tree": "<local dir>", "strip_top": ""
| "<dir>", "launch": ["cd X", "GAME.EXE"], "icon": "<path to .ico>",
"drop_non83": [...], "notes": "..."}. "tree" is a directory prepared on the
host - a game whose own setup was run in DOSBox with the target's Sound Blaster
settings, an add-on merged over its base game - and is copied as it stands.

    python3 scripts/dosgames/stage_win9x_dos.py --spec spec.json [--only Flight-Falcon3] [--dry-run]

Writing goes through smbclient with the vaulted NAS credentials (the auth file
is umask 077 and deleted afterwards); the result is verified through the
separate read-only /mnt mount - file count, every size, and md5 of the files
this script writes - because a write that reports success is not evidence.
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LIB_MNT = "/mnt/retro-share/Files/Games-Library"
LIB_SMB = "Files/Games-Library"
NAME83 = re.compile(r"^[A-Z0-9_\-!#$%&'@^`{}~]{1,8}(\.[A-Z0-9_\-!#$%&'@^`{}~]{1,3})?$")


def is_83(path):
    return all(NAME83.match(p) for p in path.upper().split("/") if p)


def clean_name(s):
    """A display/file name Windows and COMMAND.COM both accept: no parentheses
    (unlaunchable through the agent), no : / \\ * ? " < > | and no & or +."""
    s = s.replace(":", " - ").replace("&", " and ").replace("+", " and ").replace("/", " - ")
    s = re.sub(r"[()\\*?\"<>|]", "", s)
    return re.sub(r"\s+", " ", s).strip(" .")


def play_bat(t):
    lines = ["@echo off",
             "rem %s - %s - DOS game for Windows 9x." % (clean_name(t["title"]), t.get("year", "")),
             "rem The desktop shortcut runs this in a DOS box that goes full screen",
             "rem when the game sets a graphics mode; it starts in this folder.",
             "rem COMMAND.COM dialect: no %~dp0, no cd /d, no blocks, no angle brackets.",
             "rem Generated by scripts/dosgames/stage_win9x_dos.py."]
    for l in t["launch"]:
        assert not re.search(r"[<>()]", l), l
        lines.append(l)
    # Windows 9x closes a DOS box on exit only when its screen is empty, and a
    # DOS game prints on its way out - without this every quit left a
    # "Finished - <game>" window behind. Measured on .243, 2026-09-29.
    lines += ["rem CLS last: a DOS box closes on exit only if its screen is empty.",
              "cls"]
    return ("\r\n".join(lines) + "\r\n").encode("ascii")


def members(t):
    """(relative '/'-separated name, opener) for every file of the title's source:
    a prepared local "tree" as it stands, else the TOSEC "zip"."""
    if t.get("tree"):
        base = t["tree"]
        for d, _, fs in os.walk(base):
            for f in sorted(fs):
                full = os.path.join(d, f)
                rel = os.path.relpath(full, base).replace(os.sep, "/")
                yield rel, (lambda full=full: open(full, "rb"))
        return
    z = zipfile.ZipFile(t["zip"])
    for i in z.infolist():
        if not i.is_dir():
            yield i.filename, (lambda i=i: z.open(i))


def icon_problem(path):
    """Why a Windows 9x desktop cannot draw this icon, or None - the validator's
    own rule (scripts/validate-staged-library.py), so the two never disagree."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "vsl", os.path.join(REPO, "scripts", "validate-staged-library.py"))
    vsl = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(vsl)
    return vsl.icon_9x_problem(path) or (vsl.icon_xp_problem(path) or (None, None))[1]


def build(t, work):
    """Unpack and assemble one title under work/<lib>; returns (dir, files it wrote)."""
    lib = t["lib"]
    assert re.match(r"^[A-Za-z0-9][A-Za-z0-9\-]*$", lib), lib
    root = os.path.join(work, lib)
    os.makedirs(root)
    strip = t.get("strip_top", "")
    drop = set(x.upper() for x in t.get("drop_non83", []))
    bad = []
    for name, opener in members(t):
        if strip:
            if not name.startswith(strip + "/"):
                continue
            name = name[len(strip) + 1:]
        if name.upper() in drop:
            continue
        if not is_83(name):
            bad.append(name)
            continue
        dst = os.path.join(root, *name.upper().split("/"))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with opener() as src, open(dst, "wb") as out:
            shutil.copyfileobj(src, out)
    if bad:
        raise SystemExit("%s: non-8.3 names (add to drop_non83 if the game does not need them): %s" % (lib, bad[:8]))
    disp = clean_name(t["title"])
    bat = "Play %s.bat" % disp
    open(os.path.join(root, bat), "wb").write(play_bat(t))
    shutil.copyfile(t["icon"], os.path.join(root, "ICON.ICO"))
    ico = open(os.path.join(root, "ICON.ICO"), "rb").read(6)
    assert ico[:4] == b"\x00\x00\x01\x00", "%s: not an .ico" % t["icon"]
    why = icon_problem(os.path.join(root, "ICON.ICO"))
    if why:
        raise SystemExit("%s: icon %s %s" % (lib, t["icon"], why))
    launch = "%s\t%s\tICON.ICO\r\n" % (bat, disp)
    source = os.path.basename(t.get("zip") or os.path.normpath(t["tree"]))
    launch += ("#\r\n# DOS game staged for Windows 9x by scripts/dosgames/stage_win9x_dos.py -\r\n"
               "# the desktop shortcut runs it natively in a DOS box. Source: %s\r\n" % source)
    assert len(launch.split("\r\n")[0]) < 1023
    open(os.path.join(root, "launch.txt"), "wb").write(launch.encode("latin-1"))
    size = sum(os.path.getsize(os.path.join(d, f)) for d, _, fs in os.walk(root) for f in fs)
    req = {"requirements_version": 1, "title": lib, "year": t.get("year"),
           "max_os": "win9x", "min_cpu_mhz": 25, "min_ram_mb": 8,
           "disk_mb": size // 1048576 + 5,
           "notes": ("DOS game staged for Windows 9x boxes: its desktop shortcut runs it natively in a "
                     "Win9x DOS box, full screen. NT boxes do not get it - no DOSBox wrapper is staged. "
                     "Sound: BLASTER from the box's AUTOEXEC.BAT; if a game is silent, run its own setup "
                     "once. " + t.get("notes", "")).strip()}
    open(os.path.join(root, "requires.json"), "w").write(json.dumps(req, indent=2) + "\n")
    return root, [bat, "ICON.ICO", "launch.txt", "requires.json"]


def smb(auth, cmds):
    r = subprocess.run(["smbclient", "-A", auth, "//192.168.1.122/files", "-c", cmds],
                       capture_output=True, text=True, timeout=3600)
    return r.returncode, r.stdout + r.stderr


def md5(p):
    h = hashlib.md5()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def _ci(base, rel_upper):
    """The real path under `base` of an upper-cased relative name - the share and
    the local tree agree on names only case-insensitively."""
    cur = base
    for part in rel_upper.split(os.sep):
        hit = [n for n in os.listdir(cur) if n.upper() == part.upper()]
        cur = os.path.join(cur, hit[0] if hit else part)
    return cur


def verify(local, lib, mine):
    """The tree on the share, read back through /mnt - a different mount from
    the smbclient session that wrote it: same files, same sizes, same md5."""
    remote = os.path.join(LIB_MNT, lib)
    want = {}
    for d, _, fs in os.walk(local):
        for f in fs:
            p = os.path.join(d, f)
            want[os.path.relpath(p, local).upper()] = os.path.getsize(p)
    got = {}
    for d, _, fs in os.walk(remote):
        for f in fs:
            p = os.path.join(d, f)
            got[os.path.relpath(p, remote).upper()] = os.path.getsize(p)
    missing = sorted(set(want) - set(got))
    wrong = sorted(k for k in want if k in got and got[k] != want[k])
    extra = sorted(set(got) - set(want))
    # md5 of every file present on both sides: a tree is copied as it stands,
    # and a file of the right size with the wrong bytes is still a broken game.
    bad_md5 = [k for k in sorted(set(want) & set(got)) if want[k] == got[k]
               and md5(_ci(local, k)) != md5(_ci(remote, k))]
    return missing, wrong, extra, bad_md5


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True)
    ap.add_argument("--only", action="append", default=[])
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    spec = json.load(open(a.spec))
    if a.only:
        spec = [t for t in spec if t["lib"] in a.only]
    work = tempfile.mkdtemp(prefix="stage9x-")
    auth = os.path.join(work, "nas.auth")
    ok = True
    try:
        if not a.dry_run:
            kv = os.path.join(REPO, "scripts", "fleet", "keyvault.py")
            user = subprocess.run([sys.executable, kv, "get", "fleet-nas-192-168-1-122-user"],
                                  capture_output=True, text=True).stdout.strip()
            pw = subprocess.run([sys.executable, kv, "get", "fleet-nas-192-168-1-122-password"],
                                capture_output=True, text=True).stdout.strip()
            old = os.umask(0o077)
            with open(auth, "w") as f:
                f.write("username = %s\npassword = %s\n" % (user, pw))
            os.umask(old)
        for t in spec:
            local, mine = build(t, work)
            n = sum(len(fs) for _, _, fs in os.walk(local))
            mb = sum(os.path.getsize(os.path.join(d, f)) for d, _, fs in os.walk(local) for f in fs) / 1e6
            if a.dry_run:
                print("DRY  %-28s %5d files %7.1f MB  %s" % (t["lib"], n, mb, " | ".join(t["launch"])))
                continue
            if os.path.exists(os.path.join(LIB_MNT, t["lib"])):
                print("SKIP %-28s already in the library - not overwriting" % t["lib"])
                continue
            rc, out = smb(auth, 'prompt OFF; recurse ON; cd "%s"; mkdir "%s"; cd "%s"; lcd "%s"; mput *'
                          % (LIB_SMB, t["lib"], t["lib"], local))
            missing, wrong, extra, bad = verify(local, t["lib"], mine)
            if missing or wrong or bad:
                ok = False
                print("FAIL %-28s rc=%d missing=%d wrong-size=%d md5-bad=%s %s" %
                      (t["lib"], rc, len(missing), len(wrong), bad, (missing + wrong)[:5]))
            else:
                print("OK   %-28s %5d files %7.1f MB verified through /mnt%s" %
                      (t["lib"], n, mb, " (extra on share: %d)" % len(extra) if extra else ""))
    finally:
        if os.path.exists(auth):
            os.remove(auth)
        shutil.rmtree(work, ignore_errors=True)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
