#!/usr/bin/env python3
"""Stage DOS games as Windows 9x library titles - a desktop icon that runs the
game natively in Windows 98's own DOS box.

WHY (2026-09-29): .243 (Win98 SE, Pentium 166, Voodoo 2, SB16 + gameport
stick) now keeps its games on a 72 GB E: that only Windows can see - real-mode
DOS no longer reaches that disk - and the user asked for "all of the DOS flight
simulator type games", each with "icons with correct iconography on the
desktop". A GAMESYNC title does exactly that: the agent copies the tree to the
box's GamesDir and makes a shortcut (a PIF, for a DOS target) with the icon
named in launch.txt.

Each title gets:
  * the game's installed tree (the TOSEC zip, a lone top folder stripped; every
    name must already be 8.3 - DOS cannot open anything else - or be listed in
    drop_non83, files the game does not need);
  * `Play <name>.bat` - COMMAND.COM dialect: the shortcut starts in the title's
    folder, the batch cd's where the game wants to run and starts it; the DOS
    box goes full screen when the game sets a graphics mode. BLASTER comes
    from the box's AUTOEXEC.BAT;
  * <NAME>.ICO - the game's own art, under a name no other title's icon has:
    Windows 98's shell caches an icon by its FILE NAME, so 39 titles each
    shipping ICON.ICO all showed the first one's art on .243 (2026-09-29).
    BMP entries (a PNG-only .ico is a blank
    page on Windows 9x/XP);
  * launch.txt and requires.json with max_os win9x: an NT box gets nothing
    (no DOSBox is staged - these want a real 486/Pentium, not an emulated one).

Spec: a JSON list of {"lib": "Flight-Falcon3", "title": "Falcon 3.0",
"year": 1991, "zip": "<share path>" | "tree": "<local dir>", "strip_top": ""
| "<dir>", "launch": ["cd X", "GAME.EXE"], "icon": "<path to .ico>",
"drop_non83": [...], "notes": "..."}. "tree" is a directory prepared on the
host - a game whose own setup was run in DOSBox with the target's Sound Blaster
settings, an add-on merged over its base game - and is copied as it stands.

    python3 scripts/dosgames/stage_win9x_dos.py --spec spec.json [--only Flight-Falcon3] [--dry-run]

Writing goes through smbclient with the vaulted NAS credentials (the auth file
is umask 077 and deleted afterwards); the result is verified through the
separate read-only /mnt mount - file count, every size, and md5 of the files
this script writes - because a write that reports success is not evidence.
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import zipfile

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LIB_MNT = "/mnt/retro-share/Files/Games-Library"
LIB_SMB = "Files/Games-Library"
VERIFY_WAIT_S = 90
NAME83 = re.compile(r"^[A-Z0-9_\-!#$%&'@^`{}~]{1,8}(\.[A-Z0-9_\-!#$%&'@^`{}~]{1,3})?$")


def is_83(path):
    return all(NAME83.match(p) for p in path.upper().split("/") if p)


def clean_name(s):
    """A display/file name Windows and COMMAND.COM both accept: no parentheses
    (unlaunchable through the agent), no : / \\ * ? " < > | and no & or +."""
    s = s.replace(":", " - ").replace("&", " and ").replace("+", " and ").replace("/", " - ")
    s = re.sub(r"[()\\*?\"<>|]", "", s)
    return re.sub(r"\s+", " ", s).strip(" .")


def play_bat(t):
    lines = ["@echo off",
             "rem %s - %s - DOS game for Windows 9x." % (clean_name(t["title"]), t.get("year", "")),
             "rem The desktop shortcut runs this in a DOS box that goes full screen",
             "rem when the game sets a graphics mode; it starts in this folder.",
             "rem COMMAND.COM dialect: no %~dp0, no cd /d, no blocks, no angle brackets.",
             "rem Generated by scripts/dosgames/stage_win9x_dos.py."]
    for l in t["launch"]:
        assert not re.search(r"[<>()]", l), l
        # A batch started from a batch without CALL never returns, and then
        # the CLS below never runs (Retribution's RET.BAT).
        first = l.split()[0] if l.split() else ""
        if first.upper().endswith(".BAT"):
            l = "call " + l
        lines.append(l)
    # Windows 9x closes a DOS box on exit only when its screen is empty, and a
    # DOS game prints on its way out - without this every quit left a
    # "Finished - <game>" window behind. Measured on .243, 2026-09-29.
    lines += ["rem CLS last: a DOS box closes on exit only if its screen is empty.",
              "cls"]
    return ("\r\n".join(lines) + "\r\n").encode("ascii")


# The one-shot line a real-DOS title's launcher appends to C:\AUTOEXEC.BAT
# (once - the launcher looks for it first). AUTOEXEC.BAT runs in real mode
# before Windows loads, so the game runs there with the box's own drivers
# (BLASTER, the DOS mouse) and Windows starts when it returns. The stale RAN.BAT
# goes FIRST: a game that hangs the PC runs once, never at every boot after.
RD_HOOK = ("\r\n"
           "rem rundos v2: a real-DOS game armed by its Windows desktop icon runs here ONCE,\r\n"
           "rem then Windows starts - scripts/dosgames/stage_win9x_dos.py. Idle, it skips.\r\n"
           "rem An EMS title chose this boot's menu entry; its CONFIG.SYS goes back first.\r\n"
           "if exist C:\\RUNDOS\\CONFIG.SAV copy C:\\RUNDOS\\CONFIG.SAV C:\\CONFIG.SYS > nul\r\n"
           "if exist C:\\RUNDOS\\CONFIG.SAV del C:\\RUNDOS\\CONFIG.SAV\r\n"
           "if exist C:\\RUNDOS\\RAN.BAT del C:\\RUNDOS\\RAN.BAT\r\n"
           "if exist C:\\RUNDOS\\NEXT.BAT ren C:\\RUNDOS\\NEXT.BAT RAN.BAT\r\n"
           "if exist C:\\RUNDOS\\RAN.BAT call C:\\RUNDOS\\RAN.BAT\r\n")


def rd_dir(t):
    d = t["real_dos"]["dir"].upper()
    assert re.match(r"^[A-Z0-9_]{1,8}$", d), d
    return d


def play_bat_real_dos(t, mb):
    """The Windows-side launcher of a title that runs ONLY in real MS-DOS - a
    DOS extender or memory manager Windows cannot host (Origin's JEMM, Phar
    Lap TNT), a game that page-faults under Windows' DPMI (Retribution's
    DOS/4GW 1.92, EF2000's X-32VM: both fault at addresses near 2 GB in a Win98
    DOS box), or one that wants more conventional memory than a DOS box has.

    Real-mode DOS sees only the disks the BIOS types - on .243 not the E: that
    GAMESYNC fills - so the game is copied to C:\\GAMES\\<dir> (xcopy /D: only
    files newer than the copy there), the one-shot rundos line is armed and the
    PC restarts through the shell with FORCE (Win98's agent REBOOT route,
    proven on .243): the game runs from AUTOEXEC.BAT and Windows starts when
    it quits. NOT an MS-DOS mode PIF: that route shuts Windows down WITHOUT
    force, and the agent's own console - a DOS VM on Win98 - stops it with a
    dialog (the cmosmbr install on .243, 2026-09-29)."""
    d, name = rd_dir(t), clean_name(t["title"])
    lines = ["@echo off",
             "rem %s - %s - a DOS game that runs ONLY in real MS-DOS." % (name, t.get("year", "")),
             "rem Windows cannot run it in a DOS box and real-mode DOS sees only C:, so",
             "rem this copies it to C:\\GAMES\\%s, arms the one-shot rundos line in" % d,
             "rem C:\\AUTOEXEC.BAT and restarts: the game runs before Windows loads,",
             "rem and Windows starts again when it quits.",
             "rem Generated by scripts/dosgames/stage_win9x_dos.py.",
             "echo.",
             "echo  %s runs in MS-DOS, outside Windows. The PC restarts," % name,
             "echo  runs the game, and comes back to Windows when you quit it.",
             "echo.",
             "choice /c:yn /t:y,10 Restart now",
             "if errorlevel 2 goto end",
             "echo Copying the game to C:\\GAMES\\%s ..." % d,
             "xcopy *.* C:\\GAMES\\%s\\ /E /I /D /Y /Q > nul" % d,
             "rem XCOPY: 4 = could not start - no room, bad drive - and 5 = a write failed.",
             "if errorlevel 4 goto nocopy",
             "if not exist C:\\GAMES\\%s\\RDGAME.BAT goto nocopy" % d,
             "if not exist C:\\RUNDOS\\NUL md C:\\RUNDOS"]
    if t["real_dos"].get("ems"):
        # The boot menu's EMS entry for this one boot: CONFIG.SYS saved, its
        # menudefault pointed at [EMS] (MENUDEF9.EXE = scripts/fleet/win9x/
        # menudef9x.c), and the rundos line restores the saved copy FIRST at
        # the next boot. START /W: a DOS box does not wait for a Windows program.
        lines += ["copy C:\\CONFIG.SYS C:\\RUNDOS\\CONFIG.SAV > nul",
                  "start /w MENUDEF9.EXE EMS"]
    lines += ["echo call C:\\GAMES\\%s\\RDGAME.BAT> C:\\RUNDOS\\NEXT.BAT" % d,
             "if not exist C:\\RUNDOS\\NEXT.BAT goto nocopy",
             "find \"rundos v2\" C:\\AUTOEXEC.BAT > nul",
             "if errorlevel 1 type RDHOOK.TXT >> C:\\AUTOEXEC.BAT",
             "rundll32.exe shell32.dll,SHExitWindowsEx 6",
             "goto end",
             ":nocopy",
             "echo.",
             "echo  COULD NOT COPY THE GAME TO C:\\GAMES\\%s - is C: full? It needs about %d MB." % (d, mb),
             "echo  Nothing was armed and Windows keeps running.",
             "pause",
             ":end",
             "rem CLS last: a Windows 9x DOS box closes on exit only if its screen is empty.",
             "cls"]
    return ("\r\n".join(lines) + "\r\n").encode("ascii")


def rd_game_bat(t):
    """RDGAME.BAT - what the rundos line runs, in REAL DOS, from C:. An EMS
    title checks the boot menu's choice first: real DOS has EMS only when
    CONFIG.SYS loaded EMM386 (on .243 the menu's 2 - With EMS)."""
    d = rd_dir(t)
    lines = ["@echo off",
             "rem %s in real MS-DOS - run ONCE by the rundos line in C:\\AUTOEXEC.BAT;" % clean_name(t["title"]),
             "rem Windows starts when it returns. Generated by scripts/dosgames/stage_win9x_dos.py.",
             "C:", "cd \\GAMES\\%s" % d]
    if t["real_dos"].get("ems"):
        lines += ["if \"%CONFIG%\"==\"EMS\" goto run",
                  "echo.",
                  "echo  %s needs the boot menu's EMS and upper memory entry." % clean_name(t["title"]),
                  "echo  Restart, choose 2 - With EMS - and start it again from its desktop icon.",
                  "pause",
                  "goto done",
                  ":run"]
    for l in t["launch"]:
        assert not re.search(r"[<>()]", l), l
        first = l.split()[0] if l.split() else ""
        lines.append("call " + l if first.upper().endswith(".BAT") else l)
    lines += [":done", "C:", "cd \\"]
    return ("\r\n".join(lines) + "\r\n").encode("ascii")


def icon_file_name(t):
    """An 8.3 icon name unique to the title: "icon_name" from the spec, else the
    title part of the library name - Flight-Falcon3 -> FALCON3.ICO. Windows 98
    caches icons by file NAME: every Flight-* title once shipped ICON.ICO and
    .243 drew F-14 Fleet Defender's art on all 39 desktop icons."""
    name = t.get("icon_name") or re.sub(r"[^A-Za-z0-9]", "", t["lib"].split("-", 1)[-1])[:8] + ".ICO"
    name = name.upper()
    assert is_83(name) and name.endswith(".ICO") and name != "ICON.ICO", name
    return name


def members(t):
    """(relative '/'-separated name, opener) for every file of the title's source:
    a prepared local "tree" as it stands, else the TOSEC "zip"."""
    if t.get("tree"):
        base = t["tree"]
        for d, _, fs in os.walk(base):
            for f in sorted(fs):
                full = os.path.join(d, f)
                rel = os.path.relpath(full, base).replace(os.sep, "/")
                yield rel, (lambda full=full: open(full, "rb"))
        return
    z = zipfile.ZipFile(t["zip"])
    for i in z.infolist():
        if not i.is_dir():
            yield i.filename, (lambda i=i: z.open(i))


def icon_problem(path):
    """Why a Windows 9x desktop cannot draw this icon, or None - the validator's
    own rule (scripts/validate-staged-library.py), so the two never disagree."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "vsl", os.path.join(REPO, "scripts", "validate-staged-library.py"))
    vsl = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(vsl)
    return vsl.icon_9x_problem(path) or (vsl.icon_xp_problem(path) or (None, None))[1]


def build(t, work):
    """Unpack and assemble one title under work/<lib>; returns (dir, files it wrote)."""
    lib = t["lib"]
    assert re.match(r"^[A-Za-z0-9][A-Za-z0-9\-]*$", lib), lib
    root = os.path.join(work, lib)
    os.makedirs(root)
    strip = t.get("strip_top", "")
    drop = set(x.upper() for x in t.get("drop_non83", []))
    bad = []
    for name, opener in members(t):
        if strip:
            if not name.startswith(strip + "/"):
                continue
            name = name[len(strip) + 1:]
        if name.upper() in drop:
            continue
        if not is_83(name):
            bad.append(name)
            continue
        dst = os.path.join(root, *name.upper().split("/"))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with opener() as src, open(dst, "wb") as out:
            shutil.copyfileobj(src, out)
    if bad:
        raise SystemExit("%s: non-8.3 names (add to drop_non83 if the game does not need them): %s" % (lib, bad[:8]))
    other = sum(os.path.getsize(os.path.join(d, f)) for d, _, fs in os.walk(root) for f in fs)
    files = generated(t, other)
    ships = set(_tree(root))      # UPPER: the share, like Windows, ignores case
    overrides = {rel.upper() for rel in spec_files(t)}
    for rel in files:
        if rel.upper() in ships and rel.upper() not in overrides:
            raise SystemExit("%s: the game already has a file %s - %s" % (
                lib, rel, "give the title an icon_name" if rel.upper().endswith(".ICO")
                else "pick another name"))
    for rel, data in files.items():
        open(os.path.join(root, *rel.split("/")), "wb").write(data)
    return root, list(files)


def _libsource():
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "libsource", os.path.join(REPO, "scripts", "fleet", "libsource.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def spec_files(t):
    """The spec's "files": {path in the title: source} - a helper a launcher
    calls (JOYCHK.COM) or a corrected copy of one of the game's own files
    (Terminal Velocity's VOX.INI, TIE Fighter's FRONT.OVL). They are the
    GENERATOR's, like the launcher: written by --update when they differ, and
    allowed to replace a file the game ships (that is what a correction is).

    A source is a repo-relative path (our own files), or a dict naming an
    md5-pinned file on the share (scripts/fleet/libsource.py) - a game's own
    binary, which has no business in git: {"zip": "<share path>", "member":
    "crack.zip/FRONT.OVL", "md5": "..."}. A source that is not the pinned file
    stops the build; it is never staged on trust."""
    out = {}
    for rel, src in sorted(t.get("files", {}).items()):
        rel = rel.replace("\\", "/")
        assert is_83(rel), "%s: %s is not an 8.3 name" % (t["lib"], rel)
        if isinstance(src, dict):
            ls = _libsource()
            try:
                out[rel.upper()] = ls.fetch(src)
            except ls.SourceError as e:
                raise SystemExit("%s: files %s: %s" % (t["lib"], rel, e))
        else:
            out[rel.upper()] = open(os.path.join(REPO, src), "rb").read()
    return out


def generated(t, other_bytes):
    """Every file the generator writes ITSELF for a title - launcher, icon,
    launch.txt, requires.json and, for an MS-DOS mode title, its PIF and
    GAME\\RUN.BAT - as {'/'-separated relative path: bytes}. `other_bytes` is
    the size of everything else in the title (the game's own files), which
    requires.json's disk_mb counts too.

    A fresh build (build) and a fix to a title already staged (update) both
    come through here, so an update of a title whose spec did not change
    rewrites nothing - libwrite never rewrites identical bytes."""
    lib = t["lib"]
    disp = clean_name(t["title"])
    bat = "Play %s.bat" % disp
    files = {}
    if t.get("real_dos"):
        files["RDGAME.BAT"] = rd_game_bat(t)
        files["RDHOOK.TXT"] = RD_HOOK.encode("ascii")
        if t["real_dos"].get("ems"):
            files["MENUDEF9.EXE"] = open(os.path.join(REPO, "scripts", "dosgames", "rundos",
                                                      "MENUDEF9.EXE"), "rb").read()
        files[bat] = play_bat_real_dos(t, other_bytes // 1048576 + 1)
    else:
        files[bat] = play_bat(t)
    for rel, data in spec_files(t).items():
        files[rel] = data
    icon_name = icon_file_name(t)
    files[icon_name] = open(t["icon"], "rb").read()
    assert files[icon_name][:4] == b"\x00\x00\x01\x00", "%s: not an .ico" % t["icon"]
    why = icon_problem(t["icon"])
    if why:
        raise SystemExit("%s: icon %s %s" % (lib, t["icon"], why))
    launch = "%s\t%s\t%s\r\n" % (bat, disp, icon_name)
    source = t.get("source_label") or os.path.basename(t.get("zip") or os.path.normpath(t["tree"]))
    launch += ("#\r\n# DOS game staged for Windows 9x by scripts/dosgames/stage_win9x_dos.py -\r\n"
               "# the desktop shortcut runs it natively in a DOS box. Source: %s\r\n" % source)
    assert len(launch.split("\r\n")[0]) < 1023
    files["launch.txt"] = launch.encode("latin-1")
    size = other_bytes + sum(len(b) for b in files.values())
    req = {"requirements_version": 1, "title": lib, "year": t.get("year"),
           "max_os": "win9x", "min_cpu_mhz": 25, "min_ram_mb": 8,
           "disk_mb": size // 1048576 + 5,
           "notes": ("DOS game staged for Windows 9x boxes: its desktop shortcut runs it natively in a "
                     "Win9x DOS box, full screen. NT boxes do not get it - no DOSBox wrapper is staged. "
                     "Sound: BLASTER from the box's AUTOEXEC.BAT; if a game is silent, run its own setup "
                     "once. " + (("REAL DOS ONLY: this game cannot run inside Windows; its "
                                  "launcher copies it to C:\\GAMES\\%s and restarts the PC into "
                                  "real DOS through the rundos line in AUTOEXEC.BAT%s. "
                                  % (rd_dir(t), " - it needs EMS: boot menu 2, With EMS"
                                     if t["real_dos"].get("ems") else ""))
                                 if t.get("real_dos") else "") + t.get("notes", "")).strip()}
    files["requires.json"] = (json.dumps(req, indent=2) + "\n").encode("ascii")
    return files


def update(t, write, lib_root=None):
    """Bring the files the generator owns in an ALREADY STAGED title in line
    with its spec; the game's own files are not touched. `write(path, data)`
    is a libwrite writer's write_bytes. Returns the relative paths changed.

    Why this exists: build() only ever creates a title - a title already in
    the library is "verified, not overwritten" - so a launcher fix had no way
    through the generator, and a share-only edit is what the next regeneration
    silently undoes (CLAUDE.md, "fix it at the GENERATOR")."""
    lib_dir = os.path.join(lib_root or LIB_MNT, t["lib"])
    if not os.path.isdir(lib_dir):
        raise SystemExit("%s: not staged yet - build it without --update" % t["lib"])
    have = _tree(lib_dir)
    owned = {rel.upper() for rel in generated(t, 0)}
    other = sum(sz for k, (sz, _p) in have.items() if k not in owned)
    changed = []
    for rel, data in generated(t, other).items():
        cur = have.get(rel.upper())
        if cur and cur[0] == len(data) and open(cur[1], "rb").read() == data:
            continue
        write(cur[1] if cur else os.path.join(lib_dir, *rel.split("/")), data)
        changed.append(rel)
    return changed


def smb(auth, cmds):
    r = subprocess.run(["smbclient", "-A", auth, "//192.168.1.122/files", "-c", cmds],
                       capture_output=True, text=True, timeout=3600)
    return r.returncode, r.stdout + r.stderr


def md5(p):
    h = hashlib.md5()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def _tree(base):
    """{UPPER relative path: (size, real path)} - one walk, so names compare
    case-insensitively (the share and the local tree agree on nothing else)
    without listing a directory once per file."""
    out = {}
    for d, _, fs in os.walk(base):
        for f in fs:
            p = os.path.join(d, f)
            out[os.path.relpath(p, base).upper()] = (os.path.getsize(p), p)
    return out


def verify(local, lib, mine):
    """The tree on the share, read back through /mnt - a different mount from
    the smbclient session that wrote it: same files, same sizes, same md5."""
    want, got = _tree(local), _tree(os.path.join(LIB_MNT, lib))
    missing = sorted(set(want) - set(got))
    wrong = sorted(k for k in want if k in got and got[k][0] != want[k][0])
    extra = sorted(set(got) - set(want))
    # md5 of every file present on both sides: a tree is copied as it stands,
    # and a file of the right size with the wrong bytes is still a broken game.
    bad_md5 = [k for k in sorted(set(want) & set(got)) if want[k][0] == got[k][0]
               and md5(want[k][1]) != md5(got[k][1])]
    return missing, wrong, extra, bad_md5


def retree(t, new_tree, write, remove, lib_root=None):
    """Replace an ALREADY STAGED title's game files with `new_tree` (a prepared
    local tree; 8.3 names, uppercased like build() does): write every file
    that is new or differs, remove every library file the new tree does not
    have - except the generator's own (launcher, icon, launch.txt, ...), which
    update() then regenerates. Returns (written, removed) relative paths.

    Why: build() never overwrites a staged title and update() touches only
    generator-owned files, so a title staged from the wrong source (Aces Over
    Europe from the FRENCH zip, 2026-09-30) had no route to the right one.
    GAMESYNC never deletes, so a box keeps a removed file until someone does."""
    lib_dir = os.path.join(lib_root or LIB_MNT, t["lib"])
    if not os.path.isdir(lib_dir):
        raise SystemExit("%s: not staged yet - build it without --update" % t["lib"])
    have = _tree(lib_dir)
    owned = {rel.upper() for rel in generated(t, 0)}
    want, bad = {}, []
    for d, _, fs in os.walk(new_tree):
        for f in fs:
            rel = os.path.relpath(os.path.join(d, f), new_tree).replace(os.sep, "/")
            if not is_83(rel):
                bad.append(rel)
            want[rel.upper()] = os.path.join(d, f)
    if bad:
        raise SystemExit("%s: non-8.3 names in %s: %s" % (t["lib"], new_tree, bad[:8]))
    written, removed = [], []
    for rel, src in sorted(want.items()):
        if rel in owned:
            continue
        data = open(src, "rb").read()
        cur = have.get(rel)
        if cur and cur[0] == len(data) and open(cur[1], "rb").read() == data:
            continue
        write(cur[1] if cur else os.path.join(lib_dir, *rel.split("/")), data)
        written.append(rel)
    for rel, (_sz, path) in sorted(have.items()):
        if rel not in want and rel not in owned:
            remove(path)
            removed.append(rel)
    return written, removed


def run_update(spec, dry_run, new_tree=None):
    """--update: each title's generator-owned files, one verified write at a
    time; the first write that does not land stops the run (libwrite). With
    --retree DIR (one title): its game files are replaced by DIR's first."""
    sys.path.insert(0, os.path.join(REPO, "scripts", "fleet"))
    import libwrite
    if new_tree:
        if len(spec) != 1:
            raise SystemExit("--retree replaces ONE title's files: name it with --only")
        t = spec[0]
        w0, r0 = retree(t, new_tree, lambda p, d: None, lambda p: None)
        print("RETREE %-26s write %d file(s): %s | remove %d: %s" % (
            t["lib"], len(w0), ", ".join(w0[:12]), len(r0), ", ".join(r0[:12])))
        if not dry_run and (w0 or r0):
            w = libwrite.writer_for(LIB_MNT)
            try:
                with w:
                    w1, r1 = retree(t, new_tree, w.write_bytes, w.remove)
                print("RETREED %-25s %d written, %d removed" % (t["lib"], len(w1), len(r1)))
            except libwrite.LibWriteError as e:
                print(libwrite.failure_banner(e, w))
                return 1
    plan = []
    for t in spec:
        if not os.path.isdir(os.path.join(LIB_MNT, t["lib"])):
            print("NEW  %-28s not staged yet - build it without --update" % t["lib"])
            continue
        would = update(t, lambda p, d: None)
        plan.append((t, would))
        print("%-4s %-28s %s" % ("PLAN" if would else "OK", t["lib"],
                                 ", ".join(would) if would else "in line with the spec"))
    todo = [(t, w) for t, w in plan if w]
    if dry_run or not todo:
        return 0
    w = libwrite.writer_for(LIB_MNT)
    try:
        with w:
            for t, _ in todo:
                done = update(t, w.write_bytes)
                print("WROTE %-27s %s" % (t["lib"], ", ".join(done)))
    except libwrite.LibWriteError as e:
        print(libwrite.failure_banner(e, w))
        return 1
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True)
    ap.add_argument("--only", action="append", default=[])
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--update", action="store_true",
                    help="titles already staged: rewrite only the files the generator owns "
                         "(launcher, launch.txt, requires.json, icon, PIF, GAME\\RUN.BAT) where "
                         "they differ from the spec, each through libwrite, verified")
    ap.add_argument("--retree", metavar="DIR",
                    help="with --update and ONE --only title: replace its game files with DIR's "
                         "(new and changed written, files DIR lacks removed from the library)")
    a = ap.parse_args()
    spec = json.load(open(a.spec))
    if a.only:
        spec = [t for t in spec if t["lib"] in a.only]
        missing = sorted(set(a.only) - {t["lib"] for t in spec})
        if missing:
            raise SystemExit("--only names titles the spec does not have: %s" % missing)
    if a.retree and not a.update:
        raise SystemExit("--retree goes with --update")
    if a.update:
        sys.exit(run_update(spec, a.dry_run, a.retree))
    seen = {}
    for t in spec:
        n = icon_file_name(t)
        if n in seen:
            raise SystemExit("%s and %s would both ship %s - Windows 98 would draw one icon "
                             "for both; give one an icon_name" % (seen[n], t["lib"], n))
        seen[n] = t["lib"]
    work = tempfile.mkdtemp(prefix="stage9x-")
    auth = os.path.join(work, "nas.auth")
    ok = True
    try:
        if not a.dry_run:
            kv = os.path.join(REPO, "scripts", "fleet", "keyvault.py")
            user = subprocess.run([sys.executable, kv, "get", "fleet-nas-192-168-1-122-user"],
                                  capture_output=True, text=True).stdout.strip()
            pw = subprocess.run([sys.executable, kv, "get", "fleet-nas-192-168-1-122-password"],
                                capture_output=True, text=True).stdout.strip()
            old = os.umask(0o077)
            with open(auth, "w") as f:
                f.write("username = %s\npassword = %s\n" % (user, pw))
            os.umask(old)
        for t in spec:
            local, mine = build(t, work)
            n = sum(len(fs) for _, _, fs in os.walk(local))
            mb = sum(os.path.getsize(os.path.join(d, f)) for d, _, fs in os.walk(local) for f in fs) / 1e6
            if a.dry_run:
                print("DRY  %-28s %5d files %7.1f MB  %s" % (t["lib"], n, mb, " | ".join(t["launch"])))
                continue
            rc = None
            if os.path.exists(os.path.join(LIB_MNT, t["lib"])):
                # Never overwritten - but checked, so a rerun after an
                # interruption says whether the copy already there is whole.
                print("HAVE %-28s already in the library - verifying, not overwriting" % t["lib"])
            else:
                rc, out = smb(auth, 'prompt OFF; recurse ON; cd "%s"; mkdir "%s"; cd "%s"; lcd "%s"; mput *'
                              % (LIB_SMB, t["lib"], t["lib"], local))
            # /mnt is CIFS with an attribute cache: a directory smbclient has
            # just filled can list EMPTY for seconds (every file of three
            # titles read "missing" on the first run, 2026-09-29). Poll before
            # calling it a failure, as scripts/fleet/sharewrite.py does.
            deadline = time.time() + VERIFY_WAIT_S
            while True:
                missing, wrong, extra, bad = verify(local, t["lib"], mine)
                if not (missing or wrong or bad) or time.time() > deadline:
                    break
                time.sleep(5)
            if missing or wrong or bad:
                ok = False
                print("FAIL %-28s rc=%s missing=%d wrong-size=%d md5-bad=%s %s" %
                      (t["lib"], rc, len(missing), len(wrong), bad[:5], (missing + wrong)[:5]))
            else:
                print("OK   %-28s %5d files %7.1f MB verified through /mnt%s" %
                      (t["lib"], n, mb, " (extra on share: %d)" % len(extra) if extra else ""))
    finally:
        if os.path.exists(auth):
            os.remove(auth)
        shutil.rmtree(work, ignore_errors=True)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
