/* opaque DirectDraw DDI types - enough for winddi.h prototypes (no DDraw yet) */
#ifndef VCR_DDRAWINT_STUB
#define VCR_DDRAWINT_STUB
typedef struct _DD_CALLBACKS DD_CALLBACKS, *PDD_CALLBACKS;
typedef struct _DD_DIRECTDRAW_GLOBAL DD_DIRECTDRAW_GLOBAL, *PDD_DIRECTDRAW_GLOBAL;
typedef struct _DD_HALINFO DD_HALINFO, *PDD_HALINFO;
typedef struct _DD_PALETTECALLBACKS DD_PALETTECALLBACKS, *PDD_PALETTECALLBACKS;
typedef struct _DD_SURFACECALLBACKS DD_SURFACECALLBACKS, *PDD_SURFACECALLBACKS;
typedef struct _DD_SURFACE_LOCAL DD_SURFACE_LOCAL, *PDD_SURFACE_LOCAL;
typedef struct _VIDEOMEMORY VIDEOMEMORY, *LPVIDEOMEMORY;
#endif
