#!/usr/bin/env python3
"""
gen_onboard.py - generate onboard.cmd from onboard.json.

The agent's first-run onboard_thread maps the share and runs onboard.cmd,
passing the mapped drive as %1. This generator turns the declarative game list
in onboard.json into an idempotent Windows batch that:

  - stages the JScript unzip shim,
  - per game: skips if the sentinel already exists, else copies the game's ZIP
    off the share (copy /Y - NOT xcopy, which hangs on NETMAP'd SMB on XP) and
    extracts it with retro_unzip.js,
  - imports the dark 'hacker' XP theme reg if staged, re-parks desktop icons,
  - marks the machine Onboarded via regedit /s (works on 98 + XP; no reg.exe on 98).

Usage:  python3 gen_onboard.py           # writes onboard.cmd next to onboard.json
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def q(s):
    return s.replace("/", "\\")


def main():
    m = json.loads((HERE / "onboard.json").read_text())
    games_dir = q(m["share_games_dir"])
    onboard_dir = q(m["onboard_dir"])
    stage = q(m["stage_dir"])
    unzip = q(m["unzip_js_local"])
    mk = m["marker"]
    theme_reg = q(m["desktop"]["theme_reg"])
    arrange = q(m["desktop"]["arrange_icons_exe"])

    L = []
    a = L.append
    a("@echo off")
    a("REM ==== GENERATED by provisioning/gen_onboard.py - do not edit by hand ====")
    a("REM Run by the agent onboard_thread on first boot:  onboard.cmd <mappedDrive>")
    a("setlocal enableextensions")
    a('set "SHARE=%~1"')
    a('if "%SHARE%"=="" set "SHARE=Z:"')
    a(f'set "GAMES=%SHARE%\\{games_dir}"')
    a(f'set "OB=%SHARE%\\{onboard_dir}"')
    a(f'set "STAGE={stage}"')
    a(f'set "UNZIP={unzip}"')
    a("echo ============================================================")
    a("echo   RETRO AGENT ONBOARDING")
    a("echo   share=%SHARE%")
    a("echo ============================================================")
    a(f'if not exist "{stage}" md "{stage}"')
    a('REM --- stage the unzip shim (idempotent) ---')
    a('if exist "%OB%\\retro_unzip.js" copy /Y "%OB%\\retro_unzip.js" "%UNZIP%" >nul')
    a("")
    a("REM ======================= core games =======================")
    for g in m["games"]:
        a(f'call :game "{g["name"]}" "{g["zip"]}" "{q(g["dest"])}" "{q(g["sentinel"])}"')
    a("")
    a("REM ======================= desktop / theme =======================")
    a(f'if exist "%OB%\\{theme_reg}" (')
    a("  echo [theme] applying dark hacker XP theme")
    a(f'  regedit /s "%OB%\\{theme_reg}"')
    a(") else ( echo [theme] no retro_theme.reg staged - skipping )")
    a(f'if exist "{arrange}" ( echo [icons] parking desktop icons & "{arrange}" )')
    a("REM (wallpaper rotation + icon parking also run every boot via the agent)")
    a("")
    a("REM ======================= mark complete =======================")
    a('set "DONE=%TEMP%\\ob_done.reg"')
    a('> "%DONE%" echo REGEDIT4')
    a('>> "%DONE%" echo.')
    a(f'>> "%DONE%" echo [{mk["root"].replace("HKLM","HKEY_LOCAL_MACHINE")}\\{q(mk["key"])}]')
    a(f'>> "%DONE%" echo "{mk["value"]}"=dword:00000001')
    a('regedit /s "%DONE%"')
    a("echo ONBOARDING COMPLETE")
    a("goto :eof")
    a("")
    a("REM --- :game NAME ZIP DEST SENTINEL ---")
    a(":game")
    a('set "NAME=%~1"')
    a('set "ZIP=%~2"')
    a('set "DST=%~3"')
    a('set "SENT=%~4"')
    a('if exist "%DST%\\%SENT%" ( echo [skip] %NAME% - already installed & goto :eof )')
    a('if not exist "%GAMES%\\%ZIP%" ( echo [MISS] %NAME% - %ZIP% not on share & goto :eof )')
    a("echo [stage] %NAME%")
    a('copy /Y "%GAMES%\\%ZIP%" "%STAGE%\\%ZIP%" >nul')
    a('if not exist "%DST%" md "%DST%"')
    a('cscript //nologo "%UNZIP%" "%STAGE%\\%ZIP%" "%DST%"')
    a('del /q "%STAGE%\\%ZIP%" >nul 2>&1')
    a('if exist "%DST%\\%SENT%" ( echo [ok]   %NAME% ) else ( echo [WARN] %NAME% - sentinel missing after extract )')
    a("goto :eof")

    out = HERE / "onboard.cmd"
    out.write_text("\r\n".join(L) + "\r\n")
    print(f"wrote {out} ({len(m['games'])} games)")


if __name__ == "__main__":
    main()
