#!/usr/bin/env python3
"""
gen_onboard.py - generate the onboarding batch(es) from onboard.json.

The agent's first-run onboard_thread maps the share and runs the generated
batch, passing the mapped drive as %1. Because Win98 runs COMMAND.COM (NOT
cmd.exe) we emit TWO files from the same manifest:

  - onboard.cmd     -- NT/XP dialect (cmd.exe): subroutines (call :label),
                       %~1 args, set /a, goto :eof, etc.
  - onboard_9x.bat  -- Win98 COMMAND.COM dialect: NO call-to-label, NO %~1,
                       NO set /a, NO goto :eof, NO 2>&1; every game inlined
                       with goto-based flow; all labels unique within their
                       first 8 characters (COMMAND.COM only compares 8).

Both:
  - stage the JScript unzip shim,
  - GATE each game on hardware: the agent sets ONB_<FLAG>=1/0 env vars
    (gpu3d/cpufast/ram64/ram128 - see onboard.c) before running the batch;
    a game whose 'requires' flags aren't all met is skipped [HWSKIP] and does
    NOT count as a failure (so e.g. a Pentium-1 + 2D box still finishes
    onboarding, just with no games),
  - per remaining game: skip if the sentinel already exists, else copy the
    ZIP off the share (copy /Y - NOT xcopy, which hangs on NETMAP'd SMB) and
    extract it with retro_unzip.js,
  - stage the wallpaper bundle + re-park icons,
  - mark the machine Onboarded (regedit /s; no reg.exe on 98) unless
    something was missing from the share (then retry next boot).

Usage:  python3 gen_onboard.py    # writes onboard.cmd + onboard_9x.bat
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def q(s):
    return s.replace("/", "\\")


def gate_flags(game):
    """Env-var names the machine must have =1 for this game to install."""
    return ["ONB_" + f.upper() for f in game.get("requires", [])]


# ------------------------------------------------------------------ NT/XP ----
def gen_nt(m):
    games_dir = q(m["share_games_dir"])
    onboard_dir = q(m["onboard_dir"])
    stage = q(m["stage_dir"])
    unzip = q(m["unzip_js_local"])
    mk = m["marker"]
    theme_reg = q(m["desktop"]["theme_reg"])
    arrange = q(m["desktop"]["arrange_icons_exe"])
    root = mk["root"].replace("HKLM", "HKEY_LOCAL_MACHINE")

    L = []
    a = L.append
    a("@echo off")
    a("REM ==== GENERATED by provisioning/gen_onboard.py - do not edit ====")
    a("REM NT/XP (cmd.exe) onboarding.  Run: onboard.cmd <mappedDrive>")
    a("setlocal enableextensions")
    a('set "SHARE=%~1"')
    a('if "%SHARE%"=="" set "SHARE=Z:"')
    a(f'set "GAMES=%SHARE%\\{games_dir}"')
    a(f'set "OB=%SHARE%\\{onboard_dir}"')
    a(f'set "STAGE={stage}"')
    a(f'set "UNZIP={unzip}"')
    a("echo ============================================================")
    a("echo   RETRO AGENT ONBOARDING (NT/XP)")
    a("echo   share=%SHARE%  cpufast=%ONB_CPUFAST% gpu3d=%ONB_GPU3D% "
      "ram64=%ONB_RAM64%")
    a("echo ============================================================")
    a(f'if not exist "{stage}" md "{stage}"')
    a('set "FAILED=0"')
    a('if exist "%OB%\\retro_unzip.js" copy /Y "%OB%\\retro_unzip.js" "%UNZIP%" >nul')
    a("")
    a("REM ======================= core games =======================")
    for g in m["games"]:
        flags = gate_flags(g)
        a('set "OK=1"')
        for fl in flags:
            a(f'if not "%{fl}%"=="1" set "OK=0"')
        req = " ".join(g.get("requires", [])) or "none"
        a(f'call :game "{g["name"]}" "{g["zip"]}" "{q(g["dest"])}" '
          f'"{q(g["sentinel"])}" "%OK%" "{req}"')
    a("")
    a("REM ======================= desktop / theme =======================")
    a(f"REM Theme is owned by the agent's retrowall thread; onboarding no "
      f"longer sets one. (staged {theme_reg} ignored.)")
    a('if not exist "C:\\retro-wall\\rotate_wall.exe" call :stagewall')
    a(f'if exist "{arrange}" ( echo [icons] parking desktop icons & "{arrange}" )')
    a("")
    a("REM ======================= mark complete =======================")
    a('if not "%FAILED%"=="0" goto :incomplete')
    a('set "DONE=%TEMP%\\ob_done.reg"')
    a('> "%DONE%" echo REGEDIT4')
    a('>> "%DONE%" echo.')
    a(f'>> "%DONE%" echo [{root}\\{q(mk["key"])}]')
    a(f'>> "%DONE%" echo "{mk["value"]}"=dword:00000001')
    a('regedit /s "%DONE%"')
    a("echo ONBOARDING COMPLETE")
    a("goto :eof")
    a(":incomplete")
    a('echo ONBOARDING INCOMPLETE - %FAILED% item(s) missing from share; '
      'will retry next boot')
    a("goto :eof")
    a("")
    a(":stagewall")
    a('if not exist "C:\\retro-wall" md "C:\\retro-wall"')
    a('if exist "%OB%\\retro-wall\\%COMPUTERNAME%\\rotate_wall.exe" (')
    a('  echo [wall] staging per-host wallpaper bundle')
    a('  copy /Y "%OB%\\retro-wall\\%COMPUTERNAME%\\*" "C:\\retro-wall\\" >nul')
    a('  goto :eof')
    a(")")
    a('if exist "%OB%\\retro-wall\\_default\\rotate_wall.exe" (')
    a('  echo [wall] staging generic wallpaper bundle')
    a('  copy /Y "%OB%\\retro-wall\\_default\\*" "C:\\retro-wall\\" >nul')
    a(")")
    a("goto :eof")
    a("")
    a("REM --- :game NAME ZIP DEST SENTINEL OKFLAG REQTEXT ---")
    a("REM (NAMEs contain parens, so never echo %NAME% inside a (...) block)")
    a(":game")
    a('set "NAME=%~1"')
    a('set "ZIP=%~2"')
    a('set "DST=%~3"')
    a('set "SENT=%~4"')
    a('set "OK=%~5"')
    a('set "REQ=%~6"')
    a('if not "%OK%"=="1" goto :game_hw')
    a('if exist "%DST%\\%SENT%" goto :game_skip')
    a('if not exist "%GAMES%\\%ZIP%" goto :game_miss')
    a("echo [stage] %NAME%")
    a('copy /Y "%GAMES%\\%ZIP%" "%STAGE%\\%ZIP%" >nul')
    a('if not exist "%DST%" md "%DST%"')
    a('cscript //nologo "%UNZIP%" "%STAGE%\\%ZIP%" "%DST%"')
    a('del /q "%STAGE%\\%ZIP%" >nul 2>&1')
    a('if not exist "%DST%\\%SENT%" goto :game_warn')
    a("echo [ok]   %NAME%")
    a("goto :eof")
    a(":game_hw")
    a("echo [HWSKIP] %NAME% - hardware below requirement (needs %REQ%)")
    a("goto :eof")
    a(":game_skip")
    a("echo [skip] %NAME% - already installed")
    a("goto :eof")
    a(":game_miss")
    a("echo [MISS] %NAME% - %ZIP% not on share")
    a('set /a FAILED+=1')
    a("goto :eof")
    a(":game_warn")
    a("echo [WARN] %NAME% - sentinel missing after extract")
    a('set /a FAILED+=1')
    a("goto :eof")
    return "\r\n".join(L) + "\r\n"


# -------------------------------------------------------------- Win9x/98 ----
def gen_9x(m):
    games_dir = q(m["share_games_dir"])
    onboard_dir = q(m["onboard_dir"])
    stage = q(m["stage_dir"])
    unzip = q(m["unzip_js_local"])
    mk = m["marker"]
    arrange = q(m["desktop"]["arrange_icons_exe"])
    root = mk["root"].replace("HKLM", "HKEY_LOCAL_MACHINE")

    L = []
    a = L.append
    a("@echo off")
    a("REM ==== GENERATED by provisioning/gen_onboard.py - do not edit ====")
    a("REM Windows 98 COMMAND.COM dialect.  Run: onboard_9x.bat <mappedDrive>")
    a("REM No call-to-label / %~ / set /a / goto :eof / 2>&1; labels are")
    a("REM unique within 8 chars (COMMAND.COM only compares the first 8).")
    a('if not "%1"=="" set SHARE=%1')
    a('if "%1"=="" set SHARE=Z:')
    a(f"set GAMES=%SHARE%\\{games_dir}")
    a(f"set OB=%SHARE%\\{onboard_dir}")
    a(f"set STAGE={stage}")
    a(f"set UNZIP={unzip}")
    a("echo ============================================================")
    a("echo   RETRO AGENT ONBOARDING (Win9x)")
    a("echo   share=%SHARE% cpufast=%ONB_CPUFAST% gpu3d=%ONB_GPU3D%")
    a("echo ============================================================")
    a(f'if not exist "{stage}" md "{stage}"')
    a("set FAILEDANY=")
    a('if exist "%OB%\\retro_unzip.js" copy /Y "%OB%\\retro_unzip.js" '
      '"%UNZIP%" >nul')
    a("")
    a("REM ======================= core games =======================")
    for i, g in enumerate(m["games"]):
        name = g["name"]
        zipf = g["zip"]
        dst = q(g["dest"])
        sent = q(g["sentinel"])
        flags = gate_flags(g)
        req = " ".join(g.get("requires", [])) or "none"
        a(f"REM ---- game {i}: {name} (requires: {req}) ----")
        a("set OK=1")
        for fl in flags:
            a(f'if not "%{fl}%"=="1" set OK=0')
        a(f'if "%OK%"=="0" goto sk{i}')
        a(f'if exist "{dst}\\{sent}" goto in{i}')
        a(f'if not exist "%GAMES%\\{zipf}" goto ms{i}')
        a(f"echo [stage] {name}")
        a(f'copy /Y "%GAMES%\\{zipf}" "%STAGE%\\{zipf}" >nul')
        a(f'if not exist "{dst}" md "{dst}"')
        a(f'cscript //nologo "%UNZIP%" "%STAGE%\\{zipf}" "{dst}"')
        a(f'del "%STAGE%\\{zipf}" >nul')
        a(f'if not exist "{dst}\\{sent}" goto wn{i}')
        a(f"echo [ok]   {name}")
        a(f"goto nx{i}")
        a(f":in{i}")
        a(f"echo [skip] {name} - already installed")
        a(f"goto nx{i}")
        a(f":sk{i}")
        a(f"echo [HWSKIP] {name} - hardware below requirement ({req})")
        a(f"goto nx{i}")
        a(f":ms{i}")
        a(f"echo [MISS] {name} - {zipf} not on share")
        a("set FAILEDANY=1")
        a(f"goto nx{i}")
        a(f":wn{i}")
        a(f"echo [WARN] {name} - sentinel missing after extract")
        a("set FAILEDANY=1")
        a(f":nx{i}")
        a("")
    a("REM ======================= wallpaper =======================")
    a('if exist "C:\\retro-wall\\rotate_wall.exe" goto wallok')
    a('if not exist "C:\\retro-wall" md "C:\\retro-wall"')
    a('if exist "%OB%\\retro-wall\\%COMPUTERNAME%\\rotate_wall.exe" goto wallhost')
    a('if exist "%OB%\\retro-wall\\_default\\rotate_wall.exe" goto walldef')
    a("goto wallok")
    a(":wallhost")
    a("echo [wall] staging per-host wallpaper bundle")
    a('copy /Y "%OB%\\retro-wall\\%COMPUTERNAME%\\*" "C:\\retro-wall\\" >nul')
    a("goto wallok")
    a(":walldef")
    a("echo [wall] staging generic wallpaper bundle")
    a('copy /Y "%OB%\\retro-wall\\_default\\*" "C:\\retro-wall\\" >nul')
    a(":wallok")
    a(f'if not exist "{arrange}" goto noicons')
    a("echo [icons] parking desktop icons")
    a(f'"{arrange}"')
    a(":noicons")
    a("")
    a("REM ======================= mark complete =======================")
    a('if "%FAILEDANY%"=="1" goto incomple')
    a("echo REGEDIT4 > C:\\WINDOWS\\TEMP\\ob_done.reg")
    a("echo. >> C:\\WINDOWS\\TEMP\\ob_done.reg")
    a(f"echo [{root}\\{q(mk['key'])}] >> C:\\WINDOWS\\TEMP\\ob_done.reg")
    a(f'echo "{mk["value"]}"=dword:00000001 >> C:\\WINDOWS\\TEMP\\ob_done.reg')
    a("regedit /s C:\\WINDOWS\\TEMP\\ob_done.reg")
    a("del C:\\WINDOWS\\TEMP\\ob_done.reg >nul")
    a("echo ONBOARDING COMPLETE")
    a("goto done")
    a(":incomple")
    a("echo ONBOARDING INCOMPLETE - item(s) missing from share; retry next boot")
    a(":done")
    return "\r\n".join(L) + "\r\n"


def check_9x_labels(text):
    """Guard against the COMMAND.COM 8-char label-collision trap."""
    import re
    labels = re.findall(r'^:(\S+)', text, re.M)
    seen = {}
    for lb in labels:
        k = lb[:8].lower()
        if k in seen and seen[k] != lb:
            raise SystemExit(
                f"gen_onboard: Win9x label collision within 8 chars: "
                f"'{seen[k]}' vs '{lb}' (both '{k}')")
        seen[k] = lb


def main():
    m = json.loads((HERE / "onboard.json").read_text())

    nt = gen_nt(m)
    (HERE / "onboard.cmd").write_text(nt)

    nx = gen_9x(m)
    check_9x_labels(nx)
    (HERE / "onboard_9x.bat").write_text(nx)

    print(f"wrote onboard.cmd + onboard_9x.bat ({len(m['games'])} games, "
          f"gated on {m.get('capabilities')})")


if __name__ == "__main__":
    main()
