@echo off
REM ==== GENERATED by provisioning/gen_onboard.py - do not edit ====
REM NT/XP (cmd.exe) onboarding.  Run: onboard.cmd <mappedDrive>
setlocal enableextensions
set "SHARE=%~1"
if "%SHARE%"=="" set "SHARE=Z:"
set "GAMES=%SHARE%\Games"
set "OB=%SHARE%\Utility\Retro Automation\Onboard"
set "STAGE=C:\RETRO_AGENT\stage"
set "UNZIP=C:\WINDOWS\TEMP\retro_unzip.js"
echo ============================================================
echo   RETRO AGENT ONBOARDING (NT/XP)
echo   share=%SHARE%  cpufast=%ONB_CPUFAST% gpu3d=%ONB_GPU3D% ram64=%ONB_RAM64%
echo ============================================================
if not exist "C:\RETRO_AGENT\stage" md "C:\RETRO_AGENT\stage"
set "FAILED=0"
if exist "%OB%\retro_unzip.js" copy /Y "%OB%\retro_unzip.js" "%UNZIP%" >nul

REM ======================= core games =======================
set "OK=1"
if not "%ONB_CPUFAST%"=="1" set "OK=0"
if not "%ONB_RAM64%"=="1" set "OK=0"
call :game "Counter-Strike 1.6 (BC Romania)" "cs16-bc-romania.zip" "C:\Program Files\Counter-Strike 1.6" "hl.exe" "%OK%" "cpufast ram64"
set "OK=1"
if not "%ONB_GPU3D%"=="1" set "OK=0"
if not "%ONB_CPUFAST%"=="1" set "OK=0"
if not "%ONB_RAM64%"=="1" set "OK=0"
call :game "Unreal Tournament (GOTY / OldUnreal 469)" "unreal-tournament.zip" "C:\UnrealTournament" "System\UnrealTournament.exe" "%OK%" "gpu3d cpufast ram64"
set "OK=1"
if not "%ONB_CPUFAST%"=="1" set "OK=0"
if not "%ONB_RAM64%"=="1" set "OK=0"
call :game "Command and Conquer: Red Alert 2 (fleet build)" "red-alert-2.zip" "C:\Westwood\RA2" "ra2.exe" "%OK%" "cpufast ram64"
set "OK=1"
if not "%ONB_CPUFAST%"=="1" set "OK=0"
call :game "Quake II" "quake2.zip" "C:\Quake2" "quake2.exe" "%OK%" "cpufast"
set "OK=1"
if not "%ONB_GPU3D%"=="1" set "OK=0"
if not "%ONB_CPUFAST%"=="1" set "OK=0"
if not "%ONB_RAM64%"=="1" set "OK=0"
call :game "Quake III Arena" "quake3.zip" "C:\Quake III Arena" "Quake3\quake3.exe" "%OK%" "gpu3d cpufast ram64"

REM ======================= desktop / theme =======================
REM Theme is owned by the agent's retrowall thread; onboarding no longer sets one. (staged retro_theme.reg ignored.)
if not exist "C:\retro-wall\rotate_wall.exe" call :stagewall
if exist "C:\retro-wall\arrange_icons.exe" ( echo [icons] parking desktop icons & "C:\retro-wall\arrange_icons.exe" )

REM ======================= mark complete =======================
if not "%FAILED%"=="0" goto :incomplete
set "DONE=%TEMP%\ob_done.reg"
> "%DONE%" echo REGEDIT4
>> "%DONE%" echo.
>> "%DONE%" echo [HKEY_LOCAL_MACHINE\Software\RetroAgent]
>> "%DONE%" echo "Onboarded"=dword:00000001
regedit /s "%DONE%"
echo ONBOARDING COMPLETE
goto :eof
:incomplete
echo ONBOARDING INCOMPLETE - %FAILED% item(s) missing from share; will retry next boot
goto :eof

:stagewall
if not exist "C:\retro-wall" md "C:\retro-wall"
if exist "%OB%\retro-wall\%COMPUTERNAME%\rotate_wall.exe" (
  echo [wall] staging per-host wallpaper bundle
  copy /Y "%OB%\retro-wall\%COMPUTERNAME%\*" "C:\retro-wall\" >nul
  goto :eof
)
if exist "%OB%\retro-wall\_default\rotate_wall.exe" (
  echo [wall] staging generic wallpaper bundle
  copy /Y "%OB%\retro-wall\_default\*" "C:\retro-wall\" >nul
)
goto :eof

REM --- :game NAME ZIP DEST SENTINEL OKFLAG REQTEXT ---
REM (NAMEs contain parens, so never echo %NAME% inside a (...) block)
:game
set "NAME=%~1"
set "ZIP=%~2"
set "DST=%~3"
set "SENT=%~4"
set "OK=%~5"
set "REQ=%~6"
if not "%OK%"=="1" goto :game_hw
if exist "%DST%\%SENT%" goto :game_skip
if not exist "%GAMES%\%ZIP%" goto :game_miss
echo [stage] %NAME%
copy /Y "%GAMES%\%ZIP%" "%STAGE%\%ZIP%" >nul
if not exist "%DST%" md "%DST%"
cscript //nologo "%UNZIP%" "%STAGE%\%ZIP%" "%DST%"
del /q "%STAGE%\%ZIP%" >nul 2>&1
if not exist "%DST%\%SENT%" goto :game_warn
echo [ok]   %NAME%
goto :eof
:game_hw
echo [HWSKIP] %NAME% - hardware below requirement (needs %REQ%)
goto :eof
:game_skip
echo [skip] %NAME% - already installed
goto :eof
:game_miss
echo [MISS] %NAME% - %ZIP% not on share
set /a FAILED+=1
goto :eof
:game_warn
echo [WARN] %NAME% - sentinel missing after extract
set /a FAILED+=1
goto :eof
