@echo off
REM ==== GENERATED by provisioning/gen_onboard.py - do not edit by hand ====
REM Run by the agent onboard_thread on first boot:  onboard.cmd <mappedDrive>
setlocal enableextensions
set "SHARE=%~1"
if "%SHARE%"=="" set "SHARE=Z:"
set "GAMES=%SHARE%\Games"
set "OB=%SHARE%\Utility\Retro Automation\Onboard"
set "STAGE=C:\RETRO_AGENT\stage"
set "UNZIP=C:\WINDOWS\TEMP\retro_unzip.js"
echo ============================================================
echo   RETRO AGENT ONBOARDING
echo   share=%SHARE%
echo ============================================================
if not exist "C:\RETRO_AGENT\stage" md "C:\RETRO_AGENT\stage"
REM --- stage the unzip shim (idempotent) ---
if exist "%OB%\retro_unzip.js" copy /Y "%OB%\retro_unzip.js" "%UNZIP%" >nul

REM ======================= core games =======================
call :game "Counter-Strike 1.6 (BC Romania)" "cs16-bc-romania.zip" "C:\Program Files\Counter-Strike 1.6" "hl.exe"
call :game "Unreal Tournament (GOTY / OldUnreal 469)" "unreal-tournament.zip" "C:\UnrealTournament" "System\UnrealTournament.exe"
call :game "Command and Conquer: Red Alert 2 (fleet build)" "red-alert-2.zip" "C:\Westwood\RA2" "ra2.exe"
call :game "Quake II" "quake2.zip" "C:\Quake2" "quake2.exe"
call :game "Quake III Arena" "quake3.zip" "C:\Quake III Arena" "Quake3\quake3.exe"

REM ======================= desktop / theme =======================
if exist "%OB%\retro_theme.reg" (
  echo [theme] applying dark hacker XP theme
  regedit /s "%OB%\retro_theme.reg"
) else ( echo [theme] no retro_theme.reg staged - skipping )
if exist "C:\retro-wall\arrange_icons.exe" ( echo [icons] parking desktop icons & "C:\retro-wall\arrange_icons.exe" )
REM (wallpaper rotation + icon parking also run every boot via the agent)

REM ======================= mark complete =======================
set "DONE=%TEMP%\ob_done.reg"
> "%DONE%" echo REGEDIT4
>> "%DONE%" echo.
>> "%DONE%" echo [HKEY_LOCAL_MACHINE\Software\RetroAgent]
>> "%DONE%" echo "Onboarded"=dword:00000001
regedit /s "%DONE%"
echo ONBOARDING COMPLETE
goto :eof

REM --- :game NAME ZIP DEST SENTINEL ---
:game
set "NAME=%~1"
set "ZIP=%~2"
set "DST=%~3"
set "SENT=%~4"
if exist "%DST%\%SENT%" ( echo [skip] %NAME% - already installed & goto :eof )
if not exist "%GAMES%\%ZIP%" ( echo [MISS] %NAME% - %ZIP% not on share & goto :eof )
echo [stage] %NAME%
copy /Y "%GAMES%\%ZIP%" "%STAGE%\%ZIP%" >nul
if not exist "%DST%" md "%DST%"
cscript //nologo "%UNZIP%" "%STAGE%\%ZIP%" "%DST%"
del /q "%STAGE%\%ZIP%" >nul 2>&1
if exist "%DST%\%SENT%" ( echo [ok]   %NAME% ) else ( echo [WARN] %NAME% - sentinel missing after extract )
goto :eof
