@echo off
REM ==== GENERATED by provisioning/gen_onboard.py - do not edit by hand ====
REM Run by the agent onboard_thread on first boot:  onboard.cmd <mappedDrive>
setlocal enableextensions
set "SHARE=%~1"
if "%SHARE%"=="" set "SHARE=Z:"
set "GAMES=%SHARE%\Games"
set "OB=%SHARE%\Utility\Retro Automation\Onboard"
set "STAGE=C:\RETRO_AGENT\stage"
set "UNZIP=C:\WINDOWS\TEMP\retro_unzip.js"
echo ============================================================
echo   RETRO AGENT ONBOARDING
echo   share=%SHARE%
echo ============================================================
if not exist "C:\RETRO_AGENT\stage" md "C:\RETRO_AGENT\stage"
REM FAILED counts games missing-from-share or failed-to-extract. If any,
REM we do NOT set the Onboarded marker, so a later boot retries once the
REM share is complete (fixes: a box that got only the theme being marked
REM fully onboarded and never installing the games).
set "FAILED=0"
REM --- stage the unzip shim (idempotent) ---
if exist "%OB%\retro_unzip.js" copy /Y "%OB%\retro_unzip.js" "%UNZIP%" >nul

REM ======================= core games =======================
call :game "Counter-Strike 1.6 (BC Romania)" "cs16-bc-romania.zip" "C:\Program Files\Counter-Strike 1.6" "hl.exe"
call :game "Unreal Tournament (GOTY / OldUnreal 469)" "unreal-tournament.zip" "C:\UnrealTournament" "System\UnrealTournament.exe"
call :game "Command and Conquer: Red Alert 2 (fleet build)" "red-alert-2.zip" "C:\Westwood\RA2" "ra2.exe"
call :game "Quake II" "quake2.zip" "C:\Quake2" "quake2.exe"
call :game "Quake III Arena" "quake3.zip" "C:\Quake III Arena" "Quake3\quake3.exe"

REM ======================= desktop / theme =======================
REM Theme is owned by the agent's retrowall thread (applies the Windows
REM Classic theme on every startup) - onboarding no longer sets a theme,
REM so it can't fight the agent. (staged retro_theme.reg is now ignored.)

REM --- stage wallpaper rotation bundle from the share if present and the
REM     box has none yet (per-host first, then a generic _default set), so
REM     the agent's retrowall thread has assets to apply every boot. flat
REM     copy /Y (NOT xcopy - hangs on NETMAP'd SMB on XP). ---
if not exist "C:\retro-wall\rotate_wall.exe" call :stagewall
if exist "C:\retro-wall\arrange_icons.exe" ( echo [icons] parking desktop icons & "C:\retro-wall\arrange_icons.exe" )
REM (wallpaper rotation + icon parking also run every boot via the agent)

REM ======================= mark complete =======================
if not "%FAILED%"=="0" goto :incomplete
set "DONE=%TEMP%\ob_done.reg"
> "%DONE%" echo REGEDIT4
>> "%DONE%" echo.
>> "%DONE%" echo [HKEY_LOCAL_MACHINE\Software\RetroAgent]
>> "%DONE%" echo "Onboarded"=dword:00000001
regedit /s "%DONE%"
echo ONBOARDING COMPLETE
goto :eof
:incomplete
echo ONBOARDING INCOMPLETE - %FAILED% item(s) missing from share; not marking Onboarded, will retry on next boot
goto :eof

REM --- :stagewall - copy the wallpaper/theme bundle off the share ---
:stagewall
if not exist "C:\retro-wall" md "C:\retro-wall"
if exist "%OB%\retro-wall\%COMPUTERNAME%\rotate_wall.exe" (
  echo [wall] staging per-host wallpaper bundle
  copy /Y "%OB%\retro-wall\%COMPUTERNAME%\*" "C:\retro-wall\" >nul
  goto :eof
)
if exist "%OB%\retro-wall\_default\rotate_wall.exe" (
  echo [wall] staging generic wallpaper bundle
  copy /Y "%OB%\retro-wall\_default\*" "C:\retro-wall\" >nul
)
goto :eof

REM --- :game NAME ZIP DEST SENTINEL ---
REM NOTE: game NAMEs contain parentheses (e.g. "(BC Romania)"), so this
REM       routine must NOT echo %NAME% inside a ( ... ) block - the ')' in
REM       the expanded name closes the block early ("- was unexpected at
REM       this time."). Use goto-based flow with plain-line echoes instead.
:game
set "NAME=%~1"
set "ZIP=%~2"
set "DST=%~3"
set "SENT=%~4"
if exist "%DST%\%SENT%" goto :game_skip
if not exist "%GAMES%\%ZIP%" goto :game_miss
echo [stage] %NAME%
copy /Y "%GAMES%\%ZIP%" "%STAGE%\%ZIP%" >nul
if not exist "%DST%" md "%DST%"
cscript //nologo "%UNZIP%" "%STAGE%\%ZIP%" "%DST%"
del /q "%STAGE%\%ZIP%" >nul 2>&1
if not exist "%DST%\%SENT%" goto :game_warn
echo [ok]   %NAME%
goto :eof
:game_skip
echo [skip] %NAME% - already installed
goto :eof
:game_miss
echo [MISS] %NAME% - %ZIP% not on share
set /a FAILED+=1
goto :eof
:game_warn
echo [WARN] %NAME% - sentinel missing after extract
set /a FAILED+=1
goto :eof
