@echo off
REM ==== GENERATED by provisioning/gen_onboard.py - do not edit ====
REM Windows 98 COMMAND.COM dialect.  Run: onboard_9x.bat <mappedDrive>
REM No call-to-label / %~ / set /a / goto :eof / 2>&1; labels are
REM unique within 8 chars (COMMAND.COM only compares the first 8).
if not "%1"=="" set SHARE=%1
if "%1"=="" set SHARE=Z:
set GAMES=%SHARE%\Games
set OB=%SHARE%\Utility\Retro Automation\Onboard
set STAGE=C:\RETRO_AGENT\stage
set UNZIP=C:\WINDOWS\TEMP\retro_unzip.js
echo ============================================================
echo   RETRO AGENT ONBOARDING (Win9x)
echo   share=%SHARE% cpufast=%ONB_CPUFAST% gpu3d=%ONB_GPU3D%
echo ============================================================
if not exist "C:\RETRO_AGENT\stage" md "C:\RETRO_AGENT\stage"
set FAILEDANY=
if exist "%OB%\retro_unzip.js" copy /Y "%OB%\retro_unzip.js" "%UNZIP%" >nul

REM ======================= core games =======================
REM ---- game 0: Counter-Strike 1.6 (BC Romania) (requires: cpufast ram64) ----
set OK=1
if not "%ONB_CPUFAST%"=="1" set OK=0
if not "%ONB_RAM64%"=="1" set OK=0
if "%OK%"=="0" goto sk0
if exist "C:\Program Files\Counter-Strike 1.6\hl.exe" goto in0
if not exist "%GAMES%\cs16-bc-romania.zip" goto ms0
echo [stage] Counter-Strike 1.6 (BC Romania)
copy /Y "%GAMES%\cs16-bc-romania.zip" "%STAGE%\cs16-bc-romania.zip" >nul
if not exist "C:\Program Files\Counter-Strike 1.6" md "C:\Program Files\Counter-Strike 1.6"
cscript //nologo "%UNZIP%" "%STAGE%\cs16-bc-romania.zip" "C:\Program Files\Counter-Strike 1.6"
del "%STAGE%\cs16-bc-romania.zip" >nul
if not exist "C:\Program Files\Counter-Strike 1.6\hl.exe" goto wn0
echo [ok]   Counter-Strike 1.6 (BC Romania)
goto nx0
:in0
echo [skip] Counter-Strike 1.6 (BC Romania) - already installed
goto nx0
:sk0
echo [HWSKIP] Counter-Strike 1.6 (BC Romania) - hardware below requirement (cpufast ram64)
goto nx0
:ms0
echo [MISS] Counter-Strike 1.6 (BC Romania) - cs16-bc-romania.zip not on share
set FAILEDANY=1
goto nx0
:wn0
echo [WARN] Counter-Strike 1.6 (BC Romania) - sentinel missing after extract
set FAILEDANY=1
:nx0

REM ---- game 1: Unreal Tournament (GOTY / OldUnreal 469) (requires: gpu3d cpufast ram64) ----
set OK=1
if not "%ONB_GPU3D%"=="1" set OK=0
if not "%ONB_CPUFAST%"=="1" set OK=0
if not "%ONB_RAM64%"=="1" set OK=0
if "%OK%"=="0" goto sk1
if exist "C:\UnrealTournament\System\UnrealTournament.exe" goto in1
if not exist "%GAMES%\unreal-tournament.zip" goto ms1
echo [stage] Unreal Tournament (GOTY / OldUnreal 469)
copy /Y "%GAMES%\unreal-tournament.zip" "%STAGE%\unreal-tournament.zip" >nul
if not exist "C:\UnrealTournament" md "C:\UnrealTournament"
cscript //nologo "%UNZIP%" "%STAGE%\unreal-tournament.zip" "C:\UnrealTournament"
del "%STAGE%\unreal-tournament.zip" >nul
if not exist "C:\UnrealTournament\System\UnrealTournament.exe" goto wn1
echo [ok]   Unreal Tournament (GOTY / OldUnreal 469)
goto nx1
:in1
echo [skip] Unreal Tournament (GOTY / OldUnreal 469) - already installed
goto nx1
:sk1
echo [HWSKIP] Unreal Tournament (GOTY / OldUnreal 469) - hardware below requirement (gpu3d cpufast ram64)
goto nx1
:ms1
echo [MISS] Unreal Tournament (GOTY / OldUnreal 469) - unreal-tournament.zip not on share
set FAILEDANY=1
goto nx1
:wn1
echo [WARN] Unreal Tournament (GOTY / OldUnreal 469) - sentinel missing after extract
set FAILEDANY=1
:nx1

REM ---- game 2: Command and Conquer: Red Alert 2 (fleet build) (requires: cpufast ram64) ----
set OK=1
if not "%ONB_CPUFAST%"=="1" set OK=0
if not "%ONB_RAM64%"=="1" set OK=0
if "%OK%"=="0" goto sk2
if exist "C:\Westwood\RA2\ra2.exe" goto in2
if not exist "%GAMES%\red-alert-2.zip" goto ms2
echo [stage] Command and Conquer: Red Alert 2 (fleet build)
copy /Y "%GAMES%\red-alert-2.zip" "%STAGE%\red-alert-2.zip" >nul
if not exist "C:\Westwood\RA2" md "C:\Westwood\RA2"
cscript //nologo "%UNZIP%" "%STAGE%\red-alert-2.zip" "C:\Westwood\RA2"
del "%STAGE%\red-alert-2.zip" >nul
if not exist "C:\Westwood\RA2\ra2.exe" goto wn2
echo [ok]   Command and Conquer: Red Alert 2 (fleet build)
goto nx2
:in2
echo [skip] Command and Conquer: Red Alert 2 (fleet build) - already installed
goto nx2
:sk2
echo [HWSKIP] Command and Conquer: Red Alert 2 (fleet build) - hardware below requirement (cpufast ram64)
goto nx2
:ms2
echo [MISS] Command and Conquer: Red Alert 2 (fleet build) - red-alert-2.zip not on share
set FAILEDANY=1
goto nx2
:wn2
echo [WARN] Command and Conquer: Red Alert 2 (fleet build) - sentinel missing after extract
set FAILEDANY=1
:nx2

REM ---- game 3: Quake II (requires: cpufast) ----
set OK=1
if not "%ONB_CPUFAST%"=="1" set OK=0
if "%OK%"=="0" goto sk3
if exist "C:\Quake2\quake2.exe" goto in3
if not exist "%GAMES%\quake2.zip" goto ms3
echo [stage] Quake II
copy /Y "%GAMES%\quake2.zip" "%STAGE%\quake2.zip" >nul
if not exist "C:\Quake2" md "C:\Quake2"
cscript //nologo "%UNZIP%" "%STAGE%\quake2.zip" "C:\Quake2"
del "%STAGE%\quake2.zip" >nul
if not exist "C:\Quake2\quake2.exe" goto wn3
echo [ok]   Quake II
goto nx3
:in3
echo [skip] Quake II - already installed
goto nx3
:sk3
echo [HWSKIP] Quake II - hardware below requirement (cpufast)
goto nx3
:ms3
echo [MISS] Quake II - quake2.zip not on share
set FAILEDANY=1
goto nx3
:wn3
echo [WARN] Quake II - sentinel missing after extract
set FAILEDANY=1
:nx3

REM ---- game 4: Quake III Arena (requires: gpu3d cpufast ram64) ----
set OK=1
if not "%ONB_GPU3D%"=="1" set OK=0
if not "%ONB_CPUFAST%"=="1" set OK=0
if not "%ONB_RAM64%"=="1" set OK=0
if "%OK%"=="0" goto sk4
if exist "C:\Quake III Arena\Quake3\quake3.exe" goto in4
if not exist "%GAMES%\quake3.zip" goto ms4
echo [stage] Quake III Arena
copy /Y "%GAMES%\quake3.zip" "%STAGE%\quake3.zip" >nul
if not exist "C:\Quake III Arena" md "C:\Quake III Arena"
cscript //nologo "%UNZIP%" "%STAGE%\quake3.zip" "C:\Quake III Arena"
del "%STAGE%\quake3.zip" >nul
if not exist "C:\Quake III Arena\Quake3\quake3.exe" goto wn4
echo [ok]   Quake III Arena
goto nx4
:in4
echo [skip] Quake III Arena - already installed
goto nx4
:sk4
echo [HWSKIP] Quake III Arena - hardware below requirement (gpu3d cpufast ram64)
goto nx4
:ms4
echo [MISS] Quake III Arena - quake3.zip not on share
set FAILEDANY=1
goto nx4
:wn4
echo [WARN] Quake III Arena - sentinel missing after extract
set FAILEDANY=1
:nx4

REM ======================= wallpaper =======================
if exist "C:\retro-wall\rotate_wall.exe" goto wallok
if not exist "C:\retro-wall" md "C:\retro-wall"
if exist "%OB%\retro-wall\%COMPUTERNAME%\rotate_wall.exe" goto wallhost
if exist "%OB%\retro-wall\_default\rotate_wall.exe" goto walldef
goto wallok
:wallhost
echo [wall] staging per-host wallpaper bundle
copy /Y "%OB%\retro-wall\%COMPUTERNAME%\*" "C:\retro-wall\" >nul
goto wallok
:walldef
echo [wall] staging generic wallpaper bundle
copy /Y "%OB%\retro-wall\_default\*" "C:\retro-wall\" >nul
:wallok
if not exist "C:\retro-wall\arrange_icons.exe" goto noicons
echo [icons] parking desktop icons
"C:\retro-wall\arrange_icons.exe"
:noicons

REM ======================= mark complete =======================
if "%FAILEDANY%"=="1" goto incomple
echo REGEDIT4 > C:\WINDOWS\TEMP\ob_done.reg
echo. >> C:\WINDOWS\TEMP\ob_done.reg
echo [HKEY_LOCAL_MACHINE\Software\RetroAgent] >> C:\WINDOWS\TEMP\ob_done.reg
echo "Onboarded"=dword:00000001 >> C:\WINDOWS\TEMP\ob_done.reg
regedit /s C:\WINDOWS\TEMP\ob_done.reg
del C:\WINDOWS\TEMP\ob_done.reg >nul
echo ONBOARDING COMPLETE
goto done
:incomple
echo ONBOARDING INCOMPLETE - item(s) missing from share; retry next boot
:done
