#!/usr/bin/env python3
"""Generate GameBots/Classes/GBSchema.uc from schema.py.

The UnrealScript equivalent of ../gamebots_schema.h: OBS_DIM, SCHEMA_HASH and
every field offset are derived from schema.py, never hand-copied, for exactly
the reason the C header is generated -- two hand-written copies of a field
table drift, and here the failure mode is worse than a compile error: the
floats still unpack, they just mean something else, and the bot walks into a
wall for reasons nobody can see.

**Why static FUNCTIONS, not `const`.** The first version of this generator
emitted plain `const NAME = value;` declarations, called from GBMutator.uc as
bare `GBSchema.NAME`. That compiles in some positions (a lone array subscript)
and fails in others ("Bad or missing expression") with no discoverable
pattern -- reproduced across `const`s of every type this schema needs (int
offsets, an unsuffixed bit-flag, even a plain loop bound identical in shape to
ones that DID compile two lines away) on this OldUnreal 469e `ucc`. A static
function call, `class'GBSchema'.static.Name()`, hit none of those failures in
every position tried, presumably because it goes through the same call
machinery as any other cross-class call (`VSize()`, `FClamp()`, ...) rather
than whatever code path resolves a bare cross-class const. So every value
below is a zero-argument static function instead, named identically to the
old const so the call-site change is mechanical: `GBSchema.X` ->
`class'GBSchema'.static.X()`.

UnrealScript has no #include, so this is a small standalone .uc file
GBMutator.uc calls into. Run this before `ucc make` -- build.sh does it
automatically, and a test (test_gamebots_ut99.py) regenerates and diffs it so
a schema change that forgets this file fails the suite instead of shipping a
silently stale adapter.

Usage:
    python3 gen_gbschema.py > GameBots/Classes/GBSchema.uc
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
import schema  # noqa: E402


def _off_of(name):
    for _g, fname, off, _count, _doc in schema.FIELD_TABLE:
        if fname == name:
            return off
    raise KeyError(name)


def _fn(name, value, ret="int", doc=""):
    suffix = f"  // {doc}" if doc else ""
    return f"static final function {ret} {name}() {{ return {value}; }}{suffix}"


def emit():
    L = []
    a = L.append
    a("//=============================================================================")
    a("// GBSchema -- GENERATED by ../gen_gbschema.py from scripts/gamebots/schema.py.")
    a("//")
    a("// Do not edit by hand. Regenerate with:")
    a("//     python3 gen_gbschema.py > GameBots/Classes/GBSchema.uc")
    a("//")
    a("// Every value is a static function (`class'GBSchema'.static.Name()`), NOT a")
    a("// `const` -- see this generator's module docstring for why a bare cross-class")
    a("// const proved unreliable on this compiler and a function call did not.")
    a("//")
    a("// The schema hash goes out in every request; the policy server refuses a")
    a("// mismatch and names the fix. An adapter built against a stale copy of this")
    a("// file is otherwise undetectable -- the floats still unpack, they just mean")
    a("// something else.")
    a("//=============================================================================")
    a("class GBSchema extends Object;")
    a("")
    a(_fn("SCHEMA_VERSION", schema.SCHEMA_VERSION))
    a(_fn("SCHEMA_HASH", schema.SCHEMA_HASH,
          doc=f"0x{schema.SCHEMA_HASH:08x}, < 2^31 so it fits a signed int"))
    a(_fn("OBS_DIM", schema.OBS_DIM))
    a(_fn("MAX_ENTITIES", schema.MAX_ENTITIES))
    a(_fn("NUM_RAYS_H", schema.NUM_RAYS_H))
    a(_fn("INTENT_DIM", schema.INTENT_DIM))
    a("")
    a("// wire sizes (bytes) -- see schema.py HEADER_STRUCT / OBS_ENTRY_STRUCT / ACTION_STRUCT")
    a(_fn("HEADER_SIZE", schema.HEADER_SIZE))
    a(_fn("OBS_ENTRY_SIZE", schema.OBS_ENTRY_SIZE))
    a(_fn("ACTION_SIZE", schema.ACTION_SIZE))
    a("")
    a("// magic, as bytes (UnrealScript has no byte-string literal)")
    for i, ch in enumerate(schema.REQ_MAGIC):
        a(_fn(f"REQ_MAGIC_{i}", ch, doc=f"'{chr(ch)}'"))
    for i, ch in enumerate(schema.RESP_MAGIC):
        a(_fn(f"RESP_MAGIC_{i}", ch, doc=f"'{chr(ch)}'"))
    a("")
    a("// --- buttons ---")
    for i, name in enumerate(schema.BUTTON_NAMES):
        a(_fn(f"BTN_{name.upper()}", 1 << i))
    a("")
    a("// --- request flags ---")
    a(_fn("FLAG_NONE", schema.FLAG_NONE))
    a(_fn("FLAG_TRAINING", schema.FLAG_TRAINING))
    a(_fn("FLAG_PAUSED", schema.FLAG_PAUSED))
    a("")
    a("// --- action bounds (enforce on the server, never trust the policy) ---")
    a(_fn("MAX_PITCH_DELTA_DEG", schema.MAX_PITCH_DELTA_DEG, ret="float"))
    a(_fn("MAX_YAW_DELTA_DEG", schema.MAX_YAW_DELTA_DEG, ret="float"))
    a("")
    a("// --- entity slots: base = OBS_E0_PRESENT() + i * ENT_SLOT_STRIDE() ---")
    ent0 = _off_of("e0_present")
    stride = _off_of("e1_present") - ent0 if schema.MAX_ENTITIES > 1 else 0
    a(_fn("ENT_SLOT_STRIDE", stride))
    for sub, macro in (("present", "PRESENT"), ("is_teammate", "TEAMMATE"),
                       ("dir", "DIR"), ("dist_norm", "DIST"),
                       ("rel_vel", "RELVEL"), ("health_frac", "HEALTH"),
                       ("visible", "VISIBLE")):
        a(_fn(f"ENT_{macro}", _off_of("e0_" + sub) - ent0))
    a("")
    a("// --- observation field offsets ---")
    group = None
    for g, name, off, count, doc in schema.FIELD_TABLE:
        if g != group:
            a(f"// {g}")
            group = g
        a(_fn(f"OBS_{name.upper()}", off, doc=f"x{count}: {doc}"))
    a("")
    a("defaultproperties")
    a("{")
    a("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    sys.stdout.write(emit())
