/* gamebots_schema.h — GENERATED by scripts/gamebots/schema.py.
 *
 * Do not edit. Regenerate with:
 *     python3 scripts/gamebots/schema.py --emit-header \
 *         > scripts/gamebots/gamebots_schema.h
 *
 * Engine adapters compile against this. The schema hash below goes out
 * in every request and the policy server refuses a mismatch, so an
 * adapter built against a stale header fails loudly at the first tick
 * instead of quietly feeding the policy misaligned floats.
 */
#ifndef GAMEBOTS_SCHEMA_H
#define GAMEBOTS_SCHEMA_H

#include <stdint.h>

#define GB_SCHEMA_VERSION 1
#define GB_SCHEMA_HASH    0x468be61bu
#define GB_OBS_DIM        144
#define GB_MAX_ENTITIES   8
#define GB_NUM_RAYS_H     16
#define GB_INTENT_DIM     16

#define GB_REQ_MAGIC  "GBQ1"
#define GB_RESP_MAGIC "GBA1"

/* --- buttons --- */
#define GB_BTN_ATTACK   (1u << 0)
#define GB_BTN_ATTACK2  (1u << 1)
#define GB_BTN_JUMP     (1u << 2)
#define GB_BTN_CROUCH   (1u << 3)
#define GB_BTN_RELOAD   (1u << 4)
#define GB_BTN_USE      (1u << 5)
#define GB_BTN_WALK     (1u << 6)
#define GB_BTN_ZOOM     (1u << 7)

/* --- request flags --- */
#define GB_FLAG_NONE     0u
#define GB_FLAG_TRAINING (1u << 0)
#define GB_FLAG_PAUSED   (1u << 1)

/* --- action bounds (enforce on the server, never trust the policy) --- */
#define GB_MAX_PITCH_DELTA_DEG 25.0f
#define GB_MAX_YAW_DELTA_DEG   40.0f

/* --- entity slots ---
 * Every slot has the same shape, so an adapter walks them as
 *     base = GB_OBS_E0_PRESENT + i * GB_ENT_SLOT_STRIDE;
 *     obs[base + GB_ENT_DIST] = ...;
 * These are RELATIVE to a slot's start and are derived from the field
 * table, never hand-counted -- writing `base + 7` is how the Python
 * side once read `visible` out of the middle of rel_vel.
 */
#define GB_ENT_SLOT_STRIDE             10
#define GB_ENT_PRESENT                  0
#define GB_ENT_TEAMMATE                 1
#define GB_ENT_DIR                      2
#define GB_ENT_DIST                     5
#define GB_ENT_RELVEL                   6
#define GB_ENT_HEALTH                   8
#define GB_ENT_VISIBLE                  9

/* --- observation field offsets --- */
/* self */
#define GB_OBS_HEALTH_FRAC              0  /* x1: health / max health, 0..1 */
#define GB_OBS_ARMOR_FRAC               1  /* x1: armour / max armour, 0..1 */
#define GB_OBS_AMMO_FRAC                2  /* x1: ammo in clip / clip size, 0..1 */
#define GB_OBS_AMMO_RESERVE_FRAC        3  /* x1: reserve ammo, 0..1 */
#define GB_OBS_WEAPON_ID_NORM           4  /* x1: weapon index / max weapon index */
#define GB_OBS_VEL_LOCAL                5  /* x3: velocity in the bot's own frame (fwd,right,up), / max speed */
#define GB_OBS_SPEED_FRAC               8  /* x1: |velocity| / max ground speed */
#define GB_OBS_PITCH_NORM               9  /* x1: view pitch / 90deg, -1..1 */
#define GB_OBS_ON_GROUND               10  /* x1: 1 if standing on something */
#define GB_OBS_CROUCHING               11  /* x1: 1 if ducked */
#define GB_OBS_IN_WATER                12  /* x1: 1 if submerged */
#define GB_OBS_RELOADING               13  /* x1: 1 if mid-reload */
#define GB_OBS_ALIVE                   14  /* x1: 1 if alive (0 during respawn wait) */
/* geom */
#define GB_OBS_RAY_H                   15  /* x16: 16 horizontal raycast distances / far plane, starting straight ahead and going clockwise */
#define GB_OBS_RAY_UP                  31  /* x1: distance to ceiling / far plane */
#define GB_OBS_RAY_DOWN                32  /* x1: distance to floor / far plane (step/ledge sensing) */
/* ent */
#define GB_OBS_E0_PRESENT              33  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E0_IS_TEAMMATE          34  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E0_DIR                  35  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E0_DIST_NORM            38  /* x1: distance / far plane */
#define GB_OBS_E0_REL_VEL              39  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E0_HEALTH_FRAC          41  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E0_VISIBLE              42  /* x1: 1 if we currently have line of sight */
#define GB_OBS_E1_PRESENT              43  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E1_IS_TEAMMATE          44  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E1_DIR                  45  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E1_DIST_NORM            48  /* x1: distance / far plane */
#define GB_OBS_E1_REL_VEL              49  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E1_HEALTH_FRAC          51  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E1_VISIBLE              52  /* x1: 1 if we currently have line of sight */
#define GB_OBS_E2_PRESENT              53  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E2_IS_TEAMMATE          54  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E2_DIR                  55  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E2_DIST_NORM            58  /* x1: distance / far plane */
#define GB_OBS_E2_REL_VEL              59  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E2_HEALTH_FRAC          61  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E2_VISIBLE              62  /* x1: 1 if we currently have line of sight */
#define GB_OBS_E3_PRESENT              63  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E3_IS_TEAMMATE          64  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E3_DIR                  65  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E3_DIST_NORM            68  /* x1: distance / far plane */
#define GB_OBS_E3_REL_VEL              69  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E3_HEALTH_FRAC          71  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E3_VISIBLE              72  /* x1: 1 if we currently have line of sight */
#define GB_OBS_E4_PRESENT              73  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E4_IS_TEAMMATE          74  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E4_DIR                  75  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E4_DIST_NORM            78  /* x1: distance / far plane */
#define GB_OBS_E4_REL_VEL              79  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E4_HEALTH_FRAC          81  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E4_VISIBLE              82  /* x1: 1 if we currently have line of sight */
#define GB_OBS_E5_PRESENT              83  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E5_IS_TEAMMATE          84  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E5_DIR                  85  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E5_DIST_NORM            88  /* x1: distance / far plane */
#define GB_OBS_E5_REL_VEL              89  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E5_HEALTH_FRAC          91  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E5_VISIBLE              92  /* x1: 1 if we currently have line of sight */
#define GB_OBS_E6_PRESENT              93  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E6_IS_TEAMMATE          94  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E6_DIR                  95  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E6_DIST_NORM            98  /* x1: distance / far plane */
#define GB_OBS_E6_REL_VEL              99  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E6_HEALTH_FRAC         101  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E6_VISIBLE             102  /* x1: 1 if we currently have line of sight */
#define GB_OBS_E7_PRESENT             103  /* x1: 1 if this slot holds an entity */
#define GB_OBS_E7_IS_TEAMMATE         104  /* x1: 1 teammate, 0 enemy/neutral */
#define GB_OBS_E7_DIR                 105  /* x3: unit vector to it in the bot's frame */
#define GB_OBS_E7_DIST_NORM           108  /* x1: distance / far plane */
#define GB_OBS_E7_REL_VEL             109  /* x2: its velocity relative to us (fwd,right) / max speed */
#define GB_OBS_E7_HEALTH_FRAC         111  /* x1: its health 0..1 (0 if unknown) */
#define GB_OBS_E7_VISIBLE             112  /* x1: 1 if we currently have line of sight */
/* event */
#define GB_OBS_TOOK_DAMAGE            113  /* x1: damage taken last tick / max health */
#define GB_OBS_DAMAGE_DIR             114  /* x2: unit direction the damage came from (fwd,right) */
#define GB_OBS_KILLED_SOMEONE         116  /* x1: 1 if we got a kill last tick */
#define GB_OBS_DIED                   117  /* x1: 1 if we died last tick */
/* game */
#define GB_OBS_ROUND_TIME_FRAC        118  /* x1: elapsed / round length, 0..1 */
#define GB_OBS_SCORE_DIFF_NORM        119  /* x1: (our score - theirs) / fraglimit, clamped -1..1 */
#define GB_OBS_TEAMMATES_ALIVE_FRAC   120  /* x1: alive teammates / team size */
#define GB_OBS_ENEMIES_ALIVE_FRAC     121  /* x1: alive enemies / team size */
#define GB_OBS_OBJECTIVE              122  /* x2: mode-specific (bomb planted, flag carried, ...) */
/* intent */
#define GB_OBS_INTENT                 124  /* x16: intent vector from the LLM planner (all zeros = no plan) */
#define GB_OBS_PAD                    140  /* x4: alignment padding, always zero */

#pragma pack(push, 1)
typedef struct {
    char     magic[4];
    uint32_t schema_hash;
    uint16_t n_bots;
    uint16_t flags;
    uint32_t tick;
} gb_header_t;

typedef struct {
    uint16_t bot_id;
    uint16_t pad;
    float    obs[GB_OBS_DIM];
} gb_obs_entry_t;

typedef struct {
    uint16_t bot_id;
    uint16_t buttons;
    float    pitch_delta;   /* degrees, clamped */
    float    yaw_delta;     /* degrees, clamped */
    float    forward;       /* -1..1 */
    float    side;          /* -1..1 */
    uint8_t  weapon;        /* 0 = no change */
    uint8_t  pad0;
    uint16_t reserved;
} gb_action_t;
#pragma pack(pop)

/* sanity: these must match the Python side exactly */
typedef char gb_static_assert_header[(sizeof(gb_header_t) == 16) ? 1 : -1];
typedef char gb_static_assert_obs[(sizeof(gb_obs_entry_t) == 580) ? 1 : -1];
typedef char gb_static_assert_action[(sizeof(gb_action_t) == 24) ? 1 : -1];

#endif /* GAMEBOTS_SCHEMA_H */
