#!/usr/bin/env python3
"""sli_shot.py - does every chip draw its share? Quake II photographs itself.

In SLI each VSA-100 renders only its own bands of scanlines, and Glide's LFB
read (what Quake II's `screenshot` uses, via glReadPixels) gathers the bands
back from the chip that owns each one (cfgSliLfbCtrl READ_EN). So an engine
screenshot taken under N-chip SLI shows, band by band, what every chip drew:
a slave that was not set up, or set up wrong, leaves black or stale stripes
at its band positions. What it cannot show is the analog merge on the way to
the monitor - that half is the register comparison (sli_golden.py +
sli_compare.py against the vendor driver).

Runs the all-ours Quake II lane (our ICD + our Glide) on whatever kernel
driver is installed, at SLI/AA config `--cfg`, plays demo1 to a fixed frame
(same frame every run) and saves the TGA and a PNG, plus a band report: the
mean brightness of each chip's band rows, so "chip 2 drew nothing" is a
number and not an impression.

    sli_shot.py 192.168.1.124 --cfg 5 --res 1024x768 --label vcrkmd

THE GAME SWITCHES THE MONITOR: Quake II through our ICD goes fullscreen at
--res and picks the highest refresh the driver lists at that size. So before
anything changes on the box, that mode - the highest refresh `vcrctl modes`
lists at WxH, at any depth - is checked on the host against the monitor's
EDID ranges (mode_sweep.py's gate). Under another driver that needs
--monitor-info: a `vcrctl info` saved from OUR driver on this box, used only
once the box's registry says that monitor is the one on it (or, when it
cannot say, with --i-have-checked-the-monitor). A refusal is rc 2.
"""
import argparse
import asyncio
import io
import json
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
sys.path.insert(0, str(REPO / "scripts" / "benchmarks"))
sys.path.insert(0, str(HERE))
import v56k_bench as vb      # noqa: E402
import v56k_shots as vs      # noqa: E402
import mode_sweep as ms      # noqa: E402  (the monitor gate every switching tool shares)

OUT = HERE.parent / "evidence" / "sli_shots"
TOOL = r"C:\vcr\vcrctl.exe"


class Q2AllOursShot(vs.ShotTitle, vb.Quake2AllOurs):
    shotdir = r"baseq2\scrnshot"

    def __init__(self, wait_frames=250, start="map base1"):
        vb.Quake2AllOurs.__init__(self)
        self.wait_frames = wait_frames
        self.start = start

    def bench_cfg(self):
        # `demomap demo1.dm2` under this many waits aborted with
        # "CM_InlineModel: bad number" (2026-09-26); a map spawn point is just
        # as repeatable - same map, same spawn, player standing still.
        lines = ['// generated by sli_shot.py', 'set cl_maxfps "1000"',
                 'set gl_swapinterval "0"', 'set gl_picmip "0"', self.start]
        lines += ["wait"] * self.wait_frames
        lines += ["screenshot", "wait", "wait", "wait", "quit", ""]
        return "\r\n".join(lines)


def band_report(png_img, chips, nlines):
    """Mean luminance of the rows each chip owns (row y -> chip (y/nlines) % chips)."""
    g = png_img.convert("L")
    w, h = g.size
    px = g.load()
    tot = [0] * chips
    cnt = [0] * chips
    for y in range(h):
        c = (y // nlines) % chips
        s = 0
        for x in range(0, w, 4):
            s += px[x, y]
        tot[c] += s
        cnt[c] += len(range(0, w, 4))
    return [round(tot[c] / cnt[c], 1) if cnt[c] else None for c in range(chips)]


async def main_async(a):
    from PIL import Image
    box = vb.Box(a.host)
    w, h = (int(v) for v in a.res.lower().split("x"))
    # the gate first, before the config is written or the game switches
    # anything: vcrctl answers which monitor and which modes
    await box.cmd(r"MKDIR C:\vcr")         # an existing one answers an error: fine
    await box.upload(TOOL, (HERE.parent / "out" / "vcrctl.exe").read_bytes())
    rng, calc, modes, why = await ms.fullscreen_gate(box.cmd, TOOL, [(w, h, a.depth, True)],
                                                     a.monitor_info,
                                                     a.i_have_checked_the_monitor)
    if why:
        ms.refuse(why)
        return 2
    print(f"the game's mode {modes[0]}  {ms.rates(calc, modes[0])}\n  monitor {ms.describe(rng)}")
    inst, _ = await vb.find_display_instance(box)
    key = vb.GLIDE_KEY_TMPL.format(inst=inst)
    await vb.apply_aa_config(box, key, a.cfg)
    t = Q2AllOursShot(a.frames, a.start)
    await t.identify(box)
    res, err = await t.capture(a.host, w, h, a.depth, {"FX_GLIDE_SWAPINTERVAL": "0"},
                               a.timeout)
    if err:
        print(f"FAIL: {err}")
        return 1
    name, data = res
    OUT.mkdir(parents=True, exist_ok=True)
    stem = f"q2_{a.label}_cfg{a.cfg}_{a.res}_{a.depth}"
    (OUT / f"{stem}.tga").write_bytes(data)
    img = Image.open(io.BytesIO(data))
    img.save(OUT / f"{stem}.png", optimize=True)
    rep = {"host": a.host, "label": a.label, "cfg": a.cfg, "res": a.res, "depth": a.depth,
           "frames": a.frames, "taken": time.strftime("%Y-%m-%dT%H:%M:%S"),
           "size": img.size, "engine": t.engine,
           "band_luma_per_chip": band_report(img, a.chips, a.nlines) if a.chips > 1 else None,
           "nlines": a.nlines, "chips": a.chips}
    (OUT / f"{stem}.json").write_text(json.dumps(rep, indent=1))
    print(json.dumps(rep))
    print(f"-> {OUT / (stem + '.png')}")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("host")
    ap.add_argument("--cfg", type=int, default=5)
    ap.add_argument("--res", default="1024x768")
    ap.add_argument("--depth", type=int, default=16)
    ap.add_argument("--frames", type=int, default=250)
    ap.add_argument("--label", required=True)
    ap.add_argument("--start", default="map base1", help="console command that sets the scene")
    ap.add_argument("--chips", type=int, default=4, help="for the band report")
    ap.add_argument("--nlines", type=int, default=8,
                    help="SLI band height the config uses, for the band report")
    ap.add_argument("--timeout", type=int, default=240)
    ap.add_argument("--monitor-info", help="a `vcrctl info` saved from OUR driver on this box: "
                    "the monitor's EDID ranges when the installed driver is not ours (used "
                    "only when the registry says that monitor is the one on the box)")
    ap.add_argument(ms.CHECKED_FLAG, action="store_true",
                    help="with --monitor-info: go on when the box's registry cannot confirm the "
                         "monitor - only after looking at it (a different one is still refused)")
    a = ap.parse_args()
    sys.exit(asyncio.run(main_async(a)))


if __name__ == "__main__":
    main()
