#!/usr/bin/env python3
"""sli_golden.py - the vendor driver's multi-chip state, captured LIVE.

With Quake II's demo looping on N-chip SLI (our ICD + our Glide, config
`--cfg`, on whatever kernel driver is installed - the vendor's, for a golden),
this loads vcrprobe.sys and records what only a running SLI session shows:

  - PCI config of every chip (raw 0xCF8 cycles: the HAL cannot see fn 1-3)
    and of the HiNT bridge (the V5 6000's clock GPIO lives at its 0xC4)
  - every chip's IO registers (probe-mem at its BAR0) and its 3D sliCtrl /
    aaCtrl (BAR0 + 0x20020C / 0x200210)
  - the master's VGA register file

then stops the game. The same capture on our driver, diffed against this one,
is the SLI port's acceptance test.

    sli_golden.py 192.168.1.124 --label amigamerlin-3.1-r11 --cfg 5
"""
import argparse
import asyncio
import json
import struct
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts" / "benchmarks"))
import v56k_bench as vb  # noqa: E402

TOOL = r"C:\vcr\vcrctl.exe"


class Quake2Loop(vb.Quake2AllOurs):
    """The all-ours Quake II lane, but the demo LOOPS until killed."""

    def bench_cfg(self):
        return "\r\n".join([
            "// generated by sli_golden.py - loop demo1 until killed",
            'set cl_maxfps "1000"', 'set gl_swapinterval "0"', 'set timedemo "0"',
            "demomap demo1.dm2",
            'set nextserver "demomap demo1.dm2"',
            "",
        ])


def jl(text):
    for ln in reversed(text.strip().splitlines()):
        if ln.startswith("{"):
            try:
                return json.loads(ln)
            except json.JSONDecodeError:
                return None
    return None


async def main_async(a):
    box = vb.Box(a.host)
    out = {"host": a.host, "label": a.label, "cfg": a.cfg, "cfg_via": "env+registry",
           "res": f"{a.w}x{a.h}x{a.depth}", "taken": time.strftime("%Y-%m-%dT%H:%M:%S")}
    vcr = lambda args: box.exec_(rf"{TOOL} {args}")   # noqa: E731

    # the probe first, so a failure costs nothing
    await box.upload(r"C:\vcr\vcrprobe.sys", (HERE.parent / "out" / "vcrprobe.sys").read_bytes())
    await box.upload(TOOL, (HERE.parent / "out" / "vcrctl.exe").read_bytes())
    await box.exec_(r"sc create vcrprobe type= kernel start= demand binPath= C:\vcr\vcrprobe.sys")
    await box.exec_("sc start vcrprobe")
    if not (jl(await vcr("probe-vga")) or {}).get("ok"):
        print("FAIL: vcrprobe did not load")
        return 2

    # the SLI/AA config our Glide reads (the runner's own mechanism, with its
    # read-back check): Settings\Glide under the active display instance
    inst, _ = await vb.find_display_instance(box)
    glide_key = vb.GLIDE_KEY_TMPL.format(inst=inst)
    await vb.apply_aa_config(box, glide_key, a.cfg)
    print(f"SLI/AA config {a.cfg} written under HKLM\\{glide_key}")
    t = Quake2Loop()
    await t.identify(box)
    # The config must reach Glide through the GAME'S ENVIRONMENT, as the bench
    # runner does it. Our Glide does not read the registry value: every capture
    # taken before 2026-09-26 03:20 passed {} here and ran Glide's default (2 =
    # every chip in SLI, no AA), whatever --cfg said.
    await t.prepare(box, a.w, a.h, a.depth,
                    {"SSTH3_SLI_AA_CONFIGURATION": str(a.cfg), "FX_GLIDE_SWAPINTERVAL": "0"})
    await t.start(box)
    print(f"game started, cfg {a.cfg}; settling {a.settle}s")
    await asyncio.sleep(a.settle)

    snaps = []
    for n in range(a.samples):
        s = {"pci": {}, "mem": {}}
        for fn in range(4):
            s["pci"][f"3:0.{fn}"] = (jl(await vcr(f"probe-pci 3 0 {fn} raw")) or {}).get("cfg")
        s["pci"]["bridge 2:0.0"] = (jl(await vcr("probe-pci 2 0 0")) or {}).get("cfg")
        for fn in range(4):
            cfg = s["pci"][f"3:0.{fn}"]
            if not cfg:
                continue
            bar0 = struct.unpack_from("<I", bytes.fromhex(cfg), 0x10)[0] & ~0xF
            if not bar0:
                continue
            io = jl(await vcr(f"probe-mem {bar0:x} 256")) or {}
            d3 = jl(await vcr(f"probe-mem {bar0 + 0x200200:x} 32")) or {}
            s["mem"][f"chip{fn}"] = {"bar0": f"{bar0:08x}", "io": io.get("dwords"),
                                     "3d_200": d3.get("dwords")}
        s["vga"] = (jl(await vcr("probe-vga")) or {}).get("vga")
        snaps.append(s)
        print(f"  sample {n + 1}/{a.samples}: "
              + ", ".join(f"{k} bar0 {v['bar0']}" for k, v in s["mem"].items()))
        await asyncio.sleep(2)
    out["samples"] = snaps

    await vb.graceful_kill(box, t.proc)
    await box.exec_("sc stop vcrprobe")
    await box.exec_("sc delete vcrprobe")
    p = Path(a.out) if a.out else HERE.parent / "golden" / f"sli_{a.label}_cfg{a.cfg}_{a.host}.json"
    p.write_text(json.dumps(out, indent=1))
    print(f"-> {p}")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("host")
    ap.add_argument("--label", required=True)
    ap.add_argument("--cfg", type=int, default=5, help="SLI/AA config (5 = 4-chip SLI)")
    ap.add_argument("--w", type=int, default=640)
    ap.add_argument("--h", type=int, default=480)
    ap.add_argument("--depth", type=int, default=16)
    ap.add_argument("--settle", type=int, default=25)
    ap.add_argument("--samples", type=int, default=2)
    ap.add_argument("--out")
    a = ap.parse_args()
    sys.exit(asyncio.run(main_async(a)))


if __name__ == "__main__":
    main()
